Module.item=selPat;selBed;updateErdBed;insertErdRecord;updateAdmStauts;updateErdRecord;selOrderExec;updateExec;selERDRegionBedByPat;selERDPatInfo

//更新病人状态 REG_PATADM
updateAdmStauts.Type=TSQL

updateAdmStauts.SQL=UPDATE REG_PATADM SET &

	OPT_DATE=SYSDATE,OPT_USER=<OPT_USER>,OPT_TERM=<OPT_TERM>, &
	
	ADM_STATUS=<ADM_STATUS> &
	
	WHERE CASE_NO=<CASE_NO>
	
updateAdmStauts.Debug=N



//查询病患
selPat.Type=TSQL

selPat.SQL=SELECT A.REG_DATE,A.MR_NO,B.PAT_NAME,A.TRIAGE_NO,A.DEPT_CODE,A.CASE_NO,C.ERD_REGION_CODE,A.ERD_LEVEL,A.REG_DATE ADM_DATE  &

	FROM REG_PATADM A LEFT JOIN ERD_BED C ON A.CASE_NO = C.CASE_NO &
	     LEFT JOIN ERD_RECORD D ON A.CASE_NO = D.CASE_NO,&
	     SYS_PATINFO B &
	
	WHERE A.MR_NO=B.MR_NO &
	AND   A.ADM_TYPE = 'E' &
	ORDER BY A.REG_DATE DESC

selPat.item=ADM_STATUS;REG_DATE;MR_NO;ERD_REGION;CASE_NO;START_DATE
selPat.REG_DATE=REG_DATE=<REG_DATE>
selPat.MR_NO=A.MR_NO=<MR_NO>
selPat.ADM_STATUS=ADM_STATUS=<ADM_STATUS>
selPat.ERD_REGION=C.ERD_REGION_CODE=<ERD_REGION>
selPat.CASE_NO=A.CASE_NO=<CASE_NO>
selPat.START_DATE=D.OUT_DATE BETWEEN <START_DATE> AND <END_DATE>
selPat.Debug=N


//查询床位
selBed.Type=TSQL

selBed.SQL=SELECT A.BED_NO,A.BED_DESC,A.MR_NO,B.PAT_NAME,A.CASE_NO,A.ERD_REGION_CODE &

  		FROM   ERD_BED A, SYS_PATINFO B &
  		
 		WHERE   A.MR_NO = B.MR_NO(+)

selBed.item=ERD_REGION_CODE;OCCUPY_FLG
selBed.ERD_REGION_CODE=ERD_REGION_CODE=<ERD_REGION_CODE>
selBed.OCCUPY_FLG=OCCUPY_FLG<>'Y'

selBed.Debug=N






//急诊病案首页更新ERD_BED
updateErdBed.Type=TSQL

updateErdBed.SQL=UPDATE ERD_BED SET &

	OPT_DATE=SYSDATE,OPT_USER=<OPT_USER>,OPT_TERM=<OPT_TERM>, &
	
	CASE_NO=<CASE_NO>,MR_NO=<MR_NO>,OCCUPY_FLG=<OCCUPY_FLG> &
	
	WHERE ERD_REGION_CODE=<ERD_REGION_CODE> AND BED_NO=<BED_NO>
	
updateErdBed.Debug=N


//急诊病案首页更新ERD_BED
updateErdRecord.Type=TSQL

updateErdRecord.SQL=UPDATE ERD_RECORD SET &

	PAT_NAME=<PAT_NAME>,SEX=<SEX>,&
			    
	BIRTH_DATE=<BIRTH_DATE>,AGE=<AGE>,MARRIGE=<MARRIGE>,OCCUPATION=<OCCUPATION>,RESID_PROVICE=<RESID_PROVICE>,&
			    
	RESID_COUNTRY=<RESID_COUNTRY>,FOLK=<FOLK>,NATION=<NATION>,IDNO=<IDNO>,CTZ1_CODE=<CTZ1_CODE>,&
			    
	OFFICE=<OFFICE>,O_ADDRESS=<O_ADDRESS>,O_TEL=<O_TEL>,O_POSTNO=<O_POSTNO>,H_ADDRESS=<H_ADDRESS>,&
			    
	H_POSTNO=<H_POSTNO>,CONTACTER=<CONTACTER>,RELATIONSHIP=<RELATIONSHIP>,CONT_ADDRESS=<CONT_ADDRESS>,&
			    
	CONT_TEL=<CONT_TEL>,IN_DATE=<IN_DATE>,IN_DEPT=<IN_DEPT>,ERD_REGION=<ERD_REGION>,OUT_DATE=<OUT_DATE>,&
			    		    
	OUT_DEPT=<OUT_DEPT>,OUT_ERD_REGION=<OUT_ERD_REGION>,REAL_STAY_DAYS=<REAL_STAY_DAYS>,OUT_DIAG_CODE=<OUT_DIAG_CODE>,&
			    
	CODE_REMARK=<CODE_REMARK>,CODE_STATUS=<CODE_STATUS>,GET_TIMES=<GET_TIMES>,SUCCESS_TIMES=<SUCCESS_TIMES>,DR_CODE=<DR_CODE>,&
			    		    
	OP_CODE=<OP_CODE>,OP_DATE=<OP_DATE>,MAIN_SUGEON=<MAIN_SUGEON>,OP_LEVEL=<OP_LEVEL>,HEAL_LV=<HEAL_LV>,&
			    		    
	ACCOMPANY_WEEK=<ACCOMPANY_WEEK>,ACCOMPANY_MONTH=<ACCOMPANY_MONTH>,ACCOMPANY_YEAR=<ACCOMPANY_YEAR>,ACCOMP_DATE=<ACCOMP_DATE>,STATUS=<STATUS>,&
			    
	OPT_USER=<OPT_USER>,OPT_DATE=SYSDATE,OPT_TERM=<OPT_TERM>,&
			    
	DISCHG_TYPE=<DISCHG_TYPE>,DISCHG_DATE=<DISCHG_DATE>,TRAN_HOSP=<TRAN_HOSP>,IPD_IN_DEPT=<IPD_IN_DEPT>,IPD_IN_DATE=<IPD_IN_DATE>, &
	
	RETURN_DATE=<RETURN_DATE> &
	
	WHERE CASE_NO=<CASE_NO>
	
updateErdRecord.Debug=N


//急诊病案首页插入ERD_RECORD
insertErdRecord.Type=TSQL

insertErdRecord.SQL=INSERT INTO ERD_RECORD (&

		    CASE_NO,MR_NO,ERD_NO,PAT_NAME,SEX,&
		    
		    BIRTH_DATE,AGE,MARRIGE,OCCUPATION,RESID_PROVICE,&
		    
		    RESID_COUNTRY,FOLK,NATION,IDNO,CTZ1_CODE,&
		    
		    OFFICE,O_ADDRESS,O_TEL,O_POSTNO,H_ADDRESS,&
		    
		    H_POSTNO,CONTACTER,RELATIONSHIP,CONT_ADDRESS,&
		    
		    CONT_TEL,IN_DATE,IN_DEPT,ERD_REGION,OUT_DATE,&
		    		    
		    OUT_DEPT,OUT_ERD_REGION,REAL_STAY_DAYS,OUT_DIAG_CODE,&
		    
		    CODE_REMARK,CODE_STATUS,GET_TIMES,SUCCESS_TIMES,DR_CODE,&
		    		    
		    OP_CODE,OP_DATE,MAIN_SUGEON,OP_LEVEL,HEAL_LV,&
		    		    
		    ACCOMPANY_WEEK,ACCOMPANY_MONTH,ACCOMPANY_YEAR,ACCOMP_DATE,STATUS,&
		    
		    OPT_USER,OPT_DATE,OPT_TERM,&
		    
		    DISCHG_TYPE,DISCHG_DATE,TRAN_HOSP,IPD_IN_DEPT,IPD_IN_DATE&
		
		)&
		
		VALUES (&

		<CASE_NO>,<MR_NO>,<ERD_NO>,<PAT_NAME>,<SEX>,&
				    
		<BIRTH_DATE>,<AGE>,<MARRIGE>,<OCCUPATION>,<RESID_PROVICE>,&
				    
		<RESID_COUNTRY>,<FOLK>,<NATION>,<IDNO>,<CTZ1_CODE>,&
				    
		<OFFICE>,<O_ADDRESS>,<O_TEL>,<O_POSTNO>,<H_ADDRESS>,&
				    
		<H_POSTNO>,<CONTACTER>,<RELATIONSHIP>,<CONT_ADDRESS>,&
		
		<CONT_TEL>,<IN_DATE>,<IN_DEPT>,<ERD_REGION>,<OUT_DATE>,&
						    
		<OUT_DEPT>,<OUT_ERD_REGION>,<REAL_STAY_DAYS>,<OUT_DIAG_CODE>,&
		
		<CODE_REMARK>,<CODE_STATUS>,<GET_TIMES>,<SUCCESS_TIMES>,<DR_CODE>,&
						    
		<OP_CODE>,<OP_DATE>,<MAIN_SUGEON>,<OP_LEVEL>,<HEAL_LV>,&
						    
		<ACCOMPANY_WEEK>,<ACCOMPANY_MONTH>,<ACCOMPANY_YEAR>,<ACCOMP_DATE>,<STATUS>,&
				    
		<OPT_USER>,SYSDATE,<OPT_TERM>,&
		
		<DISCHG_TYPE>,<DISCHG_DATE>,<TRAN_HOSP>,<IPD_IN_DEPT>,<IPD_IN_DATE>&
		
		)

insertErdRecord.Debug=N


//------------------------------------------------护士站-------------------------------------------

//护士站执行查询
selOrderExec.Type=TSQL

selOrderExec.SQL=SELECT B.BED_DESC AS BED_NO,A.MR_NO,C.PAT_NAME,A.LINKMAIN_FLG,A.LINK_NO,A.ORDER_DESC ||CASE &
                                                 WHEN TRIM(GOODS_DESC) IS NOT NULL OR TRIM(GOODS_DESC) <>''&
                                                   THEN '(' || GOODS_DESC || ')'&
                                                 ELSE '' END || CASE &
                                                 WHEN TRIM(SPECIFICATION) IS NOT NULL OR TRIM(SPECIFICATION) <>''&
                                                   THEN '(' || SPECIFICATION || ')'&
                                                 ELSE ''&
                                                END AS ORDER_DESC_AND_SPECIFICATION,A.MEDI_QTY,A.MEDI_UNIT,A.FREQ_CODE,A.ROUTE_CODE,&
            
         A.DR_CODE,A.DR_NOTE,A.DC_ORDER_DATE,A.NS_EXEC_CODE,A.NS_EXEC_DATE,&
         
         A.NS_NOTE,A.DC_DR_CODE,A.CASE_NO,A.SEQ_NO,A.RX_NO,A.SETMAIN_FLG,A.ORDERSET_GROUP_NO, &
         A.DOSE_TYPE,A.ORDER_CAT1_CODE,D.CLASSIFY_TYPE,A.ORDER_CODE ,A.ORDER_DATE,&
         A.ORDER_DESC||SPECIFICATION ORDERDESC,A.DISPENSE_QTY,A.DISPENSE_UNIT &
  	 FROM OPD_ORDER A LEFT JOIN SYS_PHAROUTE D ON A.ROUTE_CODE = D.ROUTE_CODE, ERD_BED B, SYS_PATINFO C &
  
 	 WHERE A.CASE_NO = B.CASE_NO &
 	
 	 AND A.MR_NO = C.MR_NO &
 	 
 	 AND HIDE_FLG<>'Y' &
	    
      	 ORDER BY   RX_NO, SEQ_NO, ORDER_DATE

selOrderExec.item=STATION_CODE;CASE_NO;EXECTYPE_YES;EXECTYPE_NO;NS_EXEC_DATE;CAT1_TYPEPHA;CAT1_TYPEPL;CAT1_TYPEENT;DSPN_KINDSTF;DSPN_KINDUD;DSPN_KINDDS;DSPN_KINDIG;DOSE_TYPEO;DOSE_TYPEE;DOSE_TYPEI;DOSE_TYPEF
selOrderExec.CASE_NO=A.CASE_NO=<CASE_NO>
selOrderExec.EXECTYPE_NO=A.NS_EXEC_CODE IS NULL
selOrderExec.EXECTYPE_YES=A.NS_EXEC_CODE IS NOT NULL
selOrderExec.NS_EXEC_DATE=A.NS_EXEC_DATE BETWEEN TO_DATE(<fromCheckDate>,'yyyyMMddhh24miss') AND TO_DATE(<toCheckDate>,'yyyyMMddhh24miss')
selOrderExec.CAT1_TYPEPHA=A.ORDER_CAT1_CODE LIKE 'PHA%'
selOrderExec.CAT1_TYPEPL=A.ORDER_CAT1_CODE NOT LIKE 'PHA%'
selOrderExec.DOSE_TYPEO=DOSE_TYPE = 'O'
selOrderExec.DOSE_TYPEE=DOSE_TYPE = 'E'
selOrderExec.DOSE_TYPEI=DOSE_TYPE = 'I'
selOrderExec.DOSE_TYPEF=DOSE_TYPE = 'F'

selOrderExec.Debug=N



//急诊留观护士执行—更新OPD_ORDER
updateExec.Type=TSQL

updateExec.SQL=UPDATE OPD_ORDER SET &

	OPT_DATE=SYSDATE,OPT_USER=<OPT_USER>,OPT_TERM=<OPT_TERM>,&
	
	NS_EXEC_CODE=<NS_EXEC_CODE>,NS_EXEC_DATE=<NS_EXEC_DATE>,NS_NOTE=<NS_NOTE> &
	
	WHERE CASE_NO=<CASE_NO> AND RX_NO=<RX_NO> AND SEQ_NO=<SEQ_NO>
	
updateExec.Debug=N


//查询床位
selERDRegionBedByPat.Type=TSQL
selERDRegionBedByPat.SQL=SELECT ERD_REGION_CODE,BED_NO &
                         FROM   ERD_BED &
                         WHERE  CASE_NO=<CASE_NO>
selERDRegionBedByPat.Debug=Y

//查询急诊留观病患基本信息
selERDPatInfo.Type=TSQL
selERDPatInfo.SQL=SELECT A.REAL_STAY_DAYS ADM_DAYS,A.MR_NO,B.ADM_DATE IN_DATE,'' IPD_NO,C.ERD_REGION_CODE STATION_CODE, &
                         C.BED_NO,C.BED_DESC,D.CHN_DESC ERD_REGION_DESC,DEPT_CODE IN_DEPT_CODE,OUT_DATE &
                  FROM   ERD_RECORD A LEFT JOIN ERD_BED C ON A.CASE_NO = C.CASE_NO &
                                      LEFT JOIN SYS_DICTIONARY D ON C.ERD_REGION_CODE = D.ID AND D.GROUP_ID = 'ERD_REGION',&
                                      REG_PATADM B &
                  WHERE  A.CASE_NO = <CASE_NO>  &
                  AND    A.CASE_NO = B.CASE_NO
selERDPatInfo.Debug=N








