
package action.udd.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;

import com.dongyang.config.TConfig;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-01-16T10:30:35.200+08:00
 * Generated source version: 2.5.2
 * 
 */
public final class SpcOdiService_SpcOdiServiceImplPort_Client {

//    private static final QName SERVICE_NAME = new QName("http://services.spc.action/", "SpcOdiServiceImplService");

    private SpcOdiService_SpcOdiServiceImplPort_Client() {
    }
    private static  TConfig getProp() {
        TConfig config = TConfig.getConfig("WEB-INF\\config\\system\\TConfig.x");
        return config;
	}
 
	 public  static String getWebServicesIp(){
		 TConfig config = getProp() ;
		 String url = config.getString("", "WEB_SERVICES_IP");
		 return url;
	 }
    /**
     * 住院药房调配
     * @param odiDspnms
     * @return
     */
    public static String examine(SpcOdiDspnms odiDspnms){
    	String ip = getWebServicesIp();
    	String url = "http://"+ip+"/services/SpcOdiService" ;
    	JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean(); 
        factory.setAddress(url); 
        factory.setServiceClass(SpcOdiService.class); 
        SpcOdiService port = (SpcOdiService) factory.create();
        String result = port.examine(odiDspnms);
        return result ;
    }
    
    /**
     * 住院药房退药确认
     * @param odiDspnms
     * @return
     */
    public static String onUpdateRtnCfm(SpcOdiDspnms odiDspnms){
    	String ip = getWebServicesIp();
    	String url = "http://"+ip+"/services/SpcOdiService" ;
    	JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean(); 
        factory.setAddress(url); 
        factory.setServiceClass(SpcOdiService.class); 
        //服务端SERVICES接口
        SpcOdiService port = (SpcOdiService) factory.create();
        //调用哪个方法
        String result = port.onUpdateRtnCfm(odiDspnms);
        return result ;
    }
    /**
     * 住院药房检测库存
     * @param odiDspnms
     * @return
     */
    public static String onCheckStockQty(SpcOdiDspnms odiDspnms){
    	String ip = getWebServicesIp();
    	String url = "http://"+ip+"/services/SpcOdiService" ;
    	JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean(); 
        factory.setAddress(url); 
        factory.setServiceClass(SpcOdiService.class); 
        //服务端SERVICES接口
        SpcOdiService port = (SpcOdiService) factory.create();
        //调用哪个方法
        String result = port.onCheckStockQty(odiDspnms);
        return result ;
    }
    
    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SpcOdiServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
      /**  SpcOdiServiceImplService ss = new SpcOdiServiceImplService(wsdlURL, SERVICE_NAME);
        SpcOdiService port = ss.getSpcOdiServiceImplPort();  
        
        
        {
        System.out.println("Invoking examine...");
        action.udd.client.SpcOdiDspnms _examine_arg0 = new SpcOdiDspnms();
        java.lang.String _examine__return = port.examine(_examine_arg0);
        System.out.println("examine.result=" + _examine__return);


        }
        
        /**
        {
        System.out.println("Invoking onUpdateRtnCfm...");
        action.udd.client.SpcOdiDspnms _onUpdateRtnCfm_arg0 = new SpcOdiDspnms();
         String _onUpdateRtnCfm__return = onUpdateRtnCfm(_onUpdateRtnCfm_arg0);
        //java.lang.String _onUpdateRtnCfm__return = port.onUpdateRtnCfm(_onUpdateRtnCfm_arg0);
        System.out.println("onUpdateRtnCfm.result=" + _onUpdateRtnCfm__return);


        }*/
        System.exit(0);
    }

}
