package jdo.spc.bsm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-05-21T08:54:31.500+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.willach.com/", name = "ConsisServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ConsisServiceSoap {

    @RequestWrapper(localName = "TransHisData", targetNamespace = "http://www.willach.com/", className = "client.TransHisData")
    @WebMethod(operationName = "TransHisData", action = "http://www.willach.com/TransHisData")
    @ResponseWrapper(localName = "TransHisDataResponse", targetNamespace = "http://www.willach.com/", className = "client.TransHisDataResponse")
    public void transHisData(
        @WebParam(name = "opwinid", targetNamespace = "http://www.willach.com/")
        java.lang.String opwinid,
        @WebParam(name = "optype", targetNamespace = "http://www.willach.com/")
        int optype,
        @WebParam(name = "opstr", targetNamespace = "http://www.willach.com/")
        java.lang.String opstr,
        @WebParam(name = "opip", targetNamespace = "http://www.willach.com/")
        java.lang.String opip,
        @WebParam(name = "opmanno", targetNamespace = "http://www.willach.com/")
        java.lang.String opmanno,
        @WebParam(name = "opmanname", targetNamespace = "http://www.willach.com/")
        java.lang.String opmanname,
        @WebParam(mode = WebParam.Mode.INOUT, name = "retval", targetNamespace = "http://www.willach.com/")
        javax.xml.ws.Holder<java.lang.Integer> retval,
        @WebParam(mode = WebParam.Mode.INOUT, name = "retmsg", targetNamespace = "http://www.willach.com/")
        javax.xml.ws.Holder<java.lang.String> retmsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "TransHisDataResult", targetNamespace = "http://www.willach.com/")
        javax.xml.ws.Holder<java.lang.Integer> transHisDataResult
    );

    @WebResult(name = "TransConsisDataResult", targetNamespace = "http://www.willach.com/")
    @RequestWrapper(localName = "TransConsisData", targetNamespace = "http://www.willach.com/", className = "client.TransConsisData")
    @WebMethod(operationName = "TransConsisData", action = "http://www.willach.com/TransConsisData")
    @ResponseWrapper(localName = "TransConsisDataResponse", targetNamespace = "http://www.willach.com/", className = "client.TransConsisDataResponse")
    public java.lang.String transConsisData(
        @WebParam(name = "opstr", targetNamespace = "http://www.willach.com/")
        java.lang.String opstr
    );

    @RequestWrapper(localName = "ClearLog", targetNamespace = "http://www.willach.com/", className = "client.ClearLog")
    @WebMethod(operationName = "ClearLog", action = "http://www.willach.com/ClearLog")
    @ResponseWrapper(localName = "ClearLogResponse", targetNamespace = "http://www.willach.com/", className = "client.ClearLogResponse")
    public void clearLog(
        @WebParam(name = "months", targetNamespace = "http://www.willach.com/")
        int months
    );

    @RequestWrapper(localName = "TransConsisDataPB", targetNamespace = "http://www.willach.com/", className = "client.TransConsisDataPB")
    @WebMethod(operationName = "TransConsisDataPB", action = "http://www.willach.com/TransConsisDataPB")
    @ResponseWrapper(localName = "TransConsisDataPBResponse", targetNamespace = "http://www.willach.com/", className = "client.TransConsisDataPBResponse")
    public void transConsisDataPB(
        @WebParam(name = "opstr", targetNamespace = "http://www.willach.com/")
        java.lang.String opstr,
        @WebParam(mode = WebParam.Mode.INOUT, name = "retval", targetNamespace = "http://www.willach.com/")
        javax.xml.ws.Holder<java.lang.Integer> retval,
        @WebParam(mode = WebParam.Mode.INOUT, name = "retmsg", targetNamespace = "http://www.willach.com/")
        javax.xml.ws.Holder<java.lang.String> retmsg,
        @WebParam(mode = WebParam.Mode.OUT, name = "TransConsisDataPBResult", targetNamespace = "http://www.willach.com/")
        javax.xml.ws.Holder<java.lang.Integer> transConsisDataPBResult
    );

    @WebResult(name = "HelloWorldResult", targetNamespace = "http://www.willach.com/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://www.willach.com/", className = "client.HelloWorld")
    @WebMethod(operationName = "HelloWorld", action = "http://www.willach.com/HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://www.willach.com/", className = "client.HelloWorldResponse")
    public java.lang.String helloWorld();
}
