
package action.device.client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-08-08T12:31:59.988+08:00
 * Generated source version: 2.5.2
 * 
 */
 
public class DoRun_DoRunServicePort_Server{

    protected DoRun_DoRunServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new DoRunImpl();
        String address = "http://192.168.0.118:8080/CoatHanger/chWebService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new DoRun_DoRunServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
