
package action.device.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-08-08T12:31:59.955+08:00
 * Generated source version: 2.5.2
 * 
 */
public final class DoRun_DoRunServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.webservice.com", "DoRunServiceName");

    private DoRun_DoRunServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DoRunServiceName.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DoRunServiceName ss = new DoRunServiceName(wsdlURL, SERVICE_NAME);
        DoRun port = ss.getDoRunServicePort();  
        
        {
        System.out.println("Invoking doRun...");
        java.lang.String _doRun_p1 = "";
        boolean _doRun__return = port.doRun(_doRun_p1);
        System.out.println("doRun.result=" + _doRun__return);


        }

        System.exit(0);
    }

}
