
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package action.device.client;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-08-08T12:31:59.974+08:00
 * Generated source version: 2.5.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "DoRunServiceName",
                      portName = "DoRunServicePort",
                      targetNamespace = "http://www.webservice.com",
                      wsdlLocation = "http://192.168.0.118:8080/CoatHanger/chWebService?wsdl",
                      endpointInterface = "client.DoRun")
                      
public class DoRunImpl implements DoRun {

    private static final Logger LOG = Logger.getLogger(DoRunImpl.class.getName());

    /* (non-Javadoc)
     * @see client.DoRun#doRun(java.lang.String  p1 )*
     */
    public boolean doRun(java.lang.String p1) { 
        LOG.info("Executing operation doRun");
        System.out.println(p1);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
