package action.device.client;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-08-08T12:31:59.990+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "DoRunServiceName", 
                  wsdlLocation = "http://192.168.0.118:8080/CoatHanger/chWebService?wsdl",
                  targetNamespace = "http://www.webservice.com") 
public class DoRunServiceName extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.webservice.com", "DoRunServiceName");
    public final static QName DoRunServicePort = new QName("http://www.webservice.com", "DoRunServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.118:8080/CoatHanger/chWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DoRunServiceName.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.118:8080/CoatHanger/chWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DoRunServiceName(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DoRunServiceName(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DoRunServiceName() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DoRunServiceName(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DoRunServiceName(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DoRunServiceName(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns DoRun
     */
    @WebEndpoint(name = "DoRunServicePort")
    public DoRun getDoRunServicePort() {
        return super.getPort(DoRunServicePort, DoRun.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DoRun
     */
    @WebEndpoint(name = "DoRunServicePort")
    public DoRun getDoRunServicePort(WebServiceFeature... features) {
        return super.getPort(DoRunServicePort, DoRun.class, features);
    }

}
