package action.device.client;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-08-08T12:31:59.982+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.webservice.com", name = "DoRun")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface DoRun {

    @WebResult(name = "return", targetNamespace = "http://www.webservice.com", partName = "return")
    @WebMethod
    public boolean doRun(
        @WebParam(partName = "p1", name = "p1")
        java.lang.String p1
    );
}
