package action.device.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-04-26T11:43:39.668+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://ws.demo.sunray.com/", name = "RfidControllerService")
@XmlSeeAlso({ObjectFactory.class})
public interface RfidControllerService {

    @RequestWrapper(localName = "startScan", targetNamespace = "http://ws.demo.sunray.com/", className = "action.device.client.StartScan")
    @WebMethod
    @ResponseWrapper(localName = "startScanResponse", targetNamespace = "http://ws.demo.sunray.com/", className = "action.device.client.StartScanResponse")
    public void startScan(
        @WebParam(name = "readerId", targetNamespace = "")
        java.lang.String readerId
    );

    @RequestWrapper(localName = "disconnect", targetNamespace = "http://ws.demo.sunray.com/", className = "action.device.client.Disconnect")
    @WebMethod
    @ResponseWrapper(localName = "disconnectResponse", targetNamespace = "http://ws.demo.sunray.com/", className = "action.device.client.DisconnectResponse")
    public void disconnect(
        @WebParam(name = "readerId", targetNamespace = "")
        java.lang.String readerId
    );

    @RequestWrapper(localName = "stopScan", targetNamespace = "http://ws.demo.sunray.com/", className = "action.device.client.StopScan")
    @WebMethod
    @ResponseWrapper(localName = "stopScanResponse", targetNamespace = "http://ws.demo.sunray.com/", className = "action.device.client.StopScanResponse")
    public void stopScan(
        @WebParam(name = "readerId", targetNamespace = "")
        java.lang.String readerId
    );

    @RequestWrapper(localName = "connect", targetNamespace = "http://ws.demo.sunray.com/", className = "action.device.client.Connect")
    @WebMethod
    @ResponseWrapper(localName = "connectResponse", targetNamespace = "http://ws.demo.sunray.com/", className = "action.device.client.ConnectResponse")
    public void connect(
        @WebParam(name = "readerId", targetNamespace = "")
        java.lang.String readerId
    );
}
