package action.spc.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-12-25T16:37:57.234+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "IndServiceService", 
                  wsdlLocation = "http://172.20.116.102:8080/web/services/IndService?wsdl",
                  targetNamespace = "http://ind.jdo/") 
public class IndServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ind.jdo/", "IndServiceService");
    public final static QName IndServicePort = new QName("http://ind.jdo/", "IndServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.20.116.102:8080/web/services/IndService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IndServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.20.116.102:8080/web/services/IndService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IndServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IndServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IndServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
     
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IndServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IndServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IndServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns IIndService
     */
    @WebEndpoint(name = "IndServicePort")
    public IIndService getIndServicePort() {
        return super.getPort(IndServicePort, IIndService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IIndService
     */
    @WebEndpoint(name = "IndServicePort")
    public IIndService getIndServicePort(WebServiceFeature... features) {
        return super.getPort(IndServicePort, IIndService.class);
    }

}
