
package action.spc.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-12-22T12:12:24.665+08:00
 * Generated source version: 2.5.2
 * 
 */
public final class SpcService_SpcServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ind.jdo/", "IndServiceService");

    private SpcService_SpcServiceImplPort_Client() { 
    }
    
    public static String onSaveSpcRequest(IndDispensem indDispensem){
    	 URL wsdlURL = IndServiceService.WSDL_LOCATION;
    	 IndServiceService ss = new IndServiceService(wsdlURL, SERVICE_NAME);
         IIndService port = ss.getIndServicePort();   
         String result = port.onSaveDispenseDM(indDispensem);
         return result ;
    }
    
    public static String onStop(IndDispensem indDispensem){
    	URL wsdlURL = IndServiceService.WSDL_LOCATION;
   	 	IndServiceService ss = new IndServiceService(wsdlURL, SERVICE_NAME);
        IIndService port = ss.getIndServicePort();   
        String result = port.onStop(indDispensem);
        return result ;
   }
    
    
    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IndServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IndServiceService ss = new IndServiceService(wsdlURL, SERVICE_NAME);
        IIndService port = ss.getIndServicePort();   
        
        
        {
        System.out.println("Invoking onSaveSpcRequest...");
        IndDispensem _onSaveSpcRequest_arg0 = new IndDispensem();
        java.lang.String _onSaveSpcRequest__return = port.onSaveDispenseDM(_onSaveSpcRequest_arg0);
        System.out.println("onSaveSpcRequest.result=" + _onSaveSpcRequest__return);


        }
       

        System.exit(0);
    }

}
