package jdo.spc;

import com.dongyang.data.TParm;
import com.dongyang.jdo.TJDODBTool;
import com.dongyang.jdo.TJDOTool;
import com.javahis.util.StringUtil;

/**
 * <p>
 * Title:麻精追踪报表
 * </p>
 * 
 * <p>
 * Description:麻精追踪报表
 * </p>
 * 
 * <p>
 * Copyright: Copyright (c) 2013
 * </p>
 * 
 * <p>
 * Company: javahis
 * </p>
 * 
 * @author shendr 2013-11-27
 * @version 1.0
 */
public class SPCDrugSearchTool extends TJDOTool {

	private static SPCDrugSearchTool instanceObject;

	/**
	 * 获取实例对象
	 * 
	 * @return
	 */
	public static SPCDrugSearchTool getInstance() {
		if (instanceObject == null) {
			instanceObject = new SPCDrugSearchTool();
		}
		return instanceObject;
	}

	/**
	 * 查询
	 * 
	 * @return
	 */
	public TParm query(TParm parm) {
		String order_code = parm.getValue("ORDER_CODE");
		String con1 = "";
		if (!StringUtil.isNullString(order_code)) {
			con1 = "AND X.ORDER_CODE='" + order_code + "' ";
		}
		String bar_code = parm.getValue("BAR_CODE");
		String con2 = "";
		if (!StringUtil.isNullString(bar_code)) {
			con2 = "AND X.BAR_CODE='" + bar_code + "' ";
		}
		String start_time = parm.getValue("START_TIME");
		String end_time = parm.getValue("END_TIME");
		String con3 = "";
		if (!StringUtil.isNullString(start_time)
				&& StringUtil.isNullString(end_time)) {
			con3 = "AND X.EXE_DATE >= TO_DATE('" + start_time
					+ "','YYYY-MM-DD HH24:MI:SS') ";
		} else if (StringUtil.isNullString(start_time)
				&& !StringUtil.isNullString(end_time)) {
			con3 = "AND X.EXE_DATE <= TO_DATE('" + end_time
					+ "','YYYY-MM-DD HH24:MI:SS') ";
		} else if (!StringUtil.isNullString(start_time)
				&& !StringUtil.isNullString(end_time)) {
			con3 = "AND X.EXE_DATE BETWEEN TO_DATE('" + start_time
					+ "','YYYY-MM-DD HH24:MI:SS') " + "AND TO_DATE('"
					+ end_time + "','YYYY-MM-DD HH24:MI:SS') ";
		}
		String sql = "SELECT X.ORDER_CODE,X.ORDER_DESC,X.SPECIFICATION,X.BAR_CODE,X.EXE_DATE,X.TYPE, "
				+ "X.ORG_CHN_DESC,X.MR_NO,X.PAT_NAME,X.EXE_NS,X.ORDER_DR "
				+ "FROM "
				+ "( "
				// 药库入库
				+ "SELECT A.ORDER_CODE,F.ORDER_DESC,F.SPECIFICATION,A.TOXIC_ID AS BAR_CODE,C.REQUEST_DATE AS EXE_DATE,'A' AS TYPE, "
				+ "E.ORG_CHN_DESC,'' AS MR_NO,'' AS PAT_NAME,'' AS EXE_NS,'' AS ORDER_DR "
				+ "FROM IND_TOXICD A,IND_TOXICM B,IND_DISPENSEM C,IND_ORG E,PHA_BASE F "
				+ "WHERE A.IS_PACK='Y' "
				+ "AND A.DISPENSE_NO=B.DISPENSE_NO "
				+ "AND A.DISPENSE_SEQ_NO=B.DISPENSE_SEQ_NO "
				+ "AND A.CONTAINER_ID=B.CONTAINER_ID "
				+ "AND B.DISPENSE_NO=C.DISPENSE_NO "
				+ "AND C.TO_ORG_CODE=E.ORG_CODE "
				+ "AND A.ORDER_CODE=F.ORDER_CODE "
				+ "UNION ALL "
				// 药库出库
				+ "SELECT A.ORDER_CODE,F.ORDER_DESC,F.SPECIFICATION,A.TOXIC_ID AS BAR_CODE,C.DISPENSE_DATE AS EXE_DATE,'B' AS TYPE, "
				+ "E.ORG_CHN_DESC,'' AS MR_NO,'' AS PAT_NAME,'' AS EXE_NS,'' AS ORDER_DR "
				+ "FROM IND_TOXICD A,IND_TOXICM B,IND_DISPENSEM C,IND_ORG E,PHA_BASE F "
				+ "WHERE A.IS_PACK='Y' "
				+ "AND A.DISPENSE_NO=B.DISPENSE_NO "
				+ "AND A.DISPENSE_SEQ_NO=B.DISPENSE_SEQ_NO "
				+ "AND A.CONTAINER_ID=B.CONTAINER_ID "
				+ "AND B.DISPENSE_NO=C.DISPENSE_NO "
				+ "AND C.TO_ORG_CODE=E.ORG_CODE "
				+ "AND A.ORDER_CODE=F.ORDER_CODE "
				+ "UNION ALL "
				// 入药房
				+ "SELECT A.ORDER_CODE,F.ORDER_DESC,F.SPECIFICATION,A.TOXIC_ID AS BAR_CODE,C.WAREHOUSING_DATE AS EXE_DATE,'C' AS TYPE, "
				+ "D.ORG_CHN_DESC,'' AS MR_NO,'' AS PAT_NAME,'' AS EXE_NS,'' AS ORDER_DR "
				+ "FROM IND_TOXICD A,IND_TOXICM B,IND_DISPENSEM C,IND_ORG D,PHA_BASE F "
				+ "WHERE A.DISPENSE_NO = B.DISPENSE_NO "
				+ "AND A.DISPENSE_SEQ_NO = B.DISPENSE_SEQ_NO "
				+ "AND A.CONTAINER_ID = B.CONTAINER_ID "
				+ "AND B.IS_STORE = 'Y' "
				+ "AND B.DISPENSE_NO = C.DISPENSE_NO "
				+ "AND C.APP_ORG_CODE = D.ORG_CODE "
				+ "AND A.ORDER_CODE = F.ORDER_CODE "
				+ "UNION ALL "
				// 药房出给手术室
				+ "SELECT A.ORDER_CODE,D.ORDER_DESC,D.SPECIFICATION,A.TOXIC_ID AS BAR_CODE, "
				+ "A.OPT_DATE AS EXE_DATE,'D' AS TYPE,E.ORG_CHN_DESC  AS ORG_CHN_DESC, "
				+ "'' AS MR_NO,'' AS PAT_NAME,'' AS EXE_NS,'' AS ORDER_DR "
				+ "FROM IND_TOXICD A, IND_DISPENSEM B,IND_TOXICM C,PHA_BASE D ,IND_ORG E "
				+ "WHERE A.DISPENSE_NO = B.REQUEST_NO  "
				+ "AND A.CONTAINER_ID=C.CONTAINER_ID "
				+ "AND A.DISPENSE_NO = C.DISPENSE_NO "
				+ "AND A.ORDER_CODE = D.ORDER_CODE "
				+ "AND B.TO_ORG_CODE= E.ORG_CODE "
				+ "AND B.TO_ORG_CODE='040103' "
				+ "UNION ALL "
				// 药房出给病区
				+ "SELECT A.ORDER_CODE,A.ORDER_DESC,A.SPECIFICATION,B.TOXIC_ID AS BAR_CODE, "
				+ "B.OPT_DATE AS EXE_DATE,'D' AS TYPE,C.ORG_CHN_DESC  AS ORG_CHN_DESC, "
				+ "'' AS MR_NO,'' AS PAT_NAME,'' AS EXE_NS,'' AS ORDER_DR "
				+ "FROM ODI_DSPNM A ,IND_TOXICD B,IND_ORG C "
				+ "WHERE A.PHA_DISPENSE_NO = B.DISPENSE_NO "
				+ "AND A.TAKEMED_ORG='1' "
				+ "AND A.EXEC_DEPT_CODE = C.ORG_CODE "
				+ "AND (A.CTRLDRUGCLASS_CODE IS NOT NULL "
				+ "AND A.CTRLDRUGCLASS_CODE IN (SELECT CTRLDRUGCLASS_CODE "
				+ "     	   FROM SYS_CTRLDRUGCLASS WHERE CTRL_FLG = 'Y')) "
				+ "UNION ALL "
				// +
				// "SELECT A.ORDER_CODE,E.ORDER_DESC,E.SPECIFICATION,A.TOXIC_ID AS BAR_CODE,F.BOXED_DATE AS EXE_DATE,'D' AS TYPE, "
				// +
				// "C.ORG_CHN_DESC,'' AS MR_NO,'' AS PAT_NAME,'' AS EXE_NS,'' AS ORDER_DR "
				// +
				// "FROM IND_TOXICD A,IND_TOXICM F,IND_CABINET B,IND_ORG C,PHA_BASE E "
				// + "WHERE A.DISPENSE_NO=F.DISPENSE_NO "
				// + "AND A.DISPENSE_SEQ_NO=F.DISPENSE_SEQ_NO "
				// + "AND A.CONTAINER_ID=F.CONTAINER_ID "
				// + "AND F.IS_BOXED = 'Y' "
				// + "AND F.CABINET_ID=B.CABINET_ID "
				// + "AND B.ORG_CODE=C.ORG_CODE "
				// + "AND C.ORG_TYPE='B' "
				// + "AND A.ORDER_CODE = E.ORDER_CODE "
				// + "UNION ALL "
				// 入三级库
				+ "SELECT A.ORDER_CODE,C.ORDER_DESC,C.SPECIFICATION,A.TOXIC_ID AS BAR_CODE,A.OPT_DATE AS EXE_DATE,'E' AS TYPE, "
				+ "E.ORG_CHN_DESC,'' AS MR_NO,'' AS PAT_NAME,'' AS EXE_NS,'' AS ORDER_DR "
				+ "FROM IND_TOXICD A,IND_TOXICM B,PHA_BASE C,IND_CABINET D,IND_ORG E "
				+ "WHERE A.DISPENSE_NO = B.DISPENSE_NO "
				+ "AND A.DISPENSE_SEQ_NO = B.DISPENSE_SEQ_NO "
				+ "AND A.CONTAINER_ID = B.CONTAINER_ID "
				+ "AND B.IS_STORE = 'Y' "
				+ "AND A.ORDER_CODE = C.ORDER_CODE "
				+ "AND A.CABINET_ID=D.CABINET_ID "
				+ "AND D.ORG_CODE=E.ORG_CODE "
				+ "UNION ALL "
				// 病区发药
				// +
				// "SELECT A.ORDER_CODE,A.ORDER_DESC,A.SPECIFICATION,COALESCE(A.TOXIC_ID1,A.TOXIC_ID2,A.TOXIC_ID3) AS BAR_CODE, "
				// +
				// "A.TAKEMED_DATE AS EXE_DATE,'F' AS TYPE,B.STATION_DESC AS ORG_CHN_DESC, "
				// +
				// "'' AS MR_NO,'' AS PAT_NAME,'' AS EXE_NS,C.USER_NAME AS ORDER_DR "
				// + "FROM IND_CABDSPN A,SYS_STATION B,SYS_OPERATOR C "
				// + "WHERE A.CAT1_TYPE = 'PHA' "
				// + "AND A.TAKEMED_ORG='1' "
				// +
				// "AND (A.CTRLDRUGCLASS_CODE IS NOT NULL AND A.CTRLDRUGCLASS_CODE IN "
				// +
				// "(SELECT CTRLDRUGCLASS_CODE FROM SYS_CTRLDRUGCLASS WHERE CTRL_FLG='Y')) "
				// + "AND A.STATION_CODE = B.STATION_CODE "
				// + "AND A.VS_DR_CODE = C.USER_ID "
				// + "UNION ALL "
				+ "SELECT A.ORDER_CODE,A.ORDER_DESC,A.SPECIFICATION,A.TOXIC_ID1 AS BAR_CODE, "
				+ "A.TAKEMED_DATE AS EXE_DATE,'F' AS TYPE,B.STATION_DESC AS ORG_CHN_DESC, "
				+ "A.MR_NO,E.PAT_NAME AS PAT_NAME,'' AS EXE_NS,C.USER_NAME AS ORDER_DR "
				+ "FROM IND_CABDSPN A,SYS_STATION B,SYS_OPERATOR C,IND_TOXICD D  ,SYS_PATINFO E "
				+ "WHERE A.CAT1_TYPE = 'PHA' "
				+ "AND A.TAKEMED_ORG='1' "
				+ "AND (A.CTRLDRUGCLASS_CODE IS NOT NULL AND A.CTRLDRUGCLASS_CODE IN "
				+ "    (SELECT CTRLDRUGCLASS_CODE FROM SYS_CTRLDRUGCLASS WHERE CTRL_FLG='Y')) "
				+ "AND A.STATION_CODE = B.STATION_CODE "
				+ "AND A.VS_DR_CODE = C.USER_ID "
				+ "AND A.TOXIC_ID1 = D.TOXIC_ID "
				+ "AND A.MR_NO=E.MR_NO "
				+ "UNION ALL "
				+ "SELECT A.ORDER_CODE,A.ORDER_DESC,A.SPECIFICATION,A.TOXIC_ID2 AS BAR_CODE, "
				+ "A.TAKEMED_DATE AS EXE_DATE,'F' AS TYPE,B.STATION_DESC AS ORG_CHN_DESC, "
				+ "A.MR_NO,E.PAT_NAME AS PAT_NAME,'' AS EXE_NS,C.USER_NAME AS ORDER_DR "
				+ "FROM IND_CABDSPN A,SYS_STATION B,SYS_OPERATOR C,IND_TOXICD D  ,SYS_PATINFO E "
				+ "WHERE A.CAT1_TYPE = 'PHA' "
				+ "AND A.TAKEMED_ORG='1' "
				+ "AND (A.CTRLDRUGCLASS_CODE IS NOT NULL AND A.CTRLDRUGCLASS_CODE IN "
				+ "    (SELECT CTRLDRUGCLASS_CODE FROM SYS_CTRLDRUGCLASS WHERE CTRL_FLG='Y')) "
				+ "AND A.STATION_CODE = B.STATION_CODE "
				+ "AND A.VS_DR_CODE = C.USER_ID "
				+ "AND A.TOXIC_ID2 = D.TOXIC_ID "
				+ "AND A.MR_NO=E.MR_NO "
				+ "UNION ALL "
				+ "SELECT A.ORDER_CODE,A.ORDER_DESC,A.SPECIFICATION,A.TOXIC_ID3 AS BAR_CODE, "
				+ "A.TAKEMED_DATE AS EXE_DATE,'F' AS TYPE,B.STATION_DESC AS ORG_CHN_DESC, "
				+ "A.MR_NO,E.PAT_NAME AS PAT_NAME,'' AS EXE_NS,C.USER_NAME AS ORDER_DR "
				+ "FROM IND_CABDSPN A,SYS_STATION B,SYS_OPERATOR C,IND_TOXICD D  ,SYS_PATINFO E "
				+ "WHERE A.CAT1_TYPE = 'PHA' "
				+ "AND A.TAKEMED_ORG='1' "
				+ "AND (A.CTRLDRUGCLASS_CODE IS NOT NULL AND A.CTRLDRUGCLASS_CODE IN "
				+ "    (SELECT CTRLDRUGCLASS_CODE FROM SYS_CTRLDRUGCLASS WHERE CTRL_FLG='Y')) "
				+ "AND A.STATION_CODE = B.STATION_CODE "
				+ "AND A.VS_DR_CODE = C.USER_ID "
				+ "AND A.TOXIC_ID3 = D.TOXIC_ID "
				+ "AND A.MR_NO= E.MR_NO "
				+ "UNION ALL "
				// 手术介入发药
				+ "SELECT A.ORDER_CODE,D.ORDER_DESC,D.SPECIFICATION,A.TOXIC_ID AS BAR_CODE,C.BOXED_DATE AS EXE_DATE,'F' AS TYPE, "
				+ "F.ORG_CHN_DESC,'' AS MR_NO,'' AS PAT_NAME,'' AS EXE_NS,'' AS ORDER_DR "
				+ "FROM IND_TOXICD A, IND_TOXICM C,PHA_BASE D,IND_CABINET E,IND_ORG F "
				+ "WHERE A.DISPENSE_NO = C.DISPENSE_NO "
				+ "AND A.DISPENSE_SEQ_NO = C.DISPENSE_SEQ_NO "
				+ "AND A.CONTAINER_ID=C.CONTAINER_ID "
				+ "AND C.IS_BOXED = 'Y' "
				+ "AND A.ORDER_CODE = D.ORDER_CODE "
				+ "AND C.CABINET_ID=E.CABINET_ID "
				+ "AND E.ORG_CODE=F.ORG_CODE "
				+ "AND F.ORG_TYPE='C' "
				+ "UNION ALL "
				// 急诊区发药
				+ "SELECT A.ORDER_CODE,B.ORDER_DESC,B.SPECIFICATION,COALESCE(A.TOXIC_ID1,A.TOXIC_ID2,A.TOXIC_ID3) AS BAR_CODE, "
				+ "A.PHA_DISPENSE_DATE AS EXE_DATE,'F' AS TYPE,'急诊区' AS ORG_CHN_DESC, "
				+ "'' AS MR_NO,'' AS PAT_NAME,'' AS EXE_NS,C.USER_NAME AS ORDER_DR "
				+ "FROM OPD_ORDER A,PHA_BASE B,SYS_OPERATOR C "
				+ "WHERE A.ADM_TYPE='E' "
				+ "AND A.CAT1_TYPE = 'PHA' "
				+ "AND (A.CTRLDRUGCLASS_CODE IS NOT NULL AND A.CTRLDRUGCLASS_CODE IN "
				+ "(SELECT CTRLDRUGCLASS_CODE FROM SYS_CTRLDRUGCLASS WHERE CTRL_FLG='Y')) "
				+ "AND A.ORDER_CODE=B.ORDER_CODE "
				+ "AND A.DR_CODE=C.USER_ID "
				+ "UNION ALL "
				// 病区给药
//				+ "SELECT A.ORDER_CODE,B.ORDER_DESC,B.SPECIFICATION,COALESCE(A.TOXIC_ID1,A.TOXIC_ID2,A.TOXIC_ID3) AS BAR_CODE, "
//				+ "G.NS_EXEC_DATE AS EXE_DATE,'G' AS TYPE,C.STATION_DESC AS ORG_CHN_DESC,A.MR_NO,D.PAT_NAME, "
//				+ "E.USER_NAME AS EXE_NS,F.USER_NAME AS ORDER_DR "
//				+ "FROM IND_CABDSPN A,ODI_DSPNM G,PHA_BASE B,SYS_STATION C,SYS_PATINFO D,SYS_OPERATOR E,SYS_OPERATOR F "
//				+ "WHERE A.CAT1_TYPE='PHA' "
//				+ "AND (A.CTRLDRUGCLASS_CODE IS NOT NULL AND A.CTRLDRUGCLASS_CODE IN  "
//				+ "(SELECT CTRLDRUGCLASS_CODE FROM SYS_CTRLDRUGCLASS WHERE CTRL_FLG='Y')) "
//				+ "AND A.CASE_NO=G.CASE_NO "
//				+ "AND A.ORDER_NO=G.ORDER_NO "
//				+ "AND A.ORDER_SEQ=G.ORDER_SEQ "
//				+ "AND A.START_DTTM=G.START_DTTM "
//				+ "AND G.NS_EXEC_CODE IS NOT NULL "
//				+ "AND A.ORDER_CODE=B.ORDER_CODE "
//				+ "AND A.STATION_CODE=C.STATION_CODE "
//				+ "AND A.MR_NO=D.MR_NO "
//				+ "AND G.NS_EXEC_CODE=E.USER_ID "
//				+ "AND A.VS_DR_CODE=F.USER_ID "
//				+ "UNION ALL "
				// 手术介入给药
//				+ "SELECT A.ORDER_CODE,B.ORDER_DESC,B.SPECIFICATION,A.BAR_CODE,A.OPT_DATE AS EXE_DATE,'G' AS TYPE, "
//				+ "C.DEPT_CHN_DESC AS ORG_CHN_DESC,A.MR_NO,D.PAT_NAME,E.USER_NAME AS EXE_NS,'' AS ORDER_DR "
//				+ "FROM SPC_INV_RECORD A,PHA_BASE B,SYS_DEPT C,SYS_PATINFO D,SYS_OPERATOR E "
//				+ "WHERE A.ORDER_CODE=B.ORDER_CODE "
//				+ "AND (B.CTRLDRUGCLASS_CODE IS NOT NULL AND B.CTRLDRUGCLASS_CODE IN "
//				+ "(SELECT CTRLDRUGCLASS_CODE FROM SYS_CTRLDRUGCLASS WHERE CTRL_FLG='Y')) "
//				+ "AND A.EXE_DEPT_CODE=C.DEPT_CODE "
//				+ "AND A.MR_NO=D.MR_NO "
//				+ "AND A.NS_CODE=E.USER_ID "
//				+ "UNION ALL "
				// 病区回收
				+ "SELECT A.ORDER_CODE,A.ORDER_DESC,A.SPECIFICATION,COALESCE(A.TOXIC_ID1,A.TOXIC_ID2,A.TOXIC_ID3) AS BAR_CODE, "
				+ "A.RECLAIM_DATE AS EXE_DATE,'H' AS TYPE,B.STATION_DESC AS ORG_CHN_DESC, "
				+ "'' AS MR_NO,'' AS PAT_NAME,'' AS EXE_NS,'' AS ORDER_DR "
				+ "FROM IND_CABDSPN A,SYS_STATION B "
				+ "WHERE A.CAT1_TYPE = 'PHA' "
				+ "AND (A.CTRLDRUGCLASS_CODE IS NOT NULL AND A.CTRLDRUGCLASS_CODE IN "
				+ "(SELECT CTRLDRUGCLASS_CODE FROM SYS_CTRLDRUGCLASS WHERE CTRL_FLG='Y')) "
				+ "AND A.RECLAIM_USER IS NOT NULL "
				+ "AND A.STATION_CODE=B.STATION_CODE "
				+ "UNION ALL "
				// 手术介入回收
				+ "SELECT A.ORDER_CODE,A.ORDER_DESC,B.SPECIFICATION,A.BAR_CODE,A.RECLAIM_DATE AS EXE_DATE,'E' AS TYPE, "
				+ "C.DEPT_CHN_DESC AS ORG_CHN_DESC,'' AS MR_NO,'' AS PAT_NAME,'' AS EXE_NS,'' AS ORDER_DR "
				+ "FROM SPC_INV_RECORD A,PHA_BASE B,SYS_DEPT C "
				+ "WHERE A.RECLAIM_USER IS NOT NULL "
				+ "AND A.ORDER_CODE=B.ORDER_CODE "
				+ "AND (B.CTRLDRUGCLASS_CODE IS NOT NULL AND B.CTRLDRUGCLASS_CODE IN "
				+ "(SELECT CTRLDRUGCLASS_CODE FROM SYS_CTRLDRUGCLASS WHERE CTRL_FLG='Y')) "
				+ "AND A.DEPT_CODE=C.DEPT_CODE "
				+ ") X "
				+ "WHERE 1=1 "
				+ con1
				+ con2
				+ con3
				+ "ORDER BY X.TYPE,X.ORDER_CODE,X.BAR_CODE,X.EXE_DATE";
		return new TParm(TJDODBTool.getInstance().select(sql));
	}

}
