Module.item=queryForAmount

//抓取药品开药单位、发药单位、库存单位转换算率
queryForAmount.Type=TSQL
queryForAmount.SQL=SELECT MEDI_QTY,MEDI_UNIT,STOCK_QTY,STOCK_UNIT,PURCH_QTY,PURCH_UNIT ,DOSAGE_QTY,DOSAGE_UNIT FROM PHA_TRANSUNIT WHERE ORDER_CODE=<ORDER_CODE>