   #
   # Title:¶©¹ºÖ÷µµ
   #
   # Description:¶©¹ºÖ÷µµ   
   #
   # Copyright: JavaHis (c) 2009
   #
   # @author zhangy 2009/05/04

Module.item=createPurOrderM;updatePurOrderM;deletePurOrderM;queryPurOrderM;queryUnDonePurOrder;updateFinalFlg;updateCheckFlg


//ÐÂ½¨¶©¹ºÖ÷µµ
createPurOrderM.Type=TSQL
createPurOrderM.SQL=INSERT INTO INV_PURORDERM( &
			PURORDER_NO , ORG_CODE , SUP_CODE, PURORDER_DATE , PURORDER_AMT ,&
			REN_CODE , DESCRIPTION , RES_DELIVERY_DATE, FINAL_FLG , FROM_TYPE ,&
			STATIO_NO , QUALITY_DEDUCT_AMT , FORFEIT_AMT, ACTUAL_AMT , &
			OPT_USER , OPT_DATE , OPT_TERM,CON_FLG,CON_ORG) &
	    	      VALUES( &
	    	   	<PURORDER_NO> ,  <ORG_CODE> , <SUP_CODE> , <PURORDER_DATE> , <PURORDER_AMT> , &
	    	   	<REN_CODE> ,  <DESCRIPTION> , <RES_DELIVERY_DATE> , <FINAL_FLG> , <FROM_TYPE> , &
	    	   	<STATIO_NO> ,  <QUALITY_DEDUCT_AMT> , <FORFEIT_AMT> , <ACTUAL_AMT> , &
	    	   	<OPT_USER> , <OPT_DATE> , <OPT_TERM>,<CON_FLG>,<CON_ORG> )
createPurOrderM.Debug=N


//¸üÐÂ¶©¹ºÖ÷µµ
updatePurOrderM.Type=TSQL
updatePurOrderM.SQL=UPDATE INV_PURORDERM SET &
			ORG_CODE=<ORG_CODE>, SUP_CODE=<SUP_CODE>, &
			PURORDER_DATE=<PURORDER_DATE>, PURORDER_AMT=<PURORDER_AMT>, REN_CODE=<REN_CODE>, &
			DESCRIPTION=<DESCRIPTION>, RES_DELIVERY_DATE=<RES_DELIVERY_DATE>, FINAL_FLG=<FINAL_FLG>, &
			FROM_TYPE=<FROM_TYPE>, STATIO_NO=<STATIO_NO>, QUALITY_DEDUCT_AMT=<QUALITY_DEDUCT_AMT>, &
			FORFEIT_AMT=<FORFEIT_AMT>, ACTUAL_AMT=<ACTUAL_AMT>, &
			OPT_USER=<OPT_USER>, OPT_DATE=<OPT_DATE>, OPT_TERM=<OPT_TERM>,CON_FLG=<CON_FLG>,CON_ORG=<CON_ORG> &
		    WHERE PURORDER_NO=<PURORDER_NO>
updatePurOrderM.Debug=N


//É¾³ý¶©¹ºÖ÷µµ
deletePurOrderM.Type=TSQL
deletePurOrderM.SQL=DELETE FROM INV_PURORDERM WHERE PURORDER_NO=<PURORDER_NO>
deletePurOrderM.Debug=N


//²éÑ¯¶©¹ºÖ÷µµ
queryPurOrderM.Type=TSQL
queryPurOrderM.SQL=SELECT PURORDER_NO , ORG_CODE , SUP_CODE, PURORDER_DATE , PURORDER_AMT , &
			  REN_CODE , DESCRIPTION , RES_DELIVERY_DATE, FINAL_FLG , FROM_TYPE ,&
			  STATIO_NO , QUALITY_DEDUCT_AMT , FORFEIT_AMT, ACTUAL_AMT,CON_ORG,CON_FLG &
		     FROM INV_PURORDERM
queryPurOrderM.ITEM=FROM_TYPE;FINAL_FLG;ORG_CODE;SUP_CODE;PURORDER_NO;START_DATE;CHECK_FLG
queryPurOrderM.FROM_TYPE=FROM_TYPE=<FROM_TYPE>
queryPurOrderM.FINAL_FLG=FINAL_FLG=<FINAL_FLG>
queryPurOrderM.ORG_CODE=ORG_CODE=<ORG_CODE>
queryPurOrderM.SUP_CODE=SUP_CODE=<SUP_CODE>
queryPurOrderM.PURORDER_NO=PURORDER_NO=<PURORDER_NO>
queryPurOrderM.CHECK_FLG=CHECK_FLG=<CHECK_FLG>
queryPurOrderM.START_DATE=PURORDER_DATE BETWEEN <START_DATE> AND <END_DATE>
queryPurOrderM.Debug=N



//²éÑ¯¶©¹º
queryUnDonePurOrder.Type=TSQL
queryUnDonePurOrder.SQL=SELECT 'N' AS SELECT_FLG, A.PURORDER_NO, B.PURORDER_DATE, C.INV_CHN_DESC, &
				  A.PURORDER_QTY, A.GIFT_QTY, A.BILL_UNIT, A.PURORDER_PRICE, &
				  A.STOCKIN_SUM_QTY, A.INV_CODE, C.DESCRIPTION, C.MAN_CODE, &
				  C.VALIDATE_FLG, C.EXPENSIVE_FLG, D.PURCH_QTY, D.STOCK_QTY, & 
				  B.SUP_CODE, B.STATIO_NO, C.STOCK_UNIT, A.SEQ_NO, D.DISPENSE_QTY, &
				  D.DISPENSE_UNIT, C.SEQMAN_FLG &
			     FROM INV_PURORDERD A, INV_PURORDERM B, INV_BASE C, INV_TRANSUNIT D &
			    WHERE A.PURORDER_NO = B.PURORDER_NO &
			      AND A.INV_CODE = C.INV_CODE &
			      AND A.INV_CODE = D.INV_CODE &
			      AND C.INV_CODE = D.INV_CODE &
			      AND A.IERMINATE_FLG = 'N' &
			      AND A.PURORDER_QTY > A.STOCKIN_SUM_QTY
queryUnDonePurOrder.ITEM=PURORDER_NO;SUP_CODE;INV_CODE
queryUnDonePurOrder.PURORDER_NO=A.PURORDER_NO=<PURORDER_NO>
queryUnDonePurOrder.SUP_CODE=B.SUP_CODE=<SUP_CODE>
queryUnDonePurOrder.INV_CODE=A.INV_CODE=<INV_CODE>
queryUnDonePurOrder.Debug=N


//¸üÐÂ¶©¹ºµ¥Ö÷µµ×´Ì¬
updateFinalFlg.Type=TSQL
updateFinalFlg.SQL=UPDATE INV_PURORDERM SET &
			  FINAL_FLG='Y', OPT_USER=<OPT_USER>, OPT_DATE=SYSDATE, OPT_TERM=<OPT_TERM> &
		    WHERE PURORDER_NO=<PURORDER_NO>
updateFinalFlg.Debug=N
//¸üÐÂ¶©¹ºµ¥Ö÷µµÉóºË×´Ì¬
updateCheckFlg.Type=TSQL
updateCheckFlg.SQL=UPDATE INV_PURORDERM SET &
			  CHECK_FLG=<CHECK_FLG>, OPT_USER=<OPT_USER>, OPT_DATE=SYSDATE, OPT_TERM=<OPT_TERM>, &
                          CHECK_USER=<OPT_USER>,CHECK_DATE=SYSDATE  &
		    WHERE PURORDER_NO=<PURORDER_NO>
updateCheckFlg.Debug=N















