package jdo.bil.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-09-23T15:36:24.650+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://bil.jdo/", name = "BILSPCINVWsTool")
@XmlSeeAlso({ObjectFactory.class})
public interface BILSPCINVWsTool {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "onFeeData", targetNamespace = "http://bil.jdo/", className = "jdo.bil.client.OnFeeData")
    @WebMethod
    @ResponseWrapper(localName = "onFeeDataResponse", targetNamespace = "http://bil.jdo/", className = "jdo.bil.client.OnFeeDataResponse")
    public java.lang.String onFeeData(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "onMrNo", targetNamespace = "http://bil.jdo/", className = "jdo.bil.client.OnMrNo")
    @WebMethod
    @ResponseWrapper(localName = "onMrNoResponse", targetNamespace = "http://bil.jdo/", className = "jdo.bil.client.OnMrNoResponse")
    public java.lang.String onMrNo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "insertIBSOrder", targetNamespace = "http://bil.jdo/", className = "jdo.bil.client.InsertIBSOrder")
    @WebMethod
    @ResponseWrapper(localName = "insertIBSOrderResponse", targetNamespace = "http://bil.jdo/", className = "jdo.bil.client.InsertIBSOrderResponse")
    public java.lang.String insertIBSOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "insertOpdOrder", targetNamespace = "http://bil.jdo/", className = "jdo.bil.client.InsertOpdOrder")
    @WebMethod
    @ResponseWrapper(localName = "insertOpdOrderResponse", targetNamespace = "http://bil.jdo/", className = "jdo.bil.client.InsertOpdOrderResponse")
    public java.lang.String insertOpdOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
