
package jdo.bil.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;

import com.dongyang.config.TConfig;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-09-23T15:36:24.617+08:00
 * Generated source version: 2.5.2
 * 
 */
public final class BILSPCINVWsTool_BILSPCINVWsToolImplPort_Client {

	public  static final QName SERVICE_NAME = new QName("http://bil.jdo/", "BILSPCINVWsToolImplService");

	public  BILSPCINVWsTool_BILSPCINVWsToolImplPort_Client() {
    }

    private static  TConfig getProp() {
        TConfig config = TConfig.getConfig("WEB-INF\\config\\system\\TConfig.x");
        return config;
	}

    public  static String getWebServicesIp(){
		 TConfig config = getProp() ;
		 String url = config.getString("", "WEB_SERVICES_IP");
		 return url;
	 }

    public  String insertIBSOrder(String inString1,String inString2,String inStringM){    	 
   	 String ip = getWebServicesIp();
    	 String url = "http://"+ip+"/services/bilService" ;
    	 JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean(); 
        factory.setAddress(url); 
        factory.setServiceClass(BILSPCINVWsTool.class); 
        //factory.getInInterceptors().add(new LoggingInInterceptor()); 
        BILSPCINVWsTool service = (BILSPCINVWsTool) factory.create();        
        String result = service.insertIBSOrder(inString1, inString2,inStringM);
        return result;
   }
	 
	 public  String onMrNo(String mrNo ,String admType){    	 
   	 String ip = getWebServicesIp();
    	 String url = "http://"+ip+"/services/bilService" ;
    	 JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean(); 
        factory.setAddress(url); 
        factory.setServiceClass(BILSPCINVWsTool.class); 
        //factory.getInInterceptors().add(new LoggingInInterceptor()); 
        BILSPCINVWsTool service = (BILSPCINVWsTool) factory.create();        
        String result = service.onMrNo(mrNo, admType);
        return result;
   }
	 
	 public String insertOpdOrder(String inString){
		 String ip = getWebServicesIp();
    	 String url = "http://"+ip+"/services/bilService" ;
    	 JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean(); 
        factory.setAddress(url); 
        factory.setServiceClass(BILSPCINVWsTool.class); 
        //factory.getInInterceptors().add(new LoggingInInterceptor()); 
        BILSPCINVWsTool service = (BILSPCINVWsTool) factory.create();        
        String result = service.insertOpdOrder(inString);
        return result;
	 }
	 public String onFeeData(String inString){
		 String ip = getWebServicesIp();
    	 String url = "http://"+ip+"/services/bilService" ;
    	 JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean(); 
        factory.setAddress(url); 
        factory.setServiceClass(BILSPCINVWsTool.class); 
        //factory.getInInterceptors().add(new LoggingInInterceptor()); 
        BILSPCINVWsTool service = (BILSPCINVWsTool) factory.create();        
        String result = service.onFeeData(inString);
        return result;
	 }
	  public static void main(String args[]) throws java.lang.Exception {

	   }



//    public static void main(String args[]) throws java.lang.Exception {
//        URL wsdlURL = BILSPCINVWsToolImplService.WSDL_LOCATION;
//        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
//            File wsdlFile = new File(args[0]);
//            try {
//                if (wsdlFile.exists()) {
//                    wsdlURL = wsdlFile.toURI().toURL();
//                } else {
//                    wsdlURL = new URL(args[0]);
//                }
//            } catch (MalformedURLException e) {
//                e.printStackTrace();
//            }
//        }
//      
//        BILSPCINVWsToolImplService ss = new BILSPCINVWsToolImplService(wsdlURL, SERVICE_NAME);
//        BILSPCINVWsTool port = ss.getBILSPCINVWsToolImplPort();  
//        
//        {
//        System.out.println("Invoking onFeeData...");
//        java.lang.String _onFeeData_arg0 = "";
//        java.lang.String _onFeeData__return = port.onFeeData(_onFeeData_arg0);
//        System.out.println("onFeeData.result=" + _onFeeData__return);
//
//
//        }
//        {
//        System.out.println("Invoking onMrNo...");
//        java.lang.String _onMrNo_arg0 = "";
//        java.lang.String _onMrNo_arg1 = "";
//        java.lang.String _onMrNo__return = port.onMrNo(_onMrNo_arg0, _onMrNo_arg1);
//        System.out.println("onMrNo.result=" + _onMrNo__return);
//
//
//        }
//        {
//        System.out.println("Invoking insertIBSOrder...");
//        java.lang.String _insertIBSOrder_arg0 = "";
//        java.lang.String _insertIBSOrder_arg1 = "";
//        java.lang.String _insertIBSOrder_arg2 = "";
//        java.lang.String _insertIBSOrder__return = port.insertIBSOrder(_insertIBSOrder_arg0, _insertIBSOrder_arg1, _insertIBSOrder_arg2);
//        System.out.println("insertIBSOrder.result=" + _insertIBSOrder__return);
//
//
//        }
//        {
//        System.out.println("Invoking insertOpdOrder...");
//        java.lang.String _insertOpdOrder_arg0 = "";
//        java.lang.String _insertOpdOrder__return = port.insertOpdOrder(_insertOpdOrder_arg0);
//        System.out.println("insertOpdOrder.result=" + _insertOpdOrder__return);
//
//
//        }
//
//        System.exit(0);
//    }

}
