
package jdo.bil.client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-09-23T15:36:24.656+08:00
 * Generated source version: 2.5.2
 * 
 */
 
public class BILSPCINVWsTool_BILSPCINVWsToolImplPort_Server{

    protected BILSPCINVWsTool_BILSPCINVWsToolImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new BILSPCINVWsToolImpl();
        String address = "http://127.0.0.1:8080/web1/services/bilService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new BILSPCINVWsTool_BILSPCINVWsToolImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
