package jdo.pha.inf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-01-08T14:48:43.009+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://inf.pha.jdo/", name = "PHADosageWs")
@XmlSeeAlso({ObjectFactory.class})
public interface PHADosageWs {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOpdOrder", targetNamespace = "http://inf.pha.jdo/", className = "jdo.pha.inf.client.GetOpdOrder")
    @WebMethod
    @ResponseWrapper(localName = "getOpdOrderResponse", targetNamespace = "http://inf.pha.jdo/", className = "jdo.pha.inf.client.GetOpdOrderResponse")
    public jdo.pha.inf.client.SpcOpdOrderDtos getOpdOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
