
package action.spc.opdOrderClient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-01-22T18:53:49.718+08:00
 * Generated source version: 2.5.2
 * 
 */
public final class SPCOpdOrderSynchWsTool_SPCOpdOrderSynchWsToolImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://spc.jdo/", "SPCOpdOrderSynchWsToolImplService");

    private SPCOpdOrderSynchWsTool_SPCOpdOrderSynchWsToolImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SPCOpdOrderSynchWsToolImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SPCOpdOrderSynchWsToolImplService ss = new SPCOpdOrderSynchWsToolImplService(wsdlURL, SERVICE_NAME);
        SPCOpdOrderSynchWsTool port = ss.getSPCOpdOrderSynchWsToolImplPort();  
        
        {
        System.out.println("Invoking updateOpdOrder...");
        java.lang.String _updateOpdOrder_arg0 = "";
        java.lang.String _updateOpdOrder_arg1 = "";
        java.lang.String _updateOpdOrder_arg2 = "";
        java.lang.String _updateOpdOrder_arg3 = "";
        java.lang.String _updateOpdOrder_arg4 = "";
        java.lang.String _updateOpdOrder_arg5 = "";
        java.lang.String _updateOpdOrder_arg6 = "";
        java.lang.String _updateOpdOrder_arg7 = "";
        java.lang.String _updateOpdOrder_arg8 = "";
        java.lang.String _updateOpdOrder_arg9 = "";
        java.lang.String _updateOpdOrder_arg10 = "";
        boolean _updateOpdOrder__return = port.updateOpdOrder(_updateOpdOrder_arg0, _updateOpdOrder_arg1, _updateOpdOrder_arg2, _updateOpdOrder_arg3, _updateOpdOrder_arg4, _updateOpdOrder_arg5, _updateOpdOrder_arg6, _updateOpdOrder_arg7, _updateOpdOrder_arg8, _updateOpdOrder_arg9, _updateOpdOrder_arg10);
        System.out.println("updateOpdOrder.result=" + _updateOpdOrder__return);


        }

        System.exit(0);
    }

}
