package action.spc.opdOrderClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-01-22T18:53:49.765+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://spc.jdo/", name = "SPCOpdOrderSynchWsTool")
@XmlSeeAlso({ObjectFactory.class})
public interface SPCOpdOrderSynchWsTool {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateOpdOrder", targetNamespace = "http://spc.jdo/", className = "action.spc.opdOrderClient.UpdateOpdOrder")
    @WebMethod
    @ResponseWrapper(localName = "updateOpdOrderResponse", targetNamespace = "http://spc.jdo/", className = "action.spc.opdOrderClient.UpdateOpdOrderResponse")
    public boolean updateOpdOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        java.lang.String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        java.lang.String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        java.lang.String arg10
    );
}
