package action.spc.opdOrderClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-01-22T18:53:49.765+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "SPCOpdOrderSynchWsToolImplService", 
                  wsdlLocation = "http://127.0.0.1:8080/webgy/services/SPCOpdOrderSynchWs?wsdl",
                  targetNamespace = "http://spc.jdo/") 
                  
public class SPCOpdOrderSynchWsToolImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://spc.jdo/", "SPCOpdOrderSynchWsToolImplService");
    public final static QName SPCOpdOrderSynchWsToolImplPort = new QName("http://spc.jdo/", "SPCOpdOrderSynchWsToolImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/webgy/services/SPCOpdOrderSynchWs?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SPCOpdOrderSynchWsToolImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/webgy/services/SPCOpdOrderSynchWs?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SPCOpdOrderSynchWsToolImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SPCOpdOrderSynchWsToolImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SPCOpdOrderSynchWsToolImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SPCOpdOrderSynchWsToolImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SPCOpdOrderSynchWsToolImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SPCOpdOrderSynchWsToolImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns SPCOpdOrderSynchWsTool
     */
    @WebEndpoint(name = "SPCOpdOrderSynchWsToolImplPort")
    public SPCOpdOrderSynchWsTool getSPCOpdOrderSynchWsToolImplPort() {
        return super.getPort(SPCOpdOrderSynchWsToolImplPort, SPCOpdOrderSynchWsTool.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SPCOpdOrderSynchWsTool
     */
    @WebEndpoint(name = "SPCOpdOrderSynchWsToolImplPort")
    public SPCOpdOrderSynchWsTool getSPCOpdOrderSynchWsToolImplPort(WebServiceFeature... features) {
        return super.getPort(SPCOpdOrderSynchWsToolImplPort, SPCOpdOrderSynchWsTool.class, features);
    }

}
