package action.odi.spcUddClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-06-03T17:28:31.935+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://uddinfo.spc.jdo/", name = "SpcUddService")
@XmlSeeAlso({ObjectFactory.class})
public interface SpcUddService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOdiDspndInfo", targetNamespace = "http://uddinfo.spc.jdo/", className = "action.odi.spcUddClient.GetOdiDspndInfo")
    @WebMethod
    @ResponseWrapper(localName = "getOdiDspndInfoResponse", targetNamespace = "http://uddinfo.spc.jdo/", className = "action.odi.spcUddClient.GetOdiDspndInfoResponse")
    public java.util.List<action.odi.spcUddClient.OdiDspndPkVo> getOdiDspndInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
