
package action.odi.spcUddClient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;
import com.dongyang.config.TConfig;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-06-03T17:28:31.891+08:00
 * Generated source version: 2.5.2
 * 
 */
public final class SpcUddService_SpcUddServiceImplPort_Client {

  

    private static  TConfig getProp() {
        TConfig config = TConfig.getConfig("WEB-INF\\config\\system\\TConfig.x");
        return config;
    }
 
     public  static String getWebServicesIp(){
         TConfig config = getProp() ;
         String url = config.getString("", "WEB_SERVICES_IP");
         return url;
     }
    public static List<OdiDspndPkVo> getOdiDspndInfo(String caseNo,String barCode){
//        System.out.println("---------------getOdiDspndInfo----------------");
        String ip = getWebServicesIp();
        String url = "http://" + ip + "/services/spcUddServiceImpl";
//        String url = "http://172.20.116.105:8080/webgy/services/spcUddServiceImpl";
        // http://172.20.116.105:8080/webgy/services/
//        System.out.println("00000000000000000url:"+url);
        JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean(); 
        factory.setAddress(url);
        factory.setServiceClass(SpcUddService.class); 
        SpcUddService port = (SpcUddService) factory.create();        
        List<OdiDspndPkVo> result = port.getOdiDspndInfo(caseNo,barCode);
        return result ;
    }
    
    private static final QName SERVICE_NAME = new QName("http://uddinfo.spc.jdo/", "SpcUddServiceImplService");

    private SpcUddService_SpcUddServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SpcUddServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SpcUddServiceImplService ss = new SpcUddServiceImplService(wsdlURL, SERVICE_NAME);
        SpcUddService port = ss.getSpcUddServiceImplPort();  
        
        {
        System.out.println("Invoking getOdiDspndInfo...");
        java.lang.String _getOdiDspndInfo_arg0 = "";
        java.lang.String _getOdiDspndInfo_arg1 = "";
        java.util.List<action.odi.spcUddClient.OdiDspndPkVo> _getOdiDspndInfo__return = port.getOdiDspndInfo(_getOdiDspndInfo_arg0, _getOdiDspndInfo_arg1);
        System.out.println("getOdiDspndInfo.result=" + _getOdiDspndInfo__return);


        }

        System.exit(0);
    }

}
