package action.odi.spcUddClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-06-03T17:28:31.942+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "SpcUddServiceImplService", 
                  wsdlLocation = "http://172.20.116.105:8080/webgy/services/spcUddServiceImpl?wsdl",
                  targetNamespace = "http://uddinfo.spc.jdo/") 
public class SpcUddServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://uddinfo.spc.jdo/", "SpcUddServiceImplService");
    public final static QName SpcUddServiceImplPort = new QName("http://uddinfo.spc.jdo/", "SpcUddServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.20.116.105:8080/webgy/services/spcUddServiceImpl?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SpcUddServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.20.116.105:8080/webgy/services/spcUddServiceImpl?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SpcUddServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SpcUddServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpcUddServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SpcUddServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SpcUddServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SpcUddServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns SpcUddService
     */
    @WebEndpoint(name = "SpcUddServiceImplPort")
    public SpcUddService getSpcUddServiceImplPort() {
        return super.getPort(SpcUddServiceImplPort, SpcUddService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpcUddService
     */
    @WebEndpoint(name = "SpcUddServiceImplPort")
    public SpcUddService getSpcUddServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SpcUddServiceImplPort, SpcUddService.class, features);
    }

}
