
package com.javahis.ui.odi.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-01-10T16:52:11.469+08:00
 * Generated source version: 2.5.2
 * 
 */
public final class SpcOdiService_SpcOdiServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.spc.action/", "SpcOdiServiceImplService");

    private SpcOdiService_SpcOdiServiceImplPort_Client() {
    }
    
    public static String sendElectronicTag(String caseNo,String patName,String  stationDesc,String bedNoDesc){
    	System.out.println("caseNo---:"+caseNo);
        System.out.println("patName---:"+patName);
        System.out.println("stationDesc---:"+stationDesc);
        System.out.println("bedNoDesc---:"+bedNoDesc);
    	URL wsdlURL = SpcOdiServiceImplService.WSDL_LOCATION;
    	SpcOdiServiceImplService ss = new SpcOdiServiceImplService(wsdlURL, SERVICE_NAME);
        SpcOdiService port = ss.getSpcOdiServiceImplPort();  
        
        String result = port.sendElectronicTag(caseNo,patName,stationDesc,bedNoDesc);
        return result ;
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SpcOdiServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SpcOdiServiceImplService ss = new SpcOdiServiceImplService(wsdlURL, SERVICE_NAME);
        SpcOdiService port = ss.getSpcOdiServiceImplPort();  
        
        {
        System.out.println("Invoking sendElectronicTag...");
        java.lang.String _sendElectronicTag_arg0 = "121022000192";
        java.lang.String _sendElectronicTag_arg1 = "´Þ¸¨Ìì";
        java.lang.String _sendElectronicTag_arg2 = "0720";
        java.lang.String _sendElectronicTag_arg3 = "7²¡Çø";
        java.lang.String _sendElectronicTag__return = port.sendElectronicTag(_sendElectronicTag_arg0, _sendElectronicTag_arg1, _sendElectronicTag_arg2, _sendElectronicTag_arg3);
        System.out.println("sendElectronicTag.result=" + _sendElectronicTag__return);


        }
         

        System.exit(0);
    }

}
