package jdo.sys.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-07-03T11:19:56.910+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://ws.sys.jdo/", name = "IDictionaryService")
@XmlSeeAlso({ObjectFactory.class})
public interface IDictionaryService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getModifyInf", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetModifyInf")
    @WebMethod
    @ResponseWrapper(localName = "getModifyInfResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetModifyInfResponse")
    public java.util.List<java.lang.String> getModifyInf(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRouteInf", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetRouteInf")
    @WebMethod
    @ResponseWrapper(localName = "getRouteInfResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetRouteInfResponse")
    public java.util.List<java.lang.String> getRouteInf(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPhaOrderPY1", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPhaOrderPY1")
    @WebMethod
    @ResponseWrapper(localName = "getPhaOrderPY1Response", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPhaOrderPY1Response")
    public java.util.List<java.lang.String> getPhaOrderPY1(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSysOperationICD", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetSysOperationICD")
    @WebMethod
    @ResponseWrapper(localName = "getSysOperationICDResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetSysOperationICDResponse")
    public java.util.List<java.lang.String> getSysOperationICD(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getClinicArea", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetClinicArea")
    @WebMethod
    @ResponseWrapper(localName = "getClinicAreaResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetClinicAreaResponse")
    public java.util.List<java.lang.String> getClinicArea(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAdmType", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetAdmType")
    @WebMethod
    @ResponseWrapper(localName = "getAdmTypeResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetAdmTypeResponse")
    public java.util.List<java.lang.String> getAdmType(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDiagnosisInf", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetDiagnosisInf")
    @WebMethod
    @ResponseWrapper(localName = "getDiagnosisInfResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetDiagnosisInfResponse")
    public java.util.List<java.lang.String> getDiagnosisInf(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOperatorInf", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetOperatorInf")
    @WebMethod
    @ResponseWrapper(localName = "getOperatorInfResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetOperatorInfResponse")
    public java.util.List<java.lang.String> getOperatorInf(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "regAppt", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.RegAppt")
    @WebMethod
    @ResponseWrapper(localName = "regApptResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.RegApptResponse")
    public java.lang.String regAppt(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        java.lang.String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        java.lang.String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        java.lang.String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        java.lang.String arg11
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRegistTableInf", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetRegistTableInf")
    @WebMethod
    @ResponseWrapper(localName = "getRegistTableInfResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetRegistTableInfResponse")
    public java.util.List<java.lang.String> getRegistTableInf(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDeptInf", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetDeptInf")
    @WebMethod
    @ResponseWrapper(localName = "getDeptInfResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetDeptInfResponse")
    public java.util.List<java.lang.String> getDeptInf(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "readOpdOrderPS", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.ReadOpdOrderPS")
    @WebMethod
    @ResponseWrapper(localName = "readOpdOrderPSResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.ReadOpdOrderPSResponse")
    public java.util.List<java.lang.String> readOpdOrderPS(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getClinicRoom", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetClinicRoom")
    @WebMethod
    @ResponseWrapper(localName = "getClinicRoomResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetClinicRoomResponse")
    public java.util.List<java.lang.String> getClinicRoom(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getIndMateriallocOrder", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetIndMateriallocOrder")
    @WebMethod
    @ResponseWrapper(localName = "getIndMateriallocOrderResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetIndMateriallocOrderResponse")
    public java.util.List<java.lang.String> getIndMateriallocOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getODIPhaOrderInfoItem", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetODIPhaOrderInfoItem")
    @WebMethod
    @ResponseWrapper(localName = "getODIPhaOrderInfoItemResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetODIPhaOrderInfoItemResponse")
    public java.util.List<java.lang.String> getODIPhaOrderInfoItem(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPhaOrder", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPhaOrder")
    @WebMethod
    @ResponseWrapper(localName = "getPhaOrderResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPhaOrderResponse")
    public java.util.List<java.lang.String> getPhaOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCtzInf", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetCtzInf")
    @WebMethod
    @ResponseWrapper(localName = "getCtzInfResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetCtzInfResponse")
    public java.util.List<java.lang.String> getCtzInf(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getShareTable", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetShareTable")
    @WebMethod
    @ResponseWrapper(localName = "getShareTableResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetShareTableResponse")
    public java.util.List<java.lang.String> getShareTable();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDeptInfCode", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetDeptInfCode")
    @WebMethod
    @ResponseWrapper(localName = "getDeptInfCodeResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetDeptInfCodeResponse")
    public java.util.List<java.lang.String> getDeptInfCode(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPhaClassify", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPhaClassify")
    @WebMethod
    @ResponseWrapper(localName = "getPhaClassifyResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPhaClassifyResponse")
    public java.util.List<java.lang.String> getPhaClassify(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "modifyPassword", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.ModifyPassword")
    @WebMethod
    @ResponseWrapper(localName = "modifyPasswordResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.ModifyPasswordResponse")
    public java.lang.String modifyPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDeptInfSY", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetDeptInfSY")
    @WebMethod
    @ResponseWrapper(localName = "getDeptInfSYResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetDeptInfSYResponse")
    public java.util.List<java.lang.String> getDeptInfSY(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPhaEsyOrder", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPhaEsyOrder")
    @WebMethod
    @ResponseWrapper(localName = "getPhaEsyOrderResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPhaEsyOrderResponse")
    public java.util.List<java.lang.String> getPhaEsyOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPatForSID", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPatForSID")
    @WebMethod
    @ResponseWrapper(localName = "getPatForSIDResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPatForSIDResponse")
    public java.util.List<java.lang.String> getPatForSID(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteInf", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.DeleteInf")
    @WebMethod
    @ResponseWrapper(localName = "deleteInfResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.DeleteInfResponse")
    public java.lang.String deleteInf(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPhaFreqInf", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPhaFreqInf")
    @WebMethod
    @ResponseWrapper(localName = "getPhaFreqInfResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPhaFreqInfResponse")
    public java.util.List<java.lang.String> getPhaFreqInf(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPatByMrNo", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPatByMrNo")
    @WebMethod
    @ResponseWrapper(localName = "getPatByMrNoResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPatByMrNoResponse")
    public java.util.List<java.lang.String> getPatByMrNo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPatInfAndOrder", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPatInfAndOrder")
    @WebMethod
    @ResponseWrapper(localName = "getPatInfAndOrderResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPatInfAndOrderResponse")
    public java.util.List<java.lang.String> getPatInfAndOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getStation", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetStation")
    @WebMethod
    @ResponseWrapper(localName = "getStationResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetStationResponse")
    public java.util.List<java.lang.String> getStation(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getReulInf", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetReulInf")
    @WebMethod
    @ResponseWrapper(localName = "getReulInfResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetReulInfResponse")
    public java.util.List<java.lang.String> getReulInf(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "confirmedInf", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.ConfirmedInf")
    @WebMethod
    @ResponseWrapper(localName = "confirmedInfResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.ConfirmedInfResponse")
    public java.lang.String confirmedInf(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSexInf", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetSexInf")
    @WebMethod
    @ResponseWrapper(localName = "getSexInfResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetSexInfResponse")
    public java.util.List<java.lang.String> getSexInf(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getIndMaterialloc", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetIndMaterialloc")
    @WebMethod
    @ResponseWrapper(localName = "getIndMateriallocResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetIndMateriallocResponse")
    public java.util.List<java.lang.String> getIndMaterialloc(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getModifyTable", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetModifyTable")
    @WebMethod
    @ResponseWrapper(localName = "getModifyTableResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetModifyTableResponse")
    public java.util.List<java.lang.String> getModifyTable(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOrderSY", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetOrderSY")
    @WebMethod
    @ResponseWrapper(localName = "getOrderSYResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetOrderSYResponse")
    public java.util.List<java.lang.String> getOrderSY(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registTable", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.RegistTable")
    @WebMethod
    @ResponseWrapper(localName = "registTableResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.RegistTableResponse")
    public java.lang.String registTable(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOperatorInfSY", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetOperatorInfSY")
    @WebMethod
    @ResponseWrapper(localName = "getOperatorInfSYResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetOperatorInfSYResponse")
    public java.util.List<java.lang.String> getOperatorInfSY(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRegistStatus", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetRegistStatus")
    @WebMethod
    @ResponseWrapper(localName = "getRegistStatusResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetRegistStatusResponse")
    public java.lang.String getRegistStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getODIPhaOrderInfo", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetODIPhaOrderInfo")
    @WebMethod
    @ResponseWrapper(localName = "getODIPhaOrderInfoResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetODIPhaOrderInfoResponse")
    public java.util.List<java.lang.String> getODIPhaOrderInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSysFeeHistory", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetSysFeeHistory")
    @WebMethod
    @ResponseWrapper(localName = "getSysFeeHistoryResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetSysFeeHistoryResponse")
    public java.util.List<java.lang.String> getSysFeeHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRegionJD", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetRegionJD")
    @WebMethod
    @ResponseWrapper(localName = "getRegionJDResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetRegionJDResponse")
    public java.util.List<java.lang.String> getRegionJD(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSysFee", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetSysFee")
    @WebMethod
    @ResponseWrapper(localName = "getSysFeeResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetSysFeeResponse")
    public java.util.List<java.lang.String> getSysFee(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getData", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetData")
    @WebMethod
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetDataResponse")
    public java.util.List<java.lang.String> getData(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLisOrder", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetLisOrder")
    @WebMethod
    @ResponseWrapper(localName = "getLisOrderResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetLisOrderResponse")
    public java.util.List<java.lang.String> getLisOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRegWorkList", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetRegWorkList")
    @WebMethod
    @ResponseWrapper(localName = "getRegWorkListResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetRegWorkListResponse")
    public java.util.List<java.lang.String> getRegWorkList(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRegSchDay", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetRegSchDay")
    @WebMethod
    @ResponseWrapper(localName = "getRegSchDayResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetRegSchDayResponse")
    public java.util.List<java.lang.String> getRegSchDay(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDictionary", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetDictionary")
    @WebMethod
    @ResponseWrapper(localName = "getDictionaryResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetDictionaryResponse")
    public java.lang.String getDictionary(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPhaFreqInfSY", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPhaFreqInfSY")
    @WebMethod
    @ResponseWrapper(localName = "getPhaFreqInfSYResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPhaFreqInfSYResponse")
    public java.util.List<java.lang.String> getPhaFreqInfSY(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSessionInf", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetSessionInf")
    @WebMethod
    @ResponseWrapper(localName = "getSessionInfResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetSessionInfResponse")
    public java.util.List<java.lang.String> getSessionInf(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "regUnAppt", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.RegUnAppt")
    @WebMethod
    @ResponseWrapper(localName = "regUnApptResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.RegUnApptResponse")
    public java.lang.String regUnAppt(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "savePat", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.SavePat")
    @WebMethod
    @ResponseWrapper(localName = "savePatResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.SavePatResponse")
    public java.lang.String savePat(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getHisCancelOrder", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetHisCancelOrder")
    @WebMethod
    @ResponseWrapper(localName = "getHisCancelOrderResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetHisCancelOrderResponse")
    public java.util.List<java.lang.String> getHisCancelOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDeptClassRule", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetDeptClassRule")
    @WebMethod
    @ResponseWrapper(localName = "getDeptClassRuleResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetDeptClassRuleResponse")
    public java.util.List<java.lang.String> getDeptClassRule(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPatAppRegInfo", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPatAppRegInfo")
    @WebMethod
    @ResponseWrapper(localName = "getPatAppRegInfoResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPatAppRegInfoResponse")
    public java.util.List<java.lang.String> getPatAppRegInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "regist", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.Regist")
    @WebMethod
    @ResponseWrapper(localName = "registResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.RegistResponse")
    public java.lang.String regist(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPhaInf", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPhaInf")
    @WebMethod
    @ResponseWrapper(localName = "getPhaInfResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetPhaInfResponse")
    public java.util.List<java.lang.String> getPhaInf(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "fetchInf", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.FetchInf")
    @WebMethod
    @ResponseWrapper(localName = "fetchInfResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.FetchInfResponse")
    public java.lang.String fetchInf(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetVersion")
    @WebMethod
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://ws.sys.jdo/", className = "jdo.sys.client.GetVersionResponse")
    public java.lang.String getVersion();
}
