package com.capinfo.dataswap.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2014-11-19T14:03:54.004+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://webservice.dataswap.capinfo.com/", name = "DataSwapInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface DataSwapInterface {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "systemState", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.SystemState")
    @WebMethod
    @ResponseWrapper(localName = "systemStateResponse", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.SystemStateResponse")
    public java.lang.Integer systemState();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "loadBehavior", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.LoadBehavior")
    @WebMethod
    @ResponseWrapper(localName = "loadBehaviorResponse", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.LoadBehaviorResponse")
    public java.lang.Boolean loadBehavior(
        @WebParam(name = "mrNo", targetNamespace = "")
        java.lang.String mrNo,
        @WebParam(name = "jsonObject", targetNamespace = "")
        java.lang.String jsonObject
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateMemberByMrNo", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.UpdateMemberByMrNo")
    @WebMethod
    @ResponseWrapper(localName = "updateMemberByMrNoResponse", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.UpdateMemberByMrNoResponse")
    public java.lang.Boolean updateMemberByMrNo(
        @WebParam(name = "mrNo", targetNamespace = "")
        java.lang.String mrNo,
        @WebParam(name = "jsonObject", targetNamespace = "")
        java.lang.String jsonObject
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addOrderInfo", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.AddOrderInfo")
    @WebMethod
    @ResponseWrapper(localName = "addOrderInfoResponse", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.AddOrderInfoResponse")
    public java.lang.Boolean addOrderInfo(
        @WebParam(name = "mrNo", targetNamespace = "")
        java.lang.String mrNo,
        @WebParam(name = "date", targetNamespace = "")
        java.lang.String date,
        @WebParam(name = "timeInteval", targetNamespace = "")
        java.lang.String timeInteval,
        @WebParam(name = "dept", targetNamespace = "")
        java.lang.String dept,
        @WebParam(name = "queg", targetNamespace = "")
        java.lang.String queg,
        @WebParam(name = "doc", targetNamespace = "")
        java.lang.String doc
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateOrder", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.UpdateOrder")
    @WebMethod
    @ResponseWrapper(localName = "updateOrderResponse", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.UpdateOrderResponse")
    public java.lang.Boolean updateOrder(
        @WebParam(name = "beginDate", targetNamespace = "")
        java.lang.String beginDate,
        @WebParam(name = "endDate", targetNamespace = "")
        java.lang.String endDate,
        @WebParam(name = "timePeriod", targetNamespace = "")
        java.lang.String timePeriod,
        @WebParam(name = "deptCode", targetNamespace = "")
        java.lang.String deptCode,
        @WebParam(name = "quegCode", targetNamespace = "")
        java.lang.String quegCode,
        @WebParam(name = "drCode", targetNamespace = "")
        java.lang.String drCode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "orderInfo", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.OrderInfo")
    @WebMethod
    @ResponseWrapper(localName = "orderInfoResponse", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.OrderInfoResponse")
    public java.lang.String orderInfo(
        @WebParam(name = "mrNo", targetNamespace = "")
        java.lang.String mrNo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "orderCount", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.OrderCount")
    @WebMethod
    @ResponseWrapper(localName = "orderCountResponse", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.OrderCountResponse")
    public java.lang.Boolean orderCount(
        @WebParam(name = "date", targetNamespace = "")
        java.lang.String date,
        @WebParam(name = "deptCode", targetNamespace = "")
        java.lang.String deptCode,
        @WebParam(name = "quegCode", targetNamespace = "")
        java.lang.String quegCode,
        @WebParam(name = "docCode", targetNamespace = "")
        java.lang.String docCode,
        @WebParam(name = "count", targetNamespace = "")
        java.lang.Integer count
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cancelUpdateOrder", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.CancelUpdateOrder")
    @WebMethod
    @ResponseWrapper(localName = "cancelUpdateOrderResponse", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.CancelUpdateOrderResponse")
    public java.lang.Boolean cancelUpdateOrder(
        @WebParam(name = "beginDate", targetNamespace = "")
        java.lang.String beginDate,
        @WebParam(name = "endDate", targetNamespace = "")
        java.lang.String endDate,
        @WebParam(name = "timePeriod", targetNamespace = "")
        java.lang.String timePeriod,
        @WebParam(name = "deptCode", targetNamespace = "")
        java.lang.String deptCode,
        @WebParam(name = "quegCode", targetNamespace = "")
        java.lang.String quegCode,
        @WebParam(name = "drCode", targetNamespace = "")
        java.lang.String drCode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "delOrder", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.DelOrder")
    @WebMethod
    @ResponseWrapper(localName = "delOrderResponse", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.DelOrderResponse")
    public java.lang.Boolean delOrder(
        @WebParam(name = "orderJson", targetNamespace = "")
        java.lang.String orderJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findMember", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.FindMember")
    @WebMethod
    @ResponseWrapper(localName = "findMemberResponse", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.FindMemberResponse")
    public java.lang.String findMember(
        @WebParam(name = "orderNum", targetNamespace = "")
        java.lang.String orderNum
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cancleOrderInfo", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.CancleOrderInfo")
    @WebMethod
    @ResponseWrapper(localName = "cancleOrderInfoResponse", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.CancleOrderInfoResponse")
    public java.lang.Boolean cancleOrderInfo(
        @WebParam(name = "mrNo", targetNamespace = "")
        java.lang.String mrNo,
        @WebParam(name = "date", targetNamespace = "")
        java.lang.String date,
        @WebParam(name = "timeInteval", targetNamespace = "")
        java.lang.String timeInteval,
        @WebParam(name = "dept", targetNamespace = "")
        java.lang.String dept,
        @WebParam(name = "queg", targetNamespace = "")
        java.lang.String queg,
        @WebParam(name = "doc", targetNamespace = "")
        java.lang.String doc
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateMember", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.UpdateMember")
    @WebMethod
    @ResponseWrapper(localName = "updateMemberResponse", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.UpdateMemberResponse")
    public java.lang.Boolean updateMember(
        @WebParam(name = "orderNum", targetNamespace = "")
        java.lang.String orderNum,
        @WebParam(name = "jsonObject", targetNamespace = "")
        java.lang.String jsonObject
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addOrder", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.AddOrder")
    @WebMethod
    @ResponseWrapper(localName = "addOrderResponse", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.AddOrderResponse")
    public java.lang.Boolean addOrder(
        @WebParam(name = "orderJson", targetNamespace = "")
        java.lang.String orderJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createMember", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.CreateMember")
    @WebMethod
    @ResponseWrapper(localName = "createMemberResponse", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.CreateMemberResponse")
    public java.lang.Boolean createMember(
        @WebParam(name = "jsonObject", targetNamespace = "")
        java.lang.String jsonObject
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateCode", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.UpdateCode")
    @WebMethod
    @ResponseWrapper(localName = "updateCodeResponse", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.UpdateCodeResponse")
    public java.lang.Boolean updateCode();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOrder", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.GetOrder")
    @WebMethod
    @ResponseWrapper(localName = "getOrderResponse", targetNamespace = "http://webservice.dataswap.capinfo.com/", className = "com.capinfo.dataswap.webservice.GetOrderResponse")
    public java.lang.String getOrder(
        @WebParam(name = "date", targetNamespace = "")
        java.lang.String date,
        @WebParam(name = "timeInteval", targetNamespace = "")
        java.lang.String timeInteval,
        @WebParam(name = "dept", targetNamespace = "")
        java.lang.String dept,
        @WebParam(name = "queg", targetNamespace = "")
        java.lang.String queg,
        @WebParam(name = "doc", targetNamespace = "")
        java.lang.String doc
    );
}
