package com.capinfo.dataswap.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2014-07-11T16:30:53.373+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "DataSwapWebServiceService", 
                  wsdlLocation = "http://172.20.0.249:8080/crm/CXFService/dataswap?wsdl",
                  targetNamespace = "http://impl.webservice.dataswap.capinfo.com/") 
public class DataSwapWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.dataswap.capinfo.com/", "DataSwapWebServiceService");
    public final static QName DataSwapWebServicePort = new QName("http://impl.webservice.dataswap.capinfo.com/", "DataSwapWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.20.0.249:8080/crm/CXFService/dataswap?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DataSwapWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.32.33:8080/crm/CXFService/dataswap?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DataSwapWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DataSwapWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataSwapWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DataSwapWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DataSwapWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DataSwapWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns DataSwapInterface
     */
    @WebEndpoint(name = "DataSwapWebServicePort")
    public DataSwapInterface getDataSwapWebServicePort() {
        return super.getPort(DataSwapWebServicePort, DataSwapInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataSwapInterface
     */
    @WebEndpoint(name = "DataSwapWebServicePort")
    public DataSwapInterface getDataSwapWebServicePort(WebServiceFeature... features) {
        return super.getPort(DataSwapWebServicePort, DataSwapInterface.class, features);
    }

}
