
package com.capinfo.dataswap.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2014-10-29T17:06:20.618+08:00
 * Generated source version: 2.5.2
 * 
 */
public final class DataSwapInterface_DataSwapWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webservice.dataswap.capinfo.com/", "DataSwapWebServiceService");

    private DataSwapInterface_DataSwapWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DataSwapWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DataSwapWebServiceService ss = new DataSwapWebServiceService(wsdlURL, SERVICE_NAME);
        DataSwapInterface port = ss.getDataSwapWebServicePort();  
        
        {
        System.out.println("Invoking systemState...");
        java.lang.Integer _systemState__return = port.systemState();
        System.out.println("systemState.result=" + _systemState__return);


        }
        {
        System.out.println("Invoking loadBehavior...");
        java.lang.String _loadBehavior_mrNo = "";
        java.lang.String _loadBehavior_jsonObject = "";
        java.lang.Boolean _loadBehavior__return = port.loadBehavior(_loadBehavior_mrNo, _loadBehavior_jsonObject);
        System.out.println("loadBehavior.result=" + _loadBehavior__return);


        }
        {
        System.out.println("Invoking updateMemberByMrNo...");
        java.lang.String _updateMemberByMrNo_mrNo = "";
        java.lang.String _updateMemberByMrNo_jsonObject = "";
        java.lang.Boolean _updateMemberByMrNo__return = port.updateMemberByMrNo(_updateMemberByMrNo_mrNo, _updateMemberByMrNo_jsonObject);
        System.out.println("updateMemberByMrNo.result=" + _updateMemberByMrNo__return);


        }
        {
        System.out.println("Invoking addOrderInfo...");
        java.lang.String _addOrderInfo_mrNo = "";
        java.lang.String _addOrderInfo_date = "";
        java.lang.String _addOrderInfo_timeInteval = "";
        java.lang.String _addOrderInfo_dept = "";
        java.lang.String _addOrderInfo_doc = "";
        java.lang.Boolean _addOrderInfo__return = port.addOrderInfo(_addOrderInfo_mrNo, _addOrderInfo_date, _addOrderInfo_timeInteval, _addOrderInfo_dept, _addOrderInfo_doc);
        System.out.println("addOrderInfo.result=" + _addOrderInfo__return);


        }
        {
        System.out.println("Invoking updateOrder...");
        java.lang.String _updateOrder_beginDate = "";
        java.lang.String _updateOrder_endDate = "";
        java.lang.String _updateOrder_timePeriod = "";
        java.lang.String _updateOrder_deptCode = "";
        java.lang.String _updateOrder_drCode = "";
        java.lang.Boolean _updateOrder__return = port.updateOrder(_updateOrder_beginDate, _updateOrder_endDate, _updateOrder_timePeriod, _updateOrder_deptCode, _updateOrder_drCode);
        System.out.println("updateOrder.result=" + _updateOrder__return);


        }
        {
        System.out.println("Invoking orderInfo...");
        java.lang.String _orderInfo_mrNo = "";
        java.lang.String _orderInfo__return = port.orderInfo(_orderInfo_mrNo);
        System.out.println("orderInfo.result=" + _orderInfo__return);


        }
        {
        System.out.println("Invoking orderCount...");
        java.lang.String _orderCount_date = "";
        java.lang.String _orderCount_deptCode = "";
        java.lang.String _orderCount_docCode = "";
        java.lang.Integer _orderCount_count = null;
        java.lang.Boolean _orderCount__return = port.orderCount(_orderCount_date, _orderCount_deptCode, _orderCount_docCode, _orderCount_count);
        System.out.println("orderCount.result=" + _orderCount__return);


        }
        {
        System.out.println("Invoking cancelUpdateOrder...");
        java.lang.String _cancelUpdateOrder_beginDate = "";
        java.lang.String _cancelUpdateOrder_endDate = "";
        java.lang.String _cancelUpdateOrder_timePeriod = "";
        java.lang.String _cancelUpdateOrder_deptCode = "";
        java.lang.String _cancelUpdateOrder_drCode = "";
        java.lang.Boolean _cancelUpdateOrder__return = port.cancelUpdateOrder(_cancelUpdateOrder_beginDate, _cancelUpdateOrder_endDate, _cancelUpdateOrder_timePeriod, _cancelUpdateOrder_deptCode, _cancelUpdateOrder_drCode);
        System.out.println("cancelUpdateOrder.result=" + _cancelUpdateOrder__return);


        }
        {
        System.out.println("Invoking delOrder...");
        java.lang.String _delOrder_orderJson = "";
        java.lang.Boolean _delOrder__return = port.delOrder(_delOrder_orderJson);
        System.out.println("delOrder.result=" + _delOrder__return);


        }
        {
        System.out.println("Invoking findMember...");
        java.lang.String _findMember_orderNum = "";
        java.lang.String _findMember__return = port.findMember(_findMember_orderNum);
        System.out.println("findMember.result=" + _findMember__return);


        }
        {
        System.out.println("Invoking cancleOrderInfo...");
        java.lang.String _cancleOrderInfo_mrNo = "";
        java.lang.String _cancleOrderInfo_date = "";
        java.lang.String _cancleOrderInfo_timeInteval = "";
        java.lang.String _cancleOrderInfo_dept = "";
        java.lang.String _cancleOrderInfo_doc = "";
        java.lang.Boolean _cancleOrderInfo__return = port.cancleOrderInfo(_cancleOrderInfo_mrNo, _cancleOrderInfo_date, _cancleOrderInfo_timeInteval, _cancleOrderInfo_dept, _cancleOrderInfo_doc);
        System.out.println("cancleOrderInfo.result=" + _cancleOrderInfo__return);


        }
        {
        System.out.println("Invoking updateMember...");
        java.lang.String _updateMember_orderNum = "";
        java.lang.String _updateMember_jsonObject = "";
        java.lang.Boolean _updateMember__return = port.updateMember(_updateMember_orderNum, _updateMember_jsonObject);
        System.out.println("updateMember.result=" + _updateMember__return);


        }
        {
        System.out.println("Invoking addOrder...");
        java.lang.String _addOrder_orderJson = "";
        java.lang.Boolean _addOrder__return = port.addOrder(_addOrder_orderJson);
        System.out.println("addOrder.result=" + _addOrder__return);


        }
        {
        System.out.println("Invoking createMember...");
        java.lang.String _createMember_jsonObject = "";
        java.lang.Boolean _createMember__return = port.createMember(_createMember_jsonObject);
        System.out.println("createMember.result=" + _createMember__return);


        }
        {
        System.out.println("Invoking updateCode...");
        java.lang.Boolean _updateCode__return = port.updateCode();
        System.out.println("updateCode.result=" + _updateCode__return);


        }
        {
        System.out.println("Invoking getOrder...");
        java.lang.String _getOrder_date = "";
        java.lang.String _getOrder_timeInteval = "";
        java.lang.String _getOrder_dept = "";
        java.lang.String _getOrder_doc = "";
        java.lang.String _getOrder__return = port.getOrder(_getOrder_date, _getOrder_timeInteval, _getOrder_dept, _getOrder_doc);
        System.out.println("getOrder.result=" + _getOrder__return);


        }

        System.exit(0);
    }

}
