package jdo.spc.spcPatInfoSyncClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-03-22T10:05:09.812+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "SpcPatInfoServiceImplService", 
                  wsdlLocation = "http://172.20.116.105:8080/webgy/services/SPCPatInfoSynchWs?wsdl",
                  targetNamespace = "http://reqinf.spc.jdo/") 
public class SpcPatInfoServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://reqinf.spc.jdo/", "SpcPatInfoServiceImplService");
    public final static QName SpcPatInfoServiceImplPort = new QName("http://reqinf.spc.jdo/", "SpcPatInfoServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.20.116.105:8080/webgy/services/SPCPatInfoSynchWs?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SpcPatInfoServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.20.116.105:8080/webgy/services/SPCPatInfoSynchWs?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SpcPatInfoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SpcPatInfoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpcPatInfoServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SpcPatInfoServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SpcPatInfoServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SpcPatInfoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns SpcPatInfoService
     */
    @WebEndpoint(name = "SpcPatInfoServiceImplPort")
    public SpcPatInfoService getSpcPatInfoServiceImplPort() {
        return super.getPort(SpcPatInfoServiceImplPort, SpcPatInfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpcPatInfoService
     */
    @WebEndpoint(name = "SpcPatInfoServiceImplPort")
    public SpcPatInfoService getSpcPatInfoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SpcPatInfoServiceImplPort, SpcPatInfoService.class, features);
    }

}
