package jdo.spc.spcPatInfoSyncClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-03-22T10:05:09.781+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://reqinf.spc.jdo/", name = "SpcPatInfoService")
@XmlSeeAlso({ObjectFactory.class})
public interface SpcPatInfoService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "onSaveSpcPatInfo", targetNamespace = "http://reqinf.spc.jdo/", className = "jdo.spc.spcPatInfoSyncClient.OnSaveSpcPatInfo")
    @WebMethod
    @ResponseWrapper(localName = "onSaveSpcPatInfoResponse", targetNamespace = "http://reqinf.spc.jdo/", className = "jdo.spc.spcPatInfoSyncClient.OnSaveSpcPatInfoResponse")
    public java.lang.String onSaveSpcPatInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        jdo.spc.spcPatInfoSyncClient.SysPatinfo arg0
    );
}
