Module.item=selectall;insertdata;updatedata;deletedata;existsCTRLDRUGCLASS_CODE;existsPHA;initCtrlDrugClassCode


//查询
selectall.Type=TSQL
selectall.SQL=SELECT  SEQ ,CTRLDRUGCLASS_CODE ,CTRLDRUGCLASS_CHN_DESC&

                      ,CTRLDRUGCLASS_ENG_DESC,TAKE_DAYS,DESCRIPTION,PRN_TYPE_CODE,PRN_TYPE_DESC&
                      , PRNSPCFORM_FLG,CTRL_FLG,NARCOTIC_FLG,TOXICANT_FLG&
                      , PSYCHOPHA_FLG  , RADIA_FLG     , TEST_DRUG_FLG  , ANTISEPTIC_FLG&
                      , ANTIBIOTIC_FLG, TPN_FLG    , OPT_USER   , OPT_DATE &
                      , OPT_TERM,PY1,PY2 & 
                      FROM SYS_CTRLDRUGCLASS order by SEQ


selectall.item=CTRLDRUGCLASS_CODE
selectall.CTRLDRUGCLASS_CODE=CTRLDRUGCLASS_CODE=<CTRLDRUGCLASS_CODE>
selectall.Debug=N


//根据CTRLDRUGCLASS_CODE新增
insertdata.Type=TSQL
insertdata.SQL = INSERT INTO SYS_CTRLDRUGCLASS (SEQ,PY1,PY2,CTRLDRUGCLASS_CODE,CTRLDRUGCLASS_CHN_DESC,CTRLDRUGCLASS_ENG_DESC,TAKE_DAYS,DESCRIPTION,PRN_TYPE_CODE,PRN_TYPE_DESC,PRNSPCFORM_FLG,CTRL_FLG,NARCOTIC_FLG,TOXICANT_FLG,PSYCHOPHA_FLG,RADIA_FLG,TEST_DRUG_FLG,ANTISEPTIC_FLG,ANTIBIOTIC_FLG,TPN_FLG,OPT_USER,OPT_TERM,OPT_DATE ) &
                                        VALUES (<SEQ>,<PY1>,<PY2>,<CTRLDRUGCLASS_CODE>,<CTRLDRUGCLASS_CHN_DESC>,<CTRLDRUGCLASS_ENG_DESC>,<TAKE_DAYS>,<DESCRIPTION>,<PRN_TYPE_CODE>,<PRN_TYPE_DESC>,<PRNSPCFORM_FLG>,<CTRL_FLG>,<NARCOTIC_FLG>,<TOXICANT_FLG>,<PSYCHOPHA_FLG>,<RADIA_FLG>,<TEST_DRUG_FLG>,<ANTISEPTIC_FLG>,<ANTIBIOTIC_FLG>,<TPN_FLG>,<OPT_USER>,<OPT_TERM>,SYSDATE) 
insertdata.Debug=N


//根据 CTRLDRUGCLASS_CODE 更新全字段
updatedata.Type=TSQL
updatedata.SQL=UPDATE SYS_CTRLDRUGCLASS SET &
			SEQ=<SEQ>,PY1=<PY1>,PY2=<PY2>,CTRLDRUGCLASS_CHN_DESC=<CTRLDRUGCLASS_CHN_DESC> ,&
			CTRLDRUGCLASS_ENG_DESC=<CTRLDRUGCLASS_ENG_DESC>,TAKE_DAYS=<TAKE_DAYS> ,DESCRIPTION=<DESCRIPTION>,&
			PRN_TYPE_CODE=<PRN_TYPE_CODE>,PRN_TYPE_DESC=<PRN_TYPE_DESC>,PRNSPCFORM_FLG=<PRNSPCFORM_FLG>,&
			CTRL_FLG =<CTRL_FLG>,NARCOTIC_FLG=<NARCOTIC_FLG>,TOXICANT_FLG=<TOXICANT_FLG>,&
			PSYCHOPHA_FLG=<PSYCHOPHA_FLG>,RADIA_FLG=<RADIA_FLG>,TEST_DRUG_FLG=<TEST_DRUG_FLG>,&
			ANTISEPTIC_FLG=<ANTISEPTIC_FLG>,ANTIBIOTIC_FLG=<ANTIBIOTIC_FLG>,TPN_FLG=<TPN_FLG>,OPT_USER=<OPT_USER>,OPT_TERM=<OPT_TERM>,OPT_DATE=SYSDATE WHERE CTRLDRUGCLASS_CODE = <CTRLDRUGCLASS_CODE> 
updatedata.Debug=N

//根据 CTRLDRUGCLASS_CODE 删除
deletedata.Type=TSQL
deletedata.SQL=DELETE SYS_CTRLDRUGCLASS  WHERE CTRLDRUGCLASS_CODE = <CTRLDRUGCLASS_CODE> 
deletedata.Debug=N


////是否存在 CTRLDRUGCLASS_CODE
existsCTRLDRUGCLASS_CODE.type=TSQL
existsCTRLDRUGCLASS_CODE.SQL=SELECT CTRLDRUGCLASS_CODE FROM SYS_CTRLDRUGCLASS WHERE CTRLDRUGCLASS_CODE=<CTRLDRUGCLASS_CODE>
//existsCTRLDRUGCLASS_CODE.Debug=N


//验证pha_base中CTRLDRUGCLASS_CODE是否有值
existsPHA.Type=TSQL
existsPHA.SQL=SELECT CTRLDRUGCLASS_CODE FROM PHA_BASE WHERE CTRLDRUGCLASS_CODE = <CTRLDRUGCLASS_CODE>
existsPHA.Debug=N

//共用combo
initCtrlDrugClassCode.Type=TSQL
initCtrlDrugClassCode.SQL=SELECT CTRLDRUGCLASS_CODE AS ID, CTRLDRUGCLASS_CHN_DESC AS NAME,CTRLDRUGCLASS_ENG_DESC AS ENNAME ,PY1, PY2 &
			    FROM SYS_CTRLDRUGCLASS ORDER BY SEQ,CTRLDRUGCLASS_CODE
initCtrlDrugClassCode.item=PRNSPCFORM_FLG;CTRL_FLG;NARCOTIC_FLG;TOXICANT_FLG;PSYCHOPHA_FLG;RADIA_FLG;TEST_DRUG_FLG;ANTISEPTIC_FLG;ANTIBIOTIC_FLG;TPN_FLG
initCtrlDrugClassCode.PRNSPCFORM_FLG=PRNSPCFORM_FLG=<PRNSPCFORM_FLG>    
initCtrlDrugClassCode.CTRL_FLG=CTRL_FLG=<CTRL_FLG>    
initCtrlDrugClassCode.NARCOTIC_FLG=NARCOTIC_FLG=<NARCOTIC_FLG>    
initCtrlDrugClassCode.TOXICANT_FLG=TOXICANT_FLG=<TOXICANT_FLG>    
initCtrlDrugClassCode.PSYCHOPHA_FLG=PSYCHOPHA_FLG=<PSYCHOPHA_FLG>    
initCtrlDrugClassCode.RADIA_FLG=RADIA_FLG=<RADIA_FLG>    
initCtrlDrugClassCode.TEST_DRUG_FLG=TEST_DRUG_FLG=<TEST_DRUG_FLG>    
initCtrlDrugClassCode.ANTISEPTIC_FLG=ANTISEPTIC_FLG=<ANTISEPTIC_FLG>    
initCtrlDrugClassCode.ANTIBIOTIC_FLG=ANTIBIOTIC_FLG=<ANTIBIOTIC_FLG>    
initCtrlDrugClassCode.TPN_FLG=TPN_FLG=<TPN_FLG>
initCtrlDrugClassCode.Debug=N

 

