Module.item=selectall;selectdata;deletedata;insertdata;updatedata;existsPosition;selectbyordercode;selectbyreplaceordercode;selectsysfee

// 根据 order_code,REPLACE_ORDER_CODE 查询数据  selectbyreplaceordercode
selectdata.Type=TSQL
selectdata.SQL=SELECT A.SEQ AS SEQ,A.ORDER_CODE AS ORDER_CODE,A.REPLACE_ORDER_CODE AS REPLACE_ORDER_CODE,B.ORDER_DESC AS ORDER_DESC,C.ORDER_DESC AS REPLACE_ORDER_DESC,A.DESCRIPTION AS DESCRIPTION,A.OPT_USER AS OPT_USER ,A.OPT_DATE AS OPT_DATE FROM PHA_REDRUG A ,SYS_FEE B,SYS_FEE C WHERE A.ORDER_CODE=<ORDER_CODE> AND A.REPLACE_ORDER_CODE=<REPLACE_ORDER_CODE> AND B.ORDER_CODE=A.ORDER_CODE AND C.ORDER_CODE=A.REPLACE_ORDER_CODE ORDER BY A.ORDER_CODE, A.SEQ
selectdata.Debug=N

// 根据 order_code, 查询数据 selectbyordercode
selectbyordercode.Type=TSQL
selectbyordercode.SQL=SELECT A.SEQ AS SEQ,A.ORDER_CODE AS ORDER_CODE,A.REPLACE_ORDER_CODE AS REPLACE_ORDER_CODE,B.ORDER_DESC AS ORDER_DESC,C.ORDER_DESC AS REPLACE_ORDER_DESC,A.DESCRIPTION AS DESCRIPTION,A.OPT_USER AS OPT_USER ,A.OPT_DATE AS OPT_DATE FROM PHA_REDRUG A ,SYS_FEE B,SYS_FEE C WHERE A.ORDER_CODE=<ORDER_CODE> AND B.ORDER_CODE=A.ORDER_CODE AND C.ORDER_CODE=A.REPLACE_ORDER_CODE ORDER BY A.ORDER_CODE, A.SEQ
selectbyordercode.Debug=N

// 根据 REPLACE_ORDER_CODE 查询数据  selectbyreplaceordercode
selectbyreplaceordercode.Type=TSQL
selectbyreplaceordercode.SQL=SELECT A.SEQ AS SEQ,A.ORDER_CODE AS ORDER_CODE,A.REPLACE_ORDER_CODE AS REPLACE_ORDER_CODE,B.ORDER_DESC AS ORDER_DESC,C.ORDER_DESC AS REPLACE_ORDER_DESC,A.DESCRIPTION AS DESCRIPTION,A.OPT_USER AS OPT_USER ,A.OPT_DATE AS OPT_DATE FROM PHA_REDRUG A ,SYS_FEE B,SYS_FEE C WHERE  A.REPLACE_ORDER_CODE=<REPLACE_ORDER_CODE> AND B.ORDER_CODE=A.ORDER_CODE AND C.ORDER_CODE=A.REPLACE_ORDER_CODE ORDER BY A.ORDER_CODE, A.SEQ
selectbyreplaceordercode.Debug=N


//根据 order_code,REPLACE_ORDER_CODE 删除数据
deletedata.Type=TSQL
deletedata.SQL=DELETE PHA_REDRUG  WHERE ORDER_CODE = <ORDER_CODE>  AND REPLACE_ORDER_CODE=<REPLACE_ORDER_CODE>
deletedata.Debug=N

//根据 order_code,REPLACE_ORDER_CODE更新数据
updatedata.Type=TSQL
updatedata.SQL=UPDATE PHA_REDRUG SET SEQ=<SEQ>,DESCRIPTION=<DESCRIPTION>,OPT_USER =<OPT_USER>,OPT_DATE=SYSDATE,OPT_TERM=<OPT_TERM> WHERE ORDER_CODE=<ORDER_CODE> AND REPLACE_ORDER_CODE=<REPLACE_ORDER_CODE> 
 WHERE ORDER_CAT1_CODE = <ORDER_CAT1_CODE> 
updatedata.Debug=N

//插入医令细分类代码，医令细分类代码说明，拼音1，拼音2,医嘱细分类群组 ，处理厂商,备注，操作人员，操作日期， 操作端末
insertdata.Type=TSQL
insertdata.SQL=INSERT INTO PHA_REDRUG VALUES( <ORDER_CODE> ,<REPLACE_ORDER_CODE> ,<SEQ>,<DESCRIPTION>,<OPT_USER>,SYSDATE,<OPT_TERM>)
insertdata.Debug=N

//查询所有数据
selectall.Type=TSQL
selectall.SQL=SELECT A.SEQ AS SEQ,A.ORDER_CODE AS ORDER_CODE,A.REPLACE_ORDER_CODE AS REPLACE_ORDER_CODE,B.ORDER_DESC AS ORDER_DESC,C.ORDER_DESC AS REPLACE_ORDER_DESC,A.DESCRIPTION AS DESCRIPTION,A.OPT_USER AS OPT_USER ,A.OPT_DATE AS OPT_DATE FROM PHA_REDRUG A ,SYS_FEE B,SYS_FEE C WHERE B.ORDER_CODE=A.ORDER_CODE AND C.ORDER_CODE=A.REPLACE_ORDER_CODE ORDER BY A.ORDER_CODE, A.SEQ
selectall.Debug=N

//根据code查询sys_fee的中文名
selectsysfee.Type=TSQL
selectsysfee.SQL=SELECT ORDER_DESC FROM SYS_FEE WHERE ORDER_CODE=<ORDER_CODE>
selectsysfee.Debug=N