Module.item=selectData

selectData.Type=TSQL
selectData.SQL=SELECT CAT1_CODE,CAT2_CODE,CAT3_CODE,SCORE,REGION_CODE,CAT3_CHN_DESC,CAT3_ENG_DESC,&
PY1,PY2,SEQ,DESCRIPTION,OPT_USER,OPT_DATE,OPT_TERM &
FROM CLP_EVL_CAT3 WHERE REGION_CODE=<REGION_CODE> ORDER BY SEQ 
selectData.Debug=N
