#
# Title:进入临床路径统计
#
# Description:进入临床路径统计
#
# Copyright: JavaHis (c) 2011
# @author shibaoliu 2011/05/04
Module.item=query;querySum;queryNo2;queryNo3
query.Type=TSQL
//wangzhilei 12-07-20 修改 ——> 添加查询区域显示字段 
query.SQL=SELECT R.REGION_CHN_ABN ,ST.STATION_DESC,F.DEPT_CHN_DESC as DEPT_CHN_DESC,F.DEPT_CHN_DESC AS DEPT_CHN_DESC,&
         (SELECT COUNT(E.CASE_NO)  &
            FROM ADM_INP E ,MRO_RECORD MR  &
           WHERE  E.DEPT_CODE = F.DEPT_CODE &
             AND  &
             E.REGION_CODE =<REGION_CODE> &
             AND MR.OUT_DATE BETWEEN TO_DATE(<START_DATE>, 'YYYYMMDDHH24MISS')  &
             AND TO_DATE(<END_DATE>, 'YYYYMMDDHH24MISS')  &
             AND E.DS_DATE IS NOT NULL AND MR.CASE_NO=E.CASE_NO AND MR.OUT_DATE IS NOT NULL ) AS NO1, &
         (SELECT COUNT(B.CASE_NO)  &
            FROM ADM_INP B ,MRO_RECORD MR &
           WHERE B.DEPT_CODE = F.DEPT_CODE AND MR.CASE_NO=B.CASE_NO &
             AND B.REGION_CODE =<REGION_CODE> &
             AND MR.OUT_DATE BETWEEN TO_DATE(<START_DATE>, 'YYYYMMDDHH24MISS')  &
             AND TO_DATE(<END_DATE>, 'YYYYMMDDHH24MISS')  &
             AND B.CLNCPATH_CODE IS NOT NULL AND  MR.OUT_DATE IS NOT NULL) AS NO2, &
         (SELECT COUNT(*) FROM (SELECT D.CASE_NO &
            FROM ADM_INP C, CLP_MANAGEM_HISTORY D ,MRO_RECORD MR  &
           WHERE C.DEPT_CODE = F.DEPT_CODE AND MR.CASE_NO=D.CASE_NO &
             AND C.CASE_NO = D.CASE_NO  &
             AND C.REGION_CODE =<REGION_CODE> &
             AND MR.OUT_DATE BETWEEN TO_DATE(<START_DATE>, 'YYYYMMDDHH24MISS')  &
             AND TO_DATE(<END_DATE>, 'YYYYMMDDHH24MISS') AND MR.OUT_DATE IS NOT NULL GROUP BY D.CASE_NO)) AS NO3  &
    FROM ADM_INP A ,SYS_STATION ST , SYS_DEPT F,SYS_REGION R  &
     WHERE A.REGION_CODE =<REGION_CODE> &
     AND A.DEPT_CODE=F.DEPT_CODE(+) AND A.REGION_CODE=R.REGION_CODE & 
     AND A.DS_DATE BETWEEN TO_DATE(<START_DATE>, 'YYYYMMDDHH24MISS') &
     AND TO_DATE(<END_DATE>, 'YYYYMMDDHH24MISS')  &
     AND A.STATION_CODE=ST.STATION_CODE(+) &
GROUP BY F.DEPT_CODE,F.DEPT_CHN_DESC,ST.STATION_DESC,R.REGION_CHN_ABN
query.Debug=N

querySum.Type=TSQL
querySum.SQL=SELECT R.REGION_CHN_ABN ,ST.STATION_DESC,F.DEPT_CHN_DESC AS DEPT_CHN_DESC,A.DEPT_CODE,ST.STATION_CODE,COUNT(A.CASE_NO) AS NO1,'' AS NO2,'' AS NO3 &
  	    FROM ADM_INP A ,SYS_STATION ST , SYS_DEPT F,SYS_REGION R ,MRO_RECORD MR &
	       WHERE A.CASE_NO=MR.CASE_NO &
	         AND A.DEPT_CODE=F.DEPT_CODE &
	         AND A.STATION_CODE=ST.STATION_CODE &
	         AND A.REGION_CODE=R.REGION_CODE & 
	         AND A.REGION_CODE =<REGION_CODE> &
	         AND A.DS_DATE IS NOT NULL &
	         AND A.DS_DATE BETWEEN TO_DATE(<START_DATE>, 'YYYYMMDDHH24MISS') &
	         AND TO_DATE(<END_DATE>, 'YYYYMMDDHH24MISS')  &
	      GROUP BY R.REGION_CHN_ABN ,ST.STATION_DESC,F.DEPT_CHN_DESC,A.DEPT_CODE,ST.STATION_CODE
querySum.Debug=N

queryNo2.Type=TSQL
queryNo2.SQL=SELECT COUNT(B.CASE_NO) AS CASE_NO &
            	FROM ADM_INP B ,MRO_RECORD MR,CLP_MANAGEM C,CLP_BSCINFO D &
           WHERE MR.CASE_NO=B.CASE_NO AND B.CASE_NO=C.CASE_NO &
             AND B.DS_DATE BETWEEN TO_DATE(<START_DATE>, 'YYYYMMDDHH24MISS')  &
             AND TO_DATE(<END_DATE>, 'YYYYMMDDHH24MISS')  &
             AND C.CLNCPATH_CODE = D.CLNCPATH_CODE &
             AND B.DS_DATE IS NOT NULL &
             AND C.DELETE_DTTM IS NULL &
             AND B.DEPT_CODE=<DEPT_CODE> AND B.STATION_CODE=<STATION_CODE>
queryNo2.Debug=N 

queryNo3.Type=TSQL
queryNo3.SQL=SELECT COUNT(B.CASE_NO) AS CASE_NO &
            	FROM ADM_INP B ,MRO_RECORD MR,CLP_MANAGEM_HISTORY D &
           WHERE MR.CASE_NO=B.CASE_NO AND B.CASE_NO=D.CASE_NO &
             AND  B.DS_DATE IS NOT NULL &
             AND B.DS_DATE BETWEEN TO_DATE(<START_DATE>, 'YYYYMMDDHH24MISS')  &
             AND TO_DATE(<END_DATE>, 'YYYYMMDDHH24MISS')  &
             AND D.END_DTTM IS NOT NULL &
             AND B.DEPT_CODE=<DEPT_CODE> AND B.STATION_CODE=<STATION_CODE>
queryNo3.Debug=N