//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 10:28:02 ÉÏÎç CST 
//


package jdo.sta.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AABType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AABType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AAB01" type="{}TimeStamp"/>
 *         &lt;element name="AAB02C" type="{}AAB02CType"/>
 *         &lt;element name="AAB03" type="{}String" minOccurs="0"/>
 *         &lt;element name="AAB06C" type="{}AAB06CType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AABType", propOrder = {
    "aab01",
    "aab02C",
    "aab03",
    "aab06C"
})
public class AABType {

    @XmlElement(name = "AAB01", required = true)
    protected TimeStamp aab01;
    @XmlElement(name = "AAB02C", required = true)
    protected AAB02CType aab02C;
    @XmlElementRef(name = "AAB03", type = JAXBElement.class)
    protected JAXBElement<String> aab03;
    @XmlElement(name = "AAB06C", required = true)
    protected AAB06CType aab06C;

    /**
     * Gets the value of the aab01 property.
     * 
     * @return
     *     possible object is
     *     {@link TimeStamp }
     *     
     */
    public TimeStamp getAAB01() {
        return aab01;
    }

    /**
     * Sets the value of the aab01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeStamp }
     *     
     */
    public void setAAB01(TimeStamp value) {
        this.aab01 = value;
    }

    /**
     * Gets the value of the aab02C property.
     * 
     * @return
     *     possible object is
     *     {@link AAB02CType }
     *     
     */
    public AAB02CType getAAB02C() {
        return aab02C;
    }

    /**
     * Sets the value of the aab02C property.
     * 
     * @param value
     *     allowed object is
     *     {@link AAB02CType }
     *     
     */
    public void setAAB02C(AAB02CType value) {
        this.aab02C = value;
    }

    /**
     * Gets the value of the aab03 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAAB03() {
        return aab03;
    }

    /**
     * Sets the value of the aab03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAAB03(JAXBElement<String> value) {
        this.aab03 = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the aab06C property.
     * 
     * @return
     *     possible object is
     *     {@link AAB06CType }
     *     
     */
    public AAB06CType getAAB06C() {
        return aab06C;
    }

    /**
     * Sets the value of the aab06C property.
     * 
     * @param value
     *     allowed object is
     *     {@link AAB06CType }
     *     
     */
    public void setAAB06C(AAB06CType value) {
        this.aab06C = value;
    }

}
