//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 10:28:02 ÉÏÎç CST 
//


package jdo.sta.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AACType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AACType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AAC01" type="{}TimeStamp"/>
 *         &lt;element name="AAC02C" type="{}AAC02CType"/>
 *         &lt;element name="AAC03" type="{}String" minOccurs="0"/>
 *         &lt;element name="AAC04" type="{}Integer6"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AACType", propOrder = {
    "aac01",
    "aac02C",
    "aac03",
    "aac04"
})
public class AACType {

    @XmlElement(name = "AAC01", required = true)
    protected TimeStamp aac01;
    @XmlElement(name = "AAC02C", required = true)
    protected AAC02CType aac02C;
    @XmlElementRef(name = "AAC03", type = JAXBElement.class)
    protected JAXBElement<String> aac03;
    @XmlElement(name = "AAC04")
    protected int aac04;

    /**
     * Gets the value of the aac01 property.
     * 
     * @return
     *     possible object is
     *     {@link TimeStamp }
     *     
     */
    public TimeStamp getAAC01() {
        return aac01;
    }

    /**
     * Sets the value of the aac01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeStamp }
     *     
     */
    public void setAAC01(TimeStamp value) {
        this.aac01 = value;
    }

    /**
     * Gets the value of the aac02C property.
     * 
     * @return
     *     possible object is
     *     {@link AAC02CType }
     *     
     */
    public AAC02CType getAAC02C() {
        return aac02C;
    }

    /**
     * Sets the value of the aac02C property.
     * 
     * @param value
     *     allowed object is
     *     {@link AAC02CType }
     *     
     */
    public void setAAC02C(AAC02CType value) {
        this.aac02C = value;
    }

    /**
     * Gets the value of the aac03 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAAC03() {
        return aac03;
    }

    /**
     * Sets the value of the aac03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAAC03(JAXBElement<String> value) {
        this.aac03 = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the aac04 property.
     * 
     */
    public int getAAC04() {
        return aac04;
    }

    /**
     * Sets the value of the aac04 property.
     * 
     */
    public void setAAC04(int value) {
        this.aac04 = value;
    }

}
