//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 10:28:02 ÉÏÎç CST 
//


package jdo.sta.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AAType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AAType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AAA" type="{}AAAType"/>
 *         &lt;element name="AAB" type="{}AABType"/>
 *         &lt;element name="AAC" type="{}AACType"/>
 *         &lt;element name="AAD01C" type="{}AAD01CType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AAType", propOrder = {
    "aaa",
    "aab",
    "aac",
    "aad01C"
})
public class AAType {

    @XmlElement(name = "AAA", required = true)
    protected AAAType aaa;
    @XmlElement(name = "AAB", required = true)
    protected AABType aab;
    @XmlElement(name = "AAC", required = true)
    protected AACType aac;
    @XmlElementRef(name = "AAD01C", type = JAXBElement.class)
    protected JAXBElement<java.lang.String> aad01C;

    /**
     * Gets the value of the aaa property.
     * 
     * @return
     *     possible object is
     *     {@link AAAType }
     *     
     */
    public AAAType getAAA() {
        return aaa;
    }

    /**
     * Sets the value of the aaa property.
     * 
     * @param value
     *     allowed object is
     *     {@link AAAType }
     *     
     */
    public void setAAA(AAAType value) {
        this.aaa = value;
    }

    /**
     * Gets the value of the aab property.
     * 
     * @return
     *     possible object is
     *     {@link AABType }
     *     
     */
    public AABType getAAB() {
        return aab;
    }

    /**
     * Sets the value of the aab property.
     * 
     * @param value
     *     allowed object is
     *     {@link AABType }
     *     
     */
    public void setAAB(AABType value) {
        this.aab = value;
    }

    /**
     * Gets the value of the aac property.
     * 
     * @return
     *     possible object is
     *     {@link AACType }
     *     
     */
    public AACType getAAC() {
        return aac;
    }

    /**
     * Sets the value of the aac property.
     * 
     * @param value
     *     allowed object is
     *     {@link AACType }
     *     
     */
    public void setAAC(AACType value) {
        this.aac = value;
    }

    /**
     * Gets the value of the aad01C property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}
     *     
     */
    public JAXBElement<java.lang.String> getAAD01C() {
        return aad01C;
    }

    /**
     * Sets the value of the aad01C property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}
     *     
     */
    public void setAAD01C(JAXBElement<java.lang.String> value) {
        this.aad01C = ((JAXBElement<java.lang.String> ) value);
    }

}
