//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 10:28:02 ÉÏÎç CST 
//


package jdo.sta.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ABAType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ABAType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ABA01C" type="{}String" minOccurs="0"/>
 *         &lt;element name="ABA01N" type="{}String" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ABAType", propOrder = {
    "aba01C",
    "aba01N"
})
public class ABAType {

    @XmlElementRef(name = "ABA01C", type = JAXBElement.class)
    protected JAXBElement<String> aba01C;
    @XmlElementRef(name = "ABA01N", type = JAXBElement.class)
    protected JAXBElement<String> aba01N;

    /**
     * Gets the value of the aba01C property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getABA01C() {
        return aba01C;
    }

    /**
     * Sets the value of the aba01C property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setABA01C(JAXBElement<String> value) {
        this.aba01C = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the aba01N property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getABA01N() {
        return aba01N;
    }

    /**
     * Sets the value of the aba01N property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setABA01N(JAXBElement<String> value) {
        this.aba01N = ((JAXBElement<String> ) value);
    }

}
