//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 10:28:02 ÉÏÎç CST 
//


package jdo.sta.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ABCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ABCType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ABC01C" type="{}String"/>
 *         &lt;element name="ABC01N" type="{}String"/>
 *         &lt;element name="ABC03C" type="{}ABC03CType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ABCType", propOrder = {
    "abc01C",
    "abc01N",
    "abc03C"
})
public class ABCType {

    @XmlElement(name = "ABC01C", required = true)
    protected String abc01C;
    @XmlElement(name = "ABC01N", required = true)
    protected String abc01N;
    @XmlElement(name = "ABC03C", required = true)
    protected ABC03CType abc03C;

    /**
     * Gets the value of the abc01C property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getABC01C() {
        return abc01C;
    }

    /**
     * Sets the value of the abc01C property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setABC01C(String value) {
        this.abc01C = value;
    }

    /**
     * Gets the value of the abc01N property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getABC01N() {
        return abc01N;
    }

    /**
     * Sets the value of the abc01N property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setABC01N(String value) {
        this.abc01N = value;
    }

    /**
     * Gets the value of the abc03C property.
     * 
     * @return
     *     possible object is
     *     {@link ABC03CType }
     *     
     */
    public ABC03CType getABC03C() {
        return abc03C;
    }

    /**
     * Sets the value of the abc03C property.
     * 
     * @param value
     *     allowed object is
     *     {@link ABC03CType }
     *     
     */
    public void setABC03C(ABC03CType value) {
        this.abc03C = value;
    }

}
