//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 10:28:02 ÉÏÎç CST 
//


package jdo.sta.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ABDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ABDType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ABD01C" type="{}String"/>
 *         &lt;element name="ABD01N" type="{}String"/>
 *         &lt;element name="ABD03C" type="{}ABC03CType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ABDType", propOrder = {
    "abd01C",
    "abd01N",
    "abd03C"
})
public class ABDType {

    @XmlElement(name = "ABD01C", required = true)
    protected String abd01C;
    @XmlElement(name = "ABD01N", required = true)
    protected String abd01N;
    @XmlElement(name = "ABD03C", required = true)
    protected ABC03CType abd03C;

    /**
     * Gets the value of the abd01C property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getABD01C() {
        return abd01C;
    }

    /**
     * Sets the value of the abd01C property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setABD01C(String value) {
        this.abd01C = value;
    }

    /**
     * Gets the value of the abd01N property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getABD01N() {
        return abd01N;
    }

    /**
     * Sets the value of the abd01N property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setABD01N(String value) {
        this.abd01N = value;
    }

    /**
     * Gets the value of the abd03C property.
     * 
     * @return
     *     possible object is
     *     {@link ABC03CType }
     *     
     */
    public ABC03CType getABD03C() {
        return abd03C;
    }

    /**
     * Sets the value of the abd03C property.
     * 
     * @param value
     *     allowed object is
     *     {@link ABC03CType }
     *     
     */
    public void setABD03C(ABC03CType value) {
        this.abd03C = value;
    }

}
