//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 10:28:02 ÉÏÎç CST 
//


package jdo.sta.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ABType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ABType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ABA" type="{}ABAType" minOccurs="0"/>
 *         &lt;element name="ABC" type="{}ABCType"/>
 *         &lt;element name="ABDS" type="{}ABDSType" minOccurs="0"/>
 *         &lt;element name="ABF" type="{}ABFType" minOccurs="0"/>
 *         &lt;element name="ABG" type="{}ABGType" minOccurs="0"/>
 *         &lt;element name="ABH" type="{}ABHType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ABType", propOrder = {
    "aba",
    "abc",
    "abds",
    "abf",
    "abg",
    "abh"
})
public class ABType {

    @XmlElementRef(name = "ABA", type = JAXBElement.class)
    protected JAXBElement<ABAType> aba;
    @XmlElement(name = "ABC", required = true)
    protected ABCType abc;
    @XmlElementRef(name = "ABDS", type = JAXBElement.class)
    protected JAXBElement<ABDSType> abds;
    @XmlElementRef(name = "ABF", type = JAXBElement.class)
    protected JAXBElement<ABFType> abf;
    @XmlElementRef(name = "ABG", type = JAXBElement.class)
    protected JAXBElement<ABGType> abg;
    @XmlElementRef(name = "ABH", type = JAXBElement.class)
    protected JAXBElement<ABHType> abh;

    /**
     * Gets the value of the aba property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ABAType }{@code >}
     *     
     */
    public JAXBElement<ABAType> getABA() {
        return aba;
    }

    /**
     * Sets the value of the aba property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ABAType }{@code >}
     *     
     */
    public void setABA(JAXBElement<ABAType> value) {
        this.aba = ((JAXBElement<ABAType> ) value);
    }

    /**
     * Gets the value of the abc property.
     * 
     * @return
     *     possible object is
     *     {@link ABCType }
     *     
     */
    public ABCType getABC() {
        return abc;
    }

    /**
     * Sets the value of the abc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ABCType }
     *     
     */
    public void setABC(ABCType value) {
        this.abc = value;
    }

    /**
     * Gets the value of the abds property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ABDSType }{@code >}
     *     
     */
    public JAXBElement<ABDSType> getABDS() {
        return abds;
    }

    /**
     * Sets the value of the abds property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ABDSType }{@code >}
     *     
     */
    public void setABDS(JAXBElement<ABDSType> value) {
        this.abds = ((JAXBElement<ABDSType> ) value);
    }

    /**
     * Gets the value of the abf property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ABFType }{@code >}
     *     
     */
    public JAXBElement<ABFType> getABF() {
        return abf;
    }

    /**
     * Sets the value of the abf property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ABFType }{@code >}
     *     
     */
    public void setABF(JAXBElement<ABFType> value) {
        this.abf = ((JAXBElement<ABFType> ) value);
    }

    /**
     * Gets the value of the abg property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ABGType }{@code >}
     *     
     */
    public JAXBElement<ABGType> getABG() {
        return abg;
    }

    /**
     * Sets the value of the abg property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ABGType }{@code >}
     *     
     */
    public void setABG(JAXBElement<ABGType> value) {
        this.abg = ((JAXBElement<ABGType> ) value);
    }

    /**
     * Gets the value of the abh property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ABHType }{@code >}
     *     
     */
    public JAXBElement<ABHType> getABH() {
        return abh;
    }

    /**
     * Sets the value of the abh property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ABHType }{@code >}
     *     
     */
    public void setABH(JAXBElement<ABHType> value) {
        this.abh = ((JAXBElement<ABHType> ) value);
    }

}
