//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 10:28:02 ÉÏÎç CST 
//


package jdo.sta.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ACType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ACType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ACAS" type="{}ACASType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ACType", propOrder = {
    "acas"
})
public class ACType {

    @XmlElementRef(name = "ACAS", type = JAXBElement.class)
    protected JAXBElement<ACASType> acas;

    /**
     * Gets the value of the acas property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ACASType }{@code >}
     *     
     */
    public JAXBElement<ACASType> getACAS() {
        return acas;
    }

    /**
     * Sets the value of the acas property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ACASType }{@code >}
     *     
     */
    public void setACAS(JAXBElement<ACASType> value) {
        this.acas = ((JAXBElement<ACASType> ) value);
    }

}
