//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 10:28:02 ÉÏÎç CST 
//


package jdo.sta.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ADAType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ADAType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ADA01" type="{}morethan0Prize"/>
 *         &lt;element name="ADA0101" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA11" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA21" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA22" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA23" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA24" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA25" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA26" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA27" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA28" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA13" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA15" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA12" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA29" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA03" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA30" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA31" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA32" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA07" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA08" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA33" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA34" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA35" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA36" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA37" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA38" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA02" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA39" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA09" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA10" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA04" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA40" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA41" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA42" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA43" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA44" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA05" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA06" type="{}Prize" minOccurs="0"/>
 *         &lt;element name="ADA20" type="{}Prize" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ADAType", propOrder = {
    "ada01",
    "ada0101",
    "ada11",
    "ada21",
    "ada22",
    "ada23",
    "ada24",
    "ada25",
    "ada26",
    "ada27",
    "ada28",
    "ada13",
    "ada15",
    "ada12",
    "ada29",
    "ada03",
    "ada30",
    "ada31",
    "ada32",
    "ada07",
    "ada08",
    "ada33",
    "ada34",
    "ada35",
    "ada36",
    "ada37",
    "ada38",
    "ada02",
    "ada39",
    "ada09",
    "ada10",
    "ada04",
    "ada40",
    "ada41",
    "ada42",
    "ada43",
    "ada44",
    "ada05",
    "ada06",
    "ada20"
})
public class ADAType {

    @XmlElement(name = "ADA01", required = true)
    protected Morethan0Prize ada01;
    @XmlElementRef(name = "ADA0101", type = JAXBElement.class)
    protected JAXBElement<Prize> ada0101;
    @XmlElementRef(name = "ADA11", type = JAXBElement.class)
    protected JAXBElement<Prize> ada11;
    @XmlElementRef(name = "ADA21", type = JAXBElement.class)
    protected JAXBElement<Prize> ada21;
    @XmlElementRef(name = "ADA22", type = JAXBElement.class)
    protected JAXBElement<Prize> ada22;
    @XmlElementRef(name = "ADA23", type = JAXBElement.class)
    protected JAXBElement<Prize> ada23;
    @XmlElementRef(name = "ADA24", type = JAXBElement.class)
    protected JAXBElement<Prize> ada24;
    @XmlElementRef(name = "ADA25", type = JAXBElement.class)
    protected JAXBElement<Prize> ada25;
    @XmlElementRef(name = "ADA26", type = JAXBElement.class)
    protected JAXBElement<Prize> ada26;
    @XmlElementRef(name = "ADA27", type = JAXBElement.class)
    protected JAXBElement<Prize> ada27;
    @XmlElementRef(name = "ADA28", type = JAXBElement.class)
    protected JAXBElement<Prize> ada28;
    @XmlElementRef(name = "ADA13", type = JAXBElement.class)
    protected JAXBElement<Prize> ada13;
    @XmlElementRef(name = "ADA15", type = JAXBElement.class)
    protected JAXBElement<Prize> ada15;
    @XmlElementRef(name = "ADA12", type = JAXBElement.class)
    protected JAXBElement<Prize> ada12;
    @XmlElementRef(name = "ADA29", type = JAXBElement.class)
    protected JAXBElement<Prize> ada29;
    @XmlElementRef(name = "ADA03", type = JAXBElement.class)
    protected JAXBElement<Prize> ada03;
    @XmlElementRef(name = "ADA30", type = JAXBElement.class)
    protected JAXBElement<Prize> ada30;
    @XmlElementRef(name = "ADA31", type = JAXBElement.class)
    protected JAXBElement<Prize> ada31;
    @XmlElementRef(name = "ADA32", type = JAXBElement.class)
    protected JAXBElement<Prize> ada32;
    @XmlElementRef(name = "ADA07", type = JAXBElement.class)
    protected JAXBElement<Prize> ada07;
    @XmlElementRef(name = "ADA08", type = JAXBElement.class)
    protected JAXBElement<Prize> ada08;
    @XmlElementRef(name = "ADA33", type = JAXBElement.class)
    protected JAXBElement<Prize> ada33;
    @XmlElementRef(name = "ADA34", type = JAXBElement.class)
    protected JAXBElement<Prize> ada34;
    @XmlElementRef(name = "ADA35", type = JAXBElement.class)
    protected JAXBElement<Prize> ada35;
    @XmlElementRef(name = "ADA36", type = JAXBElement.class)
    protected JAXBElement<Prize> ada36;
    @XmlElementRef(name = "ADA37", type = JAXBElement.class)
    protected JAXBElement<Prize> ada37;
    @XmlElementRef(name = "ADA38", type = JAXBElement.class)
    protected JAXBElement<Prize> ada38;
    @XmlElementRef(name = "ADA02", type = JAXBElement.class)
    protected JAXBElement<Prize> ada02;
    @XmlElementRef(name = "ADA39", type = JAXBElement.class)
    protected JAXBElement<Prize> ada39;
    @XmlElementRef(name = "ADA09", type = JAXBElement.class)
    protected JAXBElement<Prize> ada09;
    @XmlElementRef(name = "ADA10", type = JAXBElement.class)
    protected JAXBElement<Prize> ada10;
    @XmlElementRef(name = "ADA04", type = JAXBElement.class)
    protected JAXBElement<Prize> ada04;
    @XmlElementRef(name = "ADA40", type = JAXBElement.class)
    protected JAXBElement<Prize> ada40;
    @XmlElementRef(name = "ADA41", type = JAXBElement.class)
    protected JAXBElement<Prize> ada41;
    @XmlElementRef(name = "ADA42", type = JAXBElement.class)
    protected JAXBElement<Prize> ada42;
    @XmlElementRef(name = "ADA43", type = JAXBElement.class)
    protected JAXBElement<Prize> ada43;
    @XmlElementRef(name = "ADA44", type = JAXBElement.class)
    protected JAXBElement<Prize> ada44;
    @XmlElementRef(name = "ADA05", type = JAXBElement.class)
    protected JAXBElement<Prize> ada05;
    @XmlElementRef(name = "ADA06", type = JAXBElement.class)
    protected JAXBElement<Prize> ada06;
    @XmlElementRef(name = "ADA20", type = JAXBElement.class)
    protected JAXBElement<Prize> ada20;

    /**
     * Gets the value of the ada01 property.
     * 
     * @return
     *     possible object is
     *     {@link Morethan0Prize }
     *     
     */
    public Morethan0Prize getADA01() {
        return ada01;
    }

    /**
     * Sets the value of the ada01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Morethan0Prize }
     *     
     */
    public void setADA01(Morethan0Prize value) {
        this.ada01 = value;
    }

    /**
     * Gets the value of the ada0101 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA0101() {
        return ada0101;
    }

    /**
     * Sets the value of the ada0101 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA0101(JAXBElement<Prize> value) {
        this.ada0101 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada11 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA11() {
        return ada11;
    }

    /**
     * Sets the value of the ada11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA11(JAXBElement<Prize> value) {
        this.ada11 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada21 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA21() {
        return ada21;
    }

    /**
     * Sets the value of the ada21 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA21(JAXBElement<Prize> value) {
        this.ada21 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada22 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA22() {
        return ada22;
    }

    /**
     * Sets the value of the ada22 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA22(JAXBElement<Prize> value) {
        this.ada22 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada23 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA23() {
        return ada23;
    }

    /**
     * Sets the value of the ada23 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA23(JAXBElement<Prize> value) {
        this.ada23 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada24 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA24() {
        return ada24;
    }

    /**
     * Sets the value of the ada24 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA24(JAXBElement<Prize> value) {
        this.ada24 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada25 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA25() {
        return ada25;
    }

    /**
     * Sets the value of the ada25 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA25(JAXBElement<Prize> value) {
        this.ada25 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada26 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA26() {
        return ada26;
    }

    /**
     * Sets the value of the ada26 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA26(JAXBElement<Prize> value) {
        this.ada26 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada27 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA27() {
        return ada27;
    }

    /**
     * Sets the value of the ada27 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA27(JAXBElement<Prize> value) {
        this.ada27 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada28 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA28() {
        return ada28;
    }

    /**
     * Sets the value of the ada28 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA28(JAXBElement<Prize> value) {
        this.ada28 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada13 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA13() {
        return ada13;
    }

    /**
     * Sets the value of the ada13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA13(JAXBElement<Prize> value) {
        this.ada13 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada15 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA15() {
        return ada15;
    }

    /**
     * Sets the value of the ada15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA15(JAXBElement<Prize> value) {
        this.ada15 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada12 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA12() {
        return ada12;
    }

    /**
     * Sets the value of the ada12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA12(JAXBElement<Prize> value) {
        this.ada12 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada29 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA29() {
        return ada29;
    }

    /**
     * Sets the value of the ada29 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA29(JAXBElement<Prize> value) {
        this.ada29 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada03 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA03() {
        return ada03;
    }

    /**
     * Sets the value of the ada03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA03(JAXBElement<Prize> value) {
        this.ada03 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada30 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA30() {
        return ada30;
    }

    /**
     * Sets the value of the ada30 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA30(JAXBElement<Prize> value) {
        this.ada30 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada31 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA31() {
        return ada31;
    }

    /**
     * Sets the value of the ada31 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA31(JAXBElement<Prize> value) {
        this.ada31 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada32 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA32() {
        return ada32;
    }

    /**
     * Sets the value of the ada32 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA32(JAXBElement<Prize> value) {
        this.ada32 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada07 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA07() {
        return ada07;
    }

    /**
     * Sets the value of the ada07 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA07(JAXBElement<Prize> value) {
        this.ada07 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada08 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA08() {
        return ada08;
    }

    /**
     * Sets the value of the ada08 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA08(JAXBElement<Prize> value) {
        this.ada08 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada33 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA33() {
        return ada33;
    }

    /**
     * Sets the value of the ada33 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA33(JAXBElement<Prize> value) {
        this.ada33 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada34 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA34() {
        return ada34;
    }

    /**
     * Sets the value of the ada34 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA34(JAXBElement<Prize> value) {
        this.ada34 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada35 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA35() {
        return ada35;
    }

    /**
     * Sets the value of the ada35 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA35(JAXBElement<Prize> value) {
        this.ada35 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada36 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA36() {
        return ada36;
    }

    /**
     * Sets the value of the ada36 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA36(JAXBElement<Prize> value) {
        this.ada36 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada37 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA37() {
        return ada37;
    }

    /**
     * Sets the value of the ada37 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA37(JAXBElement<Prize> value) {
        this.ada37 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada38 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA38() {
        return ada38;
    }

    /**
     * Sets the value of the ada38 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA38(JAXBElement<Prize> value) {
        this.ada38 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada02 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA02() {
        return ada02;
    }

    /**
     * Sets the value of the ada02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA02(JAXBElement<Prize> value) {
        this.ada02 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada39 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA39() {
        return ada39;
    }

    /**
     * Sets the value of the ada39 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA39(JAXBElement<Prize> value) {
        this.ada39 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada09 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA09() {
        return ada09;
    }

    /**
     * Sets the value of the ada09 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA09(JAXBElement<Prize> value) {
        this.ada09 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada10 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA10() {
        return ada10;
    }

    /**
     * Sets the value of the ada10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA10(JAXBElement<Prize> value) {
        this.ada10 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada04 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA04() {
        return ada04;
    }

    /**
     * Sets the value of the ada04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA04(JAXBElement<Prize> value) {
        this.ada04 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada40 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA40() {
        return ada40;
    }

    /**
     * Sets the value of the ada40 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA40(JAXBElement<Prize> value) {
        this.ada40 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada41 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA41() {
        return ada41;
    }

    /**
     * Sets the value of the ada41 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA41(JAXBElement<Prize> value) {
        this.ada41 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada42 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA42() {
        return ada42;
    }

    /**
     * Sets the value of the ada42 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA42(JAXBElement<Prize> value) {
        this.ada42 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada43 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA43() {
        return ada43;
    }

    /**
     * Sets the value of the ada43 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA43(JAXBElement<Prize> value) {
        this.ada43 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada44 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA44() {
        return ada44;
    }

    /**
     * Sets the value of the ada44 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA44(JAXBElement<Prize> value) {
        this.ada44 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada05 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA05() {
        return ada05;
    }

    /**
     * Sets the value of the ada05 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA05(JAXBElement<Prize> value) {
        this.ada05 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada06 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA06() {
        return ada06;
    }

    /**
     * Sets the value of the ada06 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA06(JAXBElement<Prize> value) {
        this.ada06 = ((JAXBElement<Prize> ) value);
    }

    /**
     * Gets the value of the ada20 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public JAXBElement<Prize> getADA20() {
        return ada20;
    }

    /**
     * Sets the value of the ada20 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Prize }{@code >}
     *     
     */
    public void setADA20(JAXBElement<Prize> value) {
        this.ada20 = ((JAXBElement<Prize> ) value);
    }

}
