//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 10:28:02 ÉÏÎç CST 
//


package jdo.sta.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AEBType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AEBType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AEB02C" type="{}oneORtwoType"/>
 *         &lt;element name="AEB01" type="{}String" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AEBType", propOrder = {
    "aeb02C",
    "aeb01"
})
public class AEBType {

    @XmlElement(name = "AEB02C", required = true)
    protected OneORtwoType aeb02C;
    @XmlElementRef(name = "AEB01", type = JAXBElement.class)
    protected JAXBElement<String> aeb01;

    /**
     * Gets the value of the aeb02C property.
     * 
     * @return
     *     possible object is
     *     {@link OneORtwoType }
     *     
     */
    public OneORtwoType getAEB02C() {
        return aeb02C;
    }

    /**
     * Sets the value of the aeb02C property.
     * 
     * @param value
     *     allowed object is
     *     {@link OneORtwoType }
     *     
     */
    public void setAEB02C(OneORtwoType value) {
        this.aeb02C = value;
    }

    /**
     * Gets the value of the aeb01 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAEB01() {
        return aeb01;
    }

    /**
     * Sets the value of the aeb01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAEB01(JAXBElement<String> value) {
        this.aeb01 = ((JAXBElement<String> ) value);
    }

}
