//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 10:28:02 ÉÏÎç CST 
//


package jdo.sta.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AEGType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AEGType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AEG01C" type="{}AEG01CType" minOccurs="0"/>
 *         &lt;element name="AEG02C" type="{}AEG02CType" minOccurs="0"/>
 *         &lt;element name="AEG04" type="{}Integer6" minOccurs="0"/>
 *         &lt;element name="AEG05" type="{}Integer6" minOccurs="0"/>
 *         &lt;element name="AEG06" type="{}Integer6" minOccurs="0"/>
 *         &lt;element name="AEG07" type="{}Integer6" minOccurs="0"/>
 *         &lt;element name="AEG08" type="{}Integer6" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AEGType", propOrder = {
    "aeg01C",
    "aeg02C",
    "aeg04",
    "aeg05",
    "aeg06",
    "aeg07",
    "aeg08"
})
public class AEGType {

    @XmlElementRef(name = "AEG01C", type = JAXBElement.class)
    protected JAXBElement<AEG01CType> aeg01C;
    @XmlElementRef(name = "AEG02C", type = JAXBElement.class)
    protected JAXBElement<AEG02CType> aeg02C;
    @XmlElementRef(name = "AEG04", type = JAXBElement.class)
    protected JAXBElement<Integer> aeg04;
    @XmlElementRef(name = "AEG05", type = JAXBElement.class)
    protected JAXBElement<Integer> aeg05;
    @XmlElementRef(name = "AEG06", type = JAXBElement.class)
    protected JAXBElement<Integer> aeg06;
    @XmlElementRef(name = "AEG07", type = JAXBElement.class)
    protected JAXBElement<Integer> aeg07;
    @XmlElementRef(name = "AEG08", type = JAXBElement.class)
    protected JAXBElement<Integer> aeg08;

    /**
     * Gets the value of the aeg01C property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AEG01CType }{@code >}
     *     
     */
    public JAXBElement<AEG01CType> getAEG01C() {
        return aeg01C;
    }

    /**
     * Sets the value of the aeg01C property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AEG01CType }{@code >}
     *     
     */
    public void setAEG01C(JAXBElement<AEG01CType> value) {
        this.aeg01C = ((JAXBElement<AEG01CType> ) value);
    }

    /**
     * Gets the value of the aeg02C property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AEG02CType }{@code >}
     *     
     */
    public JAXBElement<AEG02CType> getAEG02C() {
        return aeg02C;
    }

    /**
     * Sets the value of the aeg02C property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AEG02CType }{@code >}
     *     
     */
    public void setAEG02C(JAXBElement<AEG02CType> value) {
        this.aeg02C = ((JAXBElement<AEG02CType> ) value);
    }

    /**
     * Gets the value of the aeg04 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getAEG04() {
        return aeg04;
    }

    /**
     * Sets the value of the aeg04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setAEG04(JAXBElement<Integer> value) {
        this.aeg04 = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the aeg05 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getAEG05() {
        return aeg05;
    }

    /**
     * Sets the value of the aeg05 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setAEG05(JAXBElement<Integer> value) {
        this.aeg05 = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the aeg06 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getAEG06() {
        return aeg06;
    }

    /**
     * Sets the value of the aeg06 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setAEG06(JAXBElement<Integer> value) {
        this.aeg06 = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the aeg07 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getAEG07() {
        return aeg07;
    }

    /**
     * Sets the value of the aeg07 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setAEG07(JAXBElement<Integer> value) {
        this.aeg07 = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the aeg08 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getAEG08() {
        return aeg08;
    }

    /**
     * Sets the value of the aeg08 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setAEG08(JAXBElement<Integer> value) {
        this.aeg08 = ((JAXBElement<Integer> ) value);
    }

}
