//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 10:28:02 ÉÏÎç CST 
//


package jdo.sta.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AEJType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AEJType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AEJ01" type="{}AEJ01Type" minOccurs="0"/>
 *         &lt;element name="AEJ02" type="{}HoursType" minOccurs="0"/>
 *         &lt;element name="AEJ03" type="{}Minute" minOccurs="0"/>
 *         &lt;element name="AEJ04" type="{}AEJ01Type" minOccurs="0"/>
 *         &lt;element name="AEJ05" type="{}HoursType" minOccurs="0"/>
 *         &lt;element name="AEJ06" type="{}Minute" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AEJType", propOrder = {
    "aej01",
    "aej02",
    "aej03",
    "aej04",
    "aej05",
    "aej06"
})
public class AEJType {

    @XmlElementRef(name = "AEJ01", type = JAXBElement.class)
    protected JAXBElement<Integer> aej01;
    @XmlElementRef(name = "AEJ02", type = JAXBElement.class)
    protected JAXBElement<Integer> aej02;
    @XmlElementRef(name = "AEJ03", type = JAXBElement.class)
    protected JAXBElement<Minute> aej03;
    @XmlElementRef(name = "AEJ04", type = JAXBElement.class)
    protected JAXBElement<Integer> aej04;
    @XmlElementRef(name = "AEJ05", type = JAXBElement.class)
    protected JAXBElement<Integer> aej05;
    @XmlElementRef(name = "AEJ06", type = JAXBElement.class)
    protected JAXBElement<Minute> aej06;

    /**
     * Gets the value of the aej01 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getAEJ01() {
        return aej01;
    }

    /**
     * Sets the value of the aej01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setAEJ01(JAXBElement<Integer> value) {
        this.aej01 = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the aej02 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getAEJ02() {
        return aej02;
    }

    /**
     * Sets the value of the aej02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setAEJ02(JAXBElement<Integer> value) {
        this.aej02 = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the aej03 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Minute }{@code >}
     *     
     */
    public JAXBElement<Minute> getAEJ03() {
        return aej03;
    }

    /**
     * Sets the value of the aej03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Minute }{@code >}
     *     
     */
    public void setAEJ03(JAXBElement<Minute> value) {
        this.aej03 = ((JAXBElement<Minute> ) value);
    }

    /**
     * Gets the value of the aej04 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getAEJ04() {
        return aej04;
    }

    /**
     * Sets the value of the aej04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setAEJ04(JAXBElement<Integer> value) {
        this.aej04 = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the aej05 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getAEJ05() {
        return aej05;
    }

    /**
     * Sets the value of the aej05 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setAEJ05(JAXBElement<Integer> value) {
        this.aej05 = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the aej06 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Minute }{@code >}
     *     
     */
    public JAXBElement<Minute> getAEJ06() {
        return aej06;
    }

    /**
     * Sets the value of the aej06 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Minute }{@code >}
     *     
     */
    public void setAEJ06(JAXBElement<Minute> value) {
        this.aej06 = ((JAXBElement<Minute> ) value);
    }

}
