//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 10:28:02 ÉÏÎç CST 
//


package jdo.sta.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AEMType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AEMType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AEM01C" type="{}lyfsdmDic"/>
 *         &lt;element name="AEM02" type="{}String" minOccurs="0"/>
 *         &lt;element name="AEM03C" type="{}oneORtwoType"/>
 *         &lt;element name="AEM04" type="{}String" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AEMType", propOrder = {
    "aem01C",
    "aem02",
    "aem03C",
    "aem04"
})
public class AEMType {

    @XmlElement(name = "AEM01C", required = true)
    protected java.lang.String aem01C;
    @XmlElementRef(name = "AEM02", type = JAXBElement.class)
    protected JAXBElement<jdo.sta.bean.String> aem02;
    @XmlElement(name = "AEM03C", required = true)
    protected OneORtwoType aem03C;
    @XmlElementRef(name = "AEM04", type = JAXBElement.class)
    protected JAXBElement<jdo.sta.bean.String> aem04;

    /**
     * Gets the value of the aem01C property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getAEM01C() {
        return aem01C;
    }

    /**
     * Sets the value of the aem01C property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setAEM01C(java.lang.String value) {
        this.aem01C = value;
    }

    /**
     * Gets the value of the aem02 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}
     *     
     */
    public JAXBElement<jdo.sta.bean.String> getAEM02() {
        return aem02;
    }

    /**
     * Sets the value of the aem02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}
     *     
     */
    public void setAEM02(JAXBElement<jdo.sta.bean.String> value) {
        this.aem02 = ((JAXBElement<jdo.sta.bean.String> ) value);
    }

    /**
     * Gets the value of the aem03C property.
     * 
     * @return
     *     possible object is
     *     {@link OneORtwoType }
     *     
     */
    public OneORtwoType getAEM03C() {
        return aem03C;
    }

    /**
     * Sets the value of the aem03C property.
     * 
     * @param value
     *     allowed object is
     *     {@link OneORtwoType }
     *     
     */
    public void setAEM03C(OneORtwoType value) {
        this.aem03C = value;
    }

    /**
     * Gets the value of the aem04 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}
     *     
     */
    public JAXBElement<jdo.sta.bean.String> getAEM04() {
        return aem04;
    }

    /**
     * Sets the value of the aem04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}
     *     
     */
    public void setAEM04(JAXBElement<jdo.sta.bean.String> value) {
        this.aem04 = ((JAXBElement<jdo.sta.bean.String> ) value);
    }

}
