//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 10:28:02 ÉÏÎç CST 
//


package jdo.sta.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AEType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AEB" type="{}AEBType" minOccurs="0"/>
 *         &lt;element name="AED" type="{}AEDType" minOccurs="0"/>
 *         &lt;element name="AEE" type="{}AEEType"/>
 *         &lt;element name="AEG" type="{}AEGType" minOccurs="0"/>
 *         &lt;element name="AEJ" type="{}AEJType" minOccurs="0"/>
 *         &lt;element name="AEKS" type="{}AEKSType" minOccurs="0"/>
 *         &lt;element name="AEL01" type="{}Integer6" minOccurs="0"/>
 *         &lt;element name="AENS" type="{}AENSType" minOccurs="0"/>
 *         &lt;element name="AEM" type="{}AEMType" minOccurs="0"/>
 *         &lt;element name="AEI" type="{}AEIType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AEType", propOrder = {
    "aeb",
    "aed",
    "aee",
    "aeg",
    "aej",
    "aeks",
    "ael01",
    "aens",
    "aem",
    "aei"
})
public class AEType {

    @XmlElementRef(name = "AEB", type = JAXBElement.class)
    protected JAXBElement<AEBType> aeb;
    @XmlElementRef(name = "AED", type = JAXBElement.class)
    protected JAXBElement<AEDType> aed;
    @XmlElement(name = "AEE", required = true)
    protected AEEType aee;
    @XmlElementRef(name = "AEG", type = JAXBElement.class)
    protected JAXBElement<AEGType> aeg;
    @XmlElementRef(name = "AEJ", type = JAXBElement.class)
    protected JAXBElement<AEJType> aej;
    @XmlElementRef(name = "AEKS", type = JAXBElement.class)
    protected JAXBElement<AEKSType> aeks;
    @XmlElementRef(name = "AEL01", type = JAXBElement.class)
    protected JAXBElement<Integer> ael01;
    @XmlElementRef(name = "AENS", type = JAXBElement.class)
    protected JAXBElement<AENSType> aens;
    @XmlElementRef(name = "AEM", type = JAXBElement.class)
    protected JAXBElement<AEMType> aem;
    @XmlElementRef(name = "AEI", type = JAXBElement.class)
    protected JAXBElement<AEIType> aei;

    /**
     * Gets the value of the aeb property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AEBType }{@code >}
     *     
     */
    public JAXBElement<AEBType> getAEB() {
        return aeb;
    }

    /**
     * Sets the value of the aeb property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AEBType }{@code >}
     *     
     */
    public void setAEB(JAXBElement<AEBType> value) {
        this.aeb = ((JAXBElement<AEBType> ) value);
    }

    /**
     * Gets the value of the aed property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AEDType }{@code >}
     *     
     */
    public JAXBElement<AEDType> getAED() {
        return aed;
    }

    /**
     * Sets the value of the aed property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AEDType }{@code >}
     *     
     */
    public void setAED(JAXBElement<AEDType> value) {
        this.aed = ((JAXBElement<AEDType> ) value);
    }

    /**
     * Gets the value of the aee property.
     * 
     * @return
     *     possible object is
     *     {@link AEEType }
     *     
     */
    public AEEType getAEE() {
        return aee;
    }

    /**
     * Sets the value of the aee property.
     * 
     * @param value
     *     allowed object is
     *     {@link AEEType }
     *     
     */
    public void setAEE(AEEType value) {
        this.aee = value;
    }

    /**
     * Gets the value of the aeg property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AEGType }{@code >}
     *     
     */
    public JAXBElement<AEGType> getAEG() {
        return aeg;
    }

    /**
     * Sets the value of the aeg property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AEGType }{@code >}
     *     
     */
    public void setAEG(JAXBElement<AEGType> value) {
        this.aeg = ((JAXBElement<AEGType> ) value);
    }

    /**
     * Gets the value of the aej property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AEJType }{@code >}
     *     
     */
    public JAXBElement<AEJType> getAEJ() {
        return aej;
    }

    /**
     * Sets the value of the aej property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AEJType }{@code >}
     *     
     */
    public void setAEJ(JAXBElement<AEJType> value) {
        this.aej = ((JAXBElement<AEJType> ) value);
    }

    /**
     * Gets the value of the aeks property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AEKSType }{@code >}
     *     
     */
    public JAXBElement<AEKSType> getAEKS() {
        return aeks;
    }

    /**
     * Sets the value of the aeks property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AEKSType }{@code >}
     *     
     */
    public void setAEKS(JAXBElement<AEKSType> value) {
        this.aeks = ((JAXBElement<AEKSType> ) value);
    }

    /**
     * Gets the value of the ael01 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getAEL01() {
        return ael01;
    }

    /**
     * Sets the value of the ael01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setAEL01(JAXBElement<Integer> value) {
        this.ael01 = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the aens property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AENSType }{@code >}
     *     
     */
    public JAXBElement<AENSType> getAENS() {
        return aens;
    }

    /**
     * Sets the value of the aens property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AENSType }{@code >}
     *     
     */
    public void setAENS(JAXBElement<AENSType> value) {
        this.aens = ((JAXBElement<AENSType> ) value);
    }

    /**
     * Gets the value of the aem property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AEMType }{@code >}
     *     
     */
    public JAXBElement<AEMType> getAEM() {
        return aem;
    }

    /**
     * Sets the value of the aem property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AEMType }{@code >}
     *     
     */
    public void setAEM(JAXBElement<AEMType> value) {
        this.aem = ((JAXBElement<AEMType> ) value);
    }

    /**
     * Gets the value of the aei property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AEIType }{@code >}
     *     
     */
    public JAXBElement<AEIType> getAEI() {
        return aei;
    }

    /**
     * Sets the value of the aei property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AEIType }{@code >}
     *     
     */
    public void setAEI(JAXBElement<AEIType> value) {
        this.aei = ((JAXBElement<AEIType> ) value);
    }

}
