//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 10:28:02 ÉÏÎç CST 
//


package jdo.sta.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AA" type="{}AAType"/>
 *         &lt;element name="AB" type="{}ABType"/>
 *         &lt;element name="AC" type="{}ACType" minOccurs="0"/>
 *         &lt;element name="AE" type="{}AEType"/>
 *         &lt;element name="AD" type="{}ADType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AType", propOrder = {
    "aa",
    "ab",
    "ac",
    "ae",
    "ad"
})
public class AType {

    @XmlElement(name = "AA", required = true)
    protected AAType aa;
    @XmlElement(name = "AB", required = true)
    protected ABType ab;
    @XmlElementRef(name = "AC", type = JAXBElement.class)
    protected JAXBElement<ACType> ac;
    @XmlElement(name = "AE", required = true)
    protected AEType ae;
    @XmlElement(name = "AD", required = true)
    protected ADType ad;

    /**
     * Gets the value of the aa property.
     * 
     * @return
     *     possible object is
     *     {@link AAType }
     *     
     */
    public AAType getAA() {
        return aa;
    }

    /**
     * Sets the value of the aa property.
     * 
     * @param value
     *     allowed object is
     *     {@link AAType }
     *     
     */
    public void setAA(AAType value) {
        this.aa = value;
    }

    /**
     * Gets the value of the ab property.
     * 
     * @return
     *     possible object is
     *     {@link ABType }
     *     
     */
    public ABType getAB() {
        return ab;
    }

    /**
     * Sets the value of the ab property.
     * 
     * @param value
     *     allowed object is
     *     {@link ABType }
     *     
     */
    public void setAB(ABType value) {
        this.ab = value;
    }

    /**
     * Gets the value of the ac property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ACType }{@code >}
     *     
     */
    public JAXBElement<ACType> getAC() {
        return ac;
    }

    /**
     * Sets the value of the ac property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ACType }{@code >}
     *     
     */
    public void setAC(JAXBElement<ACType> value) {
        this.ac = ((JAXBElement<ACType> ) value);
    }

    /**
     * Gets the value of the ae property.
     * 
     * @return
     *     possible object is
     *     {@link AEType }
     *     
     */
    public AEType getAE() {
        return ae;
    }

    /**
     * Sets the value of the ae property.
     * 
     * @param value
     *     allowed object is
     *     {@link AEType }
     *     
     */
    public void setAE(AEType value) {
        this.ae = value;
    }

    /**
     * Gets the value of the ad property.
     * 
     * @return
     *     possible object is
     *     {@link ADType }
     *     
     */
    public ADType getAD() {
        return ad;
    }

    /**
     * Sets the value of the ad property.
     * 
     * @param value
     *     allowed object is
     *     {@link ADType }
     *     
     */
    public void setAD(ADType value) {
        this.ad = value;
    }

}
