//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 10:28:02 ÉÏÎç CST 
//


package jdo.sta.bean;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bbdmDic.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="bbdmDic">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="B_WT4-2012"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "bbdmDic")
@XmlEnum
public enum BbdmDic {

    @XmlEnumValue("B_WT4-2012")
    B_WT_4_2012("B_WT4-2012");
    private final java.lang.String value;

    BbdmDic(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static BbdmDic fromValue(java.lang.String v) {
        for (BbdmDic c: BbdmDic.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
