//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 10:28:02 ÉÏÎç CST 
//


package jdo.sta.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jdo.sta.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ABHTypeABH0201C_QNAME = new QName("", "ABH0201C");
    private final static QName _ABHTypeABH0202C_QNAME = new QName("", "ABH0202C");
    private final static QName _ABHTypeABH03C_QNAME = new QName("", "ABH03C");
    private final static QName _ABHTypeABH0203C_QNAME = new QName("", "ABH0203C");
    private final static QName _ABHTypeABH01C_QNAME = new QName("", "ABH01C");
    private final static QName _ZBTypeZB09_QNAME = new QName("", "ZB09");
    private final static QName _ZBTypeZB10_QNAME = new QName("", "ZB10");
    private final static QName _ZBTypeZB08_QNAME = new QName("", "ZB08");
    private final static QName _AENTypeAEN02N_QNAME = new QName("", "AEN02N");
    private final static QName _AENTypeAEN02C_QNAME = new QName("", "AEN02C");
    private final static QName _ATypeAC_QNAME = new QName("", "AC");
    private final static QName _ADATypeADA26_QNAME = new QName("", "ADA26");
    private final static QName _ADATypeADA08_QNAME = new QName("", "ADA08");
    private final static QName _ADATypeADA09_QNAME = new QName("", "ADA09");
    private final static QName _ADATypeADA27_QNAME = new QName("", "ADA27");
    private final static QName _ADATypeADA06_QNAME = new QName("", "ADA06");
    private final static QName _ADATypeADA24_QNAME = new QName("", "ADA24");
    private final static QName _ADATypeADA25_QNAME = new QName("", "ADA25");
    private final static QName _ADATypeADA07_QNAME = new QName("", "ADA07");
    private final static QName _ADATypeADA04_QNAME = new QName("", "ADA04");
    private final static QName _ADATypeADA05_QNAME = new QName("", "ADA05");
    private final static QName _ADATypeADA02_QNAME = new QName("", "ADA02");
    private final static QName _ADATypeADA28_QNAME = new QName("", "ADA28");
    private final static QName _ADATypeADA29_QNAME = new QName("", "ADA29");
    private final static QName _ADATypeADA03_QNAME = new QName("", "ADA03");
    private final static QName _ADATypeADA0101_QNAME = new QName("", "ADA0101");
    private final static QName _ADATypeADA12_QNAME = new QName("", "ADA12");
    private final static QName _ADATypeADA30_QNAME = new QName("", "ADA30");
    private final static QName _ADATypeADA11_QNAME = new QName("", "ADA11");
    private final static QName _ADATypeADA10_QNAME = new QName("", "ADA10");
    private final static QName _ADATypeADA34_QNAME = new QName("", "ADA34");
    private final static QName _ADATypeADA33_QNAME = new QName("", "ADA33");
    private final static QName _ADATypeADA32_QNAME = new QName("", "ADA32");
    private final static QName _ADATypeADA31_QNAME = new QName("", "ADA31");
    private final static QName _ADATypeADA35_QNAME = new QName("", "ADA35");
    private final static QName _ADATypeADA36_QNAME = new QName("", "ADA36");
    private final static QName _ADATypeADA37_QNAME = new QName("", "ADA37");
    private final static QName _ADATypeADA38_QNAME = new QName("", "ADA38");
    private final static QName _ADATypeADA39_QNAME = new QName("", "ADA39");
    private final static QName _ADATypeADA13_QNAME = new QName("", "ADA13");
    private final static QName _ADATypeADA15_QNAME = new QName("", "ADA15");
    private final static QName _ADATypeADA21_QNAME = new QName("", "ADA21");
    private final static QName _ADATypeADA20_QNAME = new QName("", "ADA20");
    private final static QName _ADATypeADA41_QNAME = new QName("", "ADA41");
    private final static QName _ADATypeADA23_QNAME = new QName("", "ADA23");
    private final static QName _ADATypeADA40_QNAME = new QName("", "ADA40");
    private final static QName _ADATypeADA22_QNAME = new QName("", "ADA22");
    private final static QName _ADATypeADA43_QNAME = new QName("", "ADA43");
    private final static QName _ADATypeADA42_QNAME = new QName("", "ADA42");
    private final static QName _ADATypeADA44_QNAME = new QName("", "ADA44");
    private final static QName _AEETypeAEE04_QNAME = new QName("", "AEE04");
    private final static QName _AEETypeAEE05_QNAME = new QName("", "AEE05");
    private final static QName _AEETypeAEE01_QNAME = new QName("", "AEE01");
    private final static QName _AEETypeAEE10_QNAME = new QName("", "AEE10");
    private final static QName _AEETypeAEE11_QNAME = new QName("", "AEE11");
    private final static QName _AEETypeAEE08_QNAME = new QName("", "AEE08");
    private final static QName _AEETypeAEE07_QNAME = new QName("", "AEE07");
    private final static QName _AEETypeAEE09_QNAME = new QName("", "AEE09");
    private final static QName _AACTypeAAC03_QNAME = new QName("", "AAC03");
    private final static QName _ABATypeABA01C_QNAME = new QName("", "ABA01C");
    private final static QName _ABATypeABA01N_QNAME = new QName("", "ABA01N");
    private final static QName _ABGTypeABG01C_QNAME = new QName("", "ABG01C");
    private final static QName _ABGTypeABG01N_QNAME = new QName("", "ABG01N");
    private final static QName _AEDTypeAED02_QNAME = new QName("", "AED02");
    private final static QName _AEDTypeAED03_QNAME = new QName("", "AED03");
    private final static QName _AEDTypeAED04_QNAME = new QName("", "AED04");
    private final static QName _AEDTypeAED01C_QNAME = new QName("", "AED01C");
    private final static QName _ACATypeACA09S_QNAME = new QName("", "ACA09S");
    private final static QName _ACATypeACA08_QNAME = new QName("", "ACA08");
    private final static QName _ACATypeACA07C_QNAME = new QName("", "ACA07C");
    private final static QName _ACATypeACA10C_QNAME = new QName("", "ACA10C");
    private final static QName _ACATypeACA06C_QNAME = new QName("", "ACA06C");
    private final static QName _ACATypeACA03_QNAME = new QName("", "ACA03");
    private final static QName _ACATypeACA04_QNAME = new QName("", "ACA04");
    private final static QName _AEGTypeAEG06_QNAME = new QName("", "AEG06");
    private final static QName _AEGTypeAEG05_QNAME = new QName("", "AEG05");
    private final static QName _AEGTypeAEG08_QNAME = new QName("", "AEG08");
    private final static QName _AEGTypeAEG07_QNAME = new QName("", "AEG07");
    private final static QName _AEGTypeAEG01C_QNAME = new QName("", "AEG01C");
    private final static QName _AEGTypeAEG02C_QNAME = new QName("", "AEG02C");
    private final static QName _AEGTypeAEG04_QNAME = new QName("", "AEG04");
    private final static QName _AEMTypeAEM02_QNAME = new QName("", "AEM02");
    private final static QName _AEMTypeAEM04_QNAME = new QName("", "AEM04");
    private final static QName _AABTypeAAB03_QNAME = new QName("", "AAB03");
    private final static QName _ABFTypeABF02C_QNAME = new QName("", "ABF02C");
    private final static QName _ABFTypeABF01C_QNAME = new QName("", "ABF01C");
    private final static QName _ABFTypeABF03C_QNAME = new QName("", "ABF03C");
    private final static QName _ABFTypeABF01N_QNAME = new QName("", "ABF01N");
    private final static QName _ABFTypeABF04_QNAME = new QName("", "ABF04");
    private final static QName _AEBTypeAEB01_QNAME = new QName("", "AEB01");
    private final static QName _ACTypeACAS_QNAME = new QName("", "ACAS");
    private final static QName _AAATypeAAA13C_QNAME = new QName("", "AAA13C");
    private final static QName _AAATypeAAA21C_QNAME = new QName("", "AAA21C");
    private final static QName _AAATypeAAA15_QNAME = new QName("", "AAA15");
    private final static QName _AAATypeAAA36C_QNAME = new QName("", "AAA36C");
    private final static QName _AAATypeAAA23C_QNAME = new QName("", "AAA23C");
    private final static QName _AAATypeAAA12_QNAME = new QName("", "AAA12");
    private final static QName _AAATypeAAA11_QNAME = new QName("", "AAA11");
    private final static QName _AAATypeAAA10_QNAME = new QName("", "AAA10");
    private final static QName _AAATypeAAA19_QNAME = new QName("", "AAA19");
    private final static QName _AAATypeAAA09_QNAME = new QName("", "AAA09");
    private final static QName _AAATypeAAA07_QNAME = new QName("", "AAA07");
    private final static QName _AAATypeAAA20_QNAME = new QName("", "AAA20");
    private final static QName _AAATypeAAA05C_QNAME = new QName("", "AAA05C");
    private final static QName _AAATypeAAA04_QNAME = new QName("", "AAA04");
    private final static QName _AAATypeAAA33C_QNAME = new QName("", "AAA33C");
    private final static QName _AAATypeAAA42_QNAME = new QName("", "AAA42");
    private final static QName _AAATypeAAA14C_QNAME = new QName("", "AAA14C");
    private final static QName _AAATypeAAA40_QNAME = new QName("", "AAA40");
    private final static QName _AAATypeAAA44_QNAME = new QName("", "AAA44");
    private final static QName _AAATypeAAA25_QNAME = new QName("", "AAA25");
    private final static QName _AAATypeAAA43_QNAME = new QName("", "AAA43");
    private final static QName _AAATypeAAA46_QNAME = new QName("", "AAA46");
    private final static QName _AAATypeAAA27_QNAME = new QName("", "AAA27");
    private final static QName _AAATypeAAA45_QNAME = new QName("", "AAA45");
    private final static QName _AAATypeAAA22_QNAME = new QName("", "AAA22");
    private final static QName _AAATypeAAA48_QNAME = new QName("", "AAA48");
    private final static QName _AAATypeAAA17C_QNAME = new QName("", "AAA17C");
    private final static QName _AAATypeAAA47_QNAME = new QName("", "AAA47");
    private final static QName _AAATypeAAA24_QNAME = new QName("", "AAA24");
    private final static QName _AAATypeAAA49_QNAME = new QName("", "AAA49");
    private final static QName _AAATypeAAA06C_QNAME = new QName("", "AAA06C");
    private final static QName _AAATypeAAA50_QNAME = new QName("", "AAA50");
    private final static QName _AAATypeAAA51_QNAME = new QName("", "AAA51");
    private final static QName _AEJTypeAEJ06_QNAME = new QName("", "AEJ06");
    private final static QName _AEJTypeAEJ03_QNAME = new QName("", "AEJ03");
    private final static QName _AEJTypeAEJ02_QNAME = new QName("", "AEJ02");
    private final static QName _AEJTypeAEJ05_QNAME = new QName("", "AEJ05");
    private final static QName _AEJTypeAEJ04_QNAME = new QName("", "AEJ04");
    private final static QName _AEJTypeAEJ01_QNAME = new QName("", "AEJ01");
    private final static QName _AETypeAEKS_QNAME = new QName("", "AEKS");
    private final static QName _AETypeAEB_QNAME = new QName("", "AEB");
    private final static QName _AETypeAENS_QNAME = new QName("", "AENS");
    private final static QName _AETypeAEM_QNAME = new QName("", "AEM");
    private final static QName _AETypeAEI_QNAME = new QName("", "AEI");
    private final static QName _AETypeAEJ_QNAME = new QName("", "AEJ");
    private final static QName _AETypeAED_QNAME = new QName("", "AED");
    private final static QName _AETypeAEL01_QNAME = new QName("", "AEL01");
    private final static QName _AETypeAEG_QNAME = new QName("", "AEG");
    private final static QName _AEITypeAEI10_QNAME = new QName("", "AEI10");
    private final static QName _AEITypeAEI01C_QNAME = new QName("", "AEI01C");
    private final static QName _AEITypeAEI08_QNAME = new QName("", "AEI08");
    private final static QName _AEITypeAEI09_QNAME = new QName("", "AEI09");
    private final static QName _AATypeAAD01C_QNAME = new QName("", "AAD01C");
    private final static QName _ABTypeABA_QNAME = new QName("", "ABA");
    private final static QName _ABTypeABH_QNAME = new QName("", "ABH");
    private final static QName _ABTypeABG_QNAME = new QName("", "ABG");
    private final static QName _ABTypeABF_QNAME = new QName("", "ABF");
    private final static QName _ABTypeABDS_QNAME = new QName("", "ABDS");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jdo.sta.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ACA0902CType }
     * 
     */
    public ACA0902CType createACA0902CType() {
        return new ACA0902CType();
    }

    /**
     * Create an instance of {@link AENType }
     * 
     */
    public AENType createAENType() {
        return new AENType();
    }

    /**
     * Create an instance of {@link AAA26CType }
     * 
     */
    public AAA26CType createAAA26CType() {
        return new AAA26CType();
    }

    /**
     * Create an instance of {@link ABD02CType }
     * 
     */
    public ABD02CType createABD02CType() {
        return new ABD02CType();
    }

    /**
     * Create an instance of {@link AAB06CType }
     * 
     */
    public AAB06CType createAAB06CType() {
        return new AAB06CType();
    }

    /**
     * Create an instance of {@link ZB03Type }
     * 
     */
    public ZB03Type createZB03Type() {
        return new ZB03Type();
    }

    /**
     * Create an instance of {@link ACA09SType }
     * 
     */
    public ACA09SType createACA09SType() {
        return new ACA09SType();
    }

    /**
     * Create an instance of {@link ZA01CType }
     * 
     */
    public ZA01CType createZA01CType() {
        return new ZA01CType();
    }

    /**
     * Create an instance of {@link AAB02CType }
     * 
     */
    public AAB02CType createAAB02CType() {
        return new AAB02CType();
    }

    /**
     * Create an instance of {@link ABDSType }
     * 
     */
    public ABDSType createABDSType() {
        return new ABDSType();
    }

    /**
     * Create an instance of {@link AABType }
     * 
     */
    public AABType createAABType() {
        return new AABType();
    }

    /**
     * Create an instance of {@link ABDType }
     * 
     */
    public ABDType createABDType() {
        return new ABDType();
    }

    /**
     * Create an instance of {@link ZB02Type }
     * 
     */
    public ZB02Type createZB02Type() {
        return new ZB02Type();
    }

    /**
     * Create an instance of {@link AEBType }
     * 
     */
    public AEBType createAEBType() {
        return new AEBType();
    }

    /**
     * Create an instance of {@link CASES }
     * 
     */
    public CASES createCASES() {
        return new CASES();
    }

    /**
     * Create an instance of {@link AEType }
     * 
     */
    public AEType createAEType() {
        return new AEType();
    }

    /**
     * Create an instance of {@link AEIType }
     * 
     */
    public AEIType createAEIType() {
        return new AEIType();
    }

    /**
     * Create an instance of {@link ABF03CType }
     * 
     */
    public ABF03CType createABF03CType() {
        return new ABF03CType();
    }

    /**
     * Create an instance of {@link AAA35Type }
     * 
     */
    public AAA35Type createAAA35Type() {
        return new AAA35Type();
    }

    /**
     * Create an instance of {@link Minute }
     * 
     */
    public Minute createMinute() {
        return new Minute();
    }

    /**
     * Create an instance of {@link OneORtwoType }
     * 
     */
    public OneORtwoType createOneORtwoType() {
        return new OneORtwoType();
    }

    /**
     * Create an instance of {@link AAA16CType }
     * 
     */
    public AAA16CType createAAA16CType() {
        return new AAA16CType();
    }

    /**
     * Create an instance of {@link ZA02CType }
     * 
     */
    public ZA02CType createZA02CType() {
        return new ZA02CType();
    }

    /**
     * Create an instance of {@link AType }
     * 
     */
    public AType createAType() {
        return new AType();
    }

    /**
     * Create an instance of {@link AEEType }
     * 
     */
    public AEEType createAEEType() {
        return new AEEType();
    }

    /**
     * Create an instance of {@link AACType }
     * 
     */
    public AACType createAACType() {
        return new AACType();
    }

    /**
     * Create an instance of {@link BirthedDays }
     * 
     */
    public BirthedDays createBirthedDays() {
        return new BirthedDays();
    }

    /**
     * Create an instance of {@link ADType }
     * 
     */
    public ADType createADType() {
        return new ADType();
    }

    /**
     * Create an instance of {@link AEKType }
     * 
     */
    public AEKType createAEKType() {
        return new AEKType();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public Email createEmail() {
        return new Email();
    }

    /**
     * Create an instance of {@link ABC02CType }
     * 
     */
    public ABC02CType createABC02CType() {
        return new ABC02CType();
    }

    /**
     * Create an instance of {@link NotNullStringType }
     * 
     */
    public NotNullStringType createNotNullStringType() {
        return new NotNullStringType();
    }

    /**
     * Create an instance of {@link ABE02CType }
     * 
     */
    public ABE02CType createABE02CType() {
        return new ABE02CType();
    }

    /**
     * Create an instance of {@link ACA07CType }
     * 
     */
    public ACA07CType createACA07CType() {
        return new ACA07CType();
    }

    /**
     * Create an instance of {@link Age }
     * 
     */
    public Age createAge() {
        return new Age();
    }

    /**
     * Create an instance of {@link AENSType }
     * 
     */
    public AENSType createAENSType() {
        return new AENSType();
    }

    /**
     * Create an instance of {@link AAA05CType }
     * 
     */
    public AAA05CType createAAA05CType() {
        return new AAA05CType();
    }

    /**
     * Create an instance of {@link AAAType }
     * 
     */
    public AAAType createAAAType() {
        return new AAAType();
    }

    /**
     * Create an instance of {@link AAA23CType }
     * 
     */
    public AAA23CType createAAA23CType() {
        return new AAA23CType();
    }

    /**
     * Create an instance of {@link AEI01CType }
     * 
     */
    public AEI01CType createAEI01CType() {
        return new AEI01CType();
    }

    /**
     * Create an instance of {@link ACASType }
     * 
     */
    public ACASType createACASType() {
        return new ACASType();
    }

    /**
     * Create an instance of {@link ABType }
     * 
     */
    public ABType createABType() {
        return new ABType();
    }

    /**
     * Create an instance of {@link AAA06CType }
     * 
     */
    public AAA06CType createAAA06CType() {
        return new AAA06CType();
    }

    /**
     * Create an instance of {@link CASEType }
     * 
     */
    public CASEType createCASEType() {
        return new CASEType();
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link AEG02CType }
     * 
     */
    public AEG02CType createAEG02CType() {
        return new AEG02CType();
    }

    /**
     * Create an instance of {@link ZType }
     * 
     */
    public ZType createZType() {
        return new ZType();
    }

    /**
     * Create an instance of {@link ACA09Type }
     * 
     */
    public ACA09Type createACA09Type() {
        return new ACA09Type();
    }

    /**
     * Create an instance of {@link ABAType }
     * 
     */
    public ABAType createABAType() {
        return new ABAType();
    }

    /**
     * Create an instance of {@link AAA02CType }
     * 
     */
    public AAA02CType createAAA02CType() {
        return new AAA02CType();
    }

    /**
     * Create an instance of {@link AAC02CType }
     * 
     */
    public AAC02CType createAAC02CType() {
        return new AAC02CType();
    }

    /**
     * Create an instance of {@link AEDType }
     * 
     */
    public AEDType createAEDType() {
        return new AEDType();
    }

    /**
     * Create an instance of {@link ACAType }
     * 
     */
    public ACAType createACAType() {
        return new ACAType();
    }

    /**
     * Create an instance of {@link Morethan0Prize }
     * 
     */
    public Morethan0Prize createMorethan0Prize() {
        return new Morethan0Prize();
    }

    /**
     * Create an instance of {@link AEMType }
     * 
     */
    public AEMType createAEMType() {
        return new AEMType();
    }

    /**
     * Create an instance of {@link Min1Integer }
     * 
     */
    public Min1Integer createMin1Integer() {
        return new Min1Integer();
    }

    /**
     * Create an instance of {@link ABF02CType }
     * 
     */
    public ABF02CType createABF02CType() {
        return new ABF02CType();
    }

    /**
     * Create an instance of {@link Int1999999 }
     * 
     */
    public Int1999999 createInt1999999() {
        return new Int1999999();
    }

    /**
     * Create an instance of {@link ZKKBDM }
     * 
     */
    public ZKKBDM createZKKBDM() {
        return new ZKKBDM();
    }

    /**
     * Create an instance of {@link ACA01CType }
     * 
     */
    public ACA01CType createACA01CType() {
        return new ACA01CType();
    }

    /**
     * Create an instance of {@link IDCard }
     * 
     */
    public IDCard createIDCard() {
        return new IDCard();
    }

    /**
     * Create an instance of {@link jdo.sta.bean.String }
     * 
     */
    public jdo.sta.bean.String createString() {
        return new jdo.sta.bean.String();
    }

    /**
     * Create an instance of {@link AEJType }
     * 
     */
    public AEJType createAEJType() {
        return new AEJType();
    }

    /**
     * Create an instance of {@link ABHType }
     * 
     */
    public ABHType createABHType() {
        return new ABHType();
    }

    /**
     * Create an instance of {@link AEKSType }
     * 
     */
    public AEKSType createAEKSType() {
        return new AEKSType();
    }

    /**
     * Create an instance of {@link ZBType }
     * 
     */
    public ZBType createZBType() {
        return new ZBType();
    }

    /**
     * Create an instance of {@link ZB01CType }
     * 
     */
    public ZB01CType createZB01CType() {
        return new ZB01CType();
    }

    /**
     * Create an instance of {@link NonNegativeInteger }
     * 
     */
    public NonNegativeInteger createNonNegativeInteger() {
        return new NonNegativeInteger();
    }

    /**
     * Create an instance of {@link ABC03CType }
     * 
     */
    public ABC03CType createABC03CType() {
        return new ABC03CType();
    }

    /**
     * Create an instance of {@link ADAType }
     * 
     */
    public ADAType createADAType() {
        return new ADAType();
    }

    /**
     * Create an instance of {@link Morethan0Days }
     * 
     */
    public Morethan0Days createMorethan0Days() {
        return new Morethan0Days();
    }

    /**
     * Create an instance of {@link MobilePhone }
     * 
     */
    public MobilePhone createMobilePhone() {
        return new MobilePhone();
    }

    /**
     * Create an instance of {@link ABGType }
     * 
     */
    public ABGType createABGType() {
        return new ABGType();
    }

    /**
     * Create an instance of {@link TimeStamp }
     * 
     */
    public TimeStamp createTimeStamp() {
        return new TimeStamp();
    }

    /**
     * Create an instance of {@link AEGType }
     * 
     */
    public AEGType createAEGType() {
        return new AEGType();
    }

    /**
     * Create an instance of {@link ZAType }
     * 
     */
    public ZAType createZAType() {
        return new ZAType();
    }

    /**
     * Create an instance of {@link ABCType }
     * 
     */
    public ABCType createABCType() {
        return new ABCType();
    }

    /**
     * Create an instance of {@link AED01CType }
     * 
     */
    public AED01CType createAED01CType() {
        return new AED01CType();
    }

    /**
     * Create an instance of {@link AAA18CType }
     * 
     */
    public AAA18CType createAAA18CType() {
        return new AAA18CType();
    }

    /**
     * Create an instance of {@link ABF01CType }
     * 
     */
    public ABF01CType createABF01CType() {
        return new ABF01CType();
    }

    /**
     * Create an instance of {@link Prize }
     * 
     */
    public Prize createPrize() {
        return new Prize();
    }

    /**
     * Create an instance of {@link AAA13CType }
     * 
     */
    public AAA13CType createAAA13CType() {
        return new AAA13CType();
    }

    /**
     * Create an instance of {@link AEG01CType }
     * 
     */
    public AEG01CType createAEG01CType() {
        return new AEG01CType();
    }

    /**
     * Create an instance of {@link AAA08CType }
     * 
     */
    public AAA08CType createAAA08CType() {
        return new AAA08CType();
    }

    /**
     * Create an instance of {@link ABFType }
     * 
     */
    public ABFType createABFType() {
        return new ABFType();
    }

    /**
     * Create an instance of {@link ACType }
     * 
     */
    public ACType createACType() {
        return new ACType();
    }

    /**
     * Create an instance of {@link ZipCode }
     * 
     */
    public ZipCode createZipCode() {
        return new ZipCode();
    }

    /**
     * Create an instance of {@link ACA06CType }
     * 
     */
    public ACA06CType createACA06CType() {
        return new ACA06CType();
    }

    /**
     * Create an instance of {@link AAType }
     * 
     */
    public AAType createAAType() {
        return new AAType();
    }

    /**
     * Create an instance of {@link ACA0903CType }
     * 
     */
    public ACA0903CType createACA0903CType() {
        return new ACA0903CType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ABH0201C", scope = ABHType.class)
    public JAXBElement<java.lang.String> createABHTypeABH0201C(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_ABHTypeABH0201C_QNAME, java.lang.String.class, ABHType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ABH0202C", scope = ABHType.class)
    public JAXBElement<java.lang.String> createABHTypeABH0202C(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_ABHTypeABH0202C_QNAME, java.lang.String.class, ABHType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ABH03C", scope = ABHType.class)
    public JAXBElement<java.lang.String> createABHTypeABH03C(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_ABHTypeABH03C_QNAME, java.lang.String.class, ABHType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ABH0203C", scope = ABHType.class)
    public JAXBElement<java.lang.String> createABHTypeABH0203C(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_ABHTypeABH0203C_QNAME, java.lang.String.class, ABHType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OneORtwoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ABH01C", scope = ABHType.class)
    public JAXBElement<OneORtwoType> createABHTypeABH01C(OneORtwoType value) {
        return new JAXBElement<OneORtwoType>(_ABHTypeABH01C_QNAME, OneORtwoType.class, ABHType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MobilePhone }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ZB09", scope = ZBType.class)
    public JAXBElement<MobilePhone> createZBTypeZB09(MobilePhone value) {
        return new JAXBElement<MobilePhone>(_ZBTypeZB09_QNAME, MobilePhone.class, ZBType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ZB10", scope = ZBType.class)
    public JAXBElement<jdo.sta.bean.String> createZBTypeZB10(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_ZBTypeZB10_QNAME, jdo.sta.bean.String.class, ZBType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Email }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ZB08", scope = ZBType.class)
    public JAXBElement<Email> createZBTypeZB08(Email value) {
        return new JAXBElement<Email>(_ZBTypeZB08_QNAME, Email.class, ZBType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEN02N", scope = AENType.class)
    public JAXBElement<jdo.sta.bean.String> createAENTypeAEN02N(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AENTypeAEN02N_QNAME, jdo.sta.bean.String.class, AENType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEN02C", scope = AENType.class)
    public JAXBElement<jdo.sta.bean.String> createAENTypeAEN02C(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AENTypeAEN02C_QNAME, jdo.sta.bean.String.class, AENType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ACType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AC", scope = AType.class)
    public JAXBElement<ACType> createATypeAC(ACType value) {
        return new JAXBElement<ACType>(_ATypeAC_QNAME, ACType.class, AType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA26", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA26(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA26_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA08", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA08(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA08_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA09", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA09(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA09_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA27", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA27(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA27_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA06", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA06(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA06_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA24", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA24(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA24_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA25", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA25(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA25_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA07", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA07(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA07_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA04", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA04(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA04_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA05", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA05(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA05_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA02", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA02(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA02_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA28", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA28(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA28_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA29", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA29(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA29_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA03", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA03(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA03_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA0101", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA0101(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA0101_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA12", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA12(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA12_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA30", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA30(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA30_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA11", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA11(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA11_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA10", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA10(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA10_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA34", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA34(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA34_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA33", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA33(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA33_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA32", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA32(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA32_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA31", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA31(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA31_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA35", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA35(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA35_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA36", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA36(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA36_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA37", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA37(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA37_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA38", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA38(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA38_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA39", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA39(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA39_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA13", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA13(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA13_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA15", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA15(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA15_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA21", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA21(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA21_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA20", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA20(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA20_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA41", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA41(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA41_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA23", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA23(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA23_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA40", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA40(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA40_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA22", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA22(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA22_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA43", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA43(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA43_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA42", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA42(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA42_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADA44", scope = ADAType.class)
    public JAXBElement<Prize> createADATypeADA44(Prize value) {
        return new JAXBElement<Prize>(_ADATypeADA44_QNAME, Prize.class, ADAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEE04", scope = AEEType.class)
    public JAXBElement<jdo.sta.bean.String> createAEETypeAEE04(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AEETypeAEE04_QNAME, jdo.sta.bean.String.class, AEEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEE05", scope = AEEType.class)
    public JAXBElement<jdo.sta.bean.String> createAEETypeAEE05(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AEETypeAEE05_QNAME, jdo.sta.bean.String.class, AEEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEE01", scope = AEEType.class)
    public JAXBElement<jdo.sta.bean.String> createAEETypeAEE01(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AEETypeAEE01_QNAME, jdo.sta.bean.String.class, AEEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEE10", scope = AEEType.class)
    public JAXBElement<jdo.sta.bean.String> createAEETypeAEE10(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AEETypeAEE10_QNAME, jdo.sta.bean.String.class, AEEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEE11", scope = AEEType.class)
    public JAXBElement<java.lang.String> createAEETypeAEE11(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_AEETypeAEE11_QNAME, java.lang.String.class, AEEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEE08", scope = AEEType.class)
    public JAXBElement<jdo.sta.bean.String> createAEETypeAEE08(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AEETypeAEE08_QNAME, jdo.sta.bean.String.class, AEEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEE07", scope = AEEType.class)
    public JAXBElement<jdo.sta.bean.String> createAEETypeAEE07(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AEETypeAEE07_QNAME, jdo.sta.bean.String.class, AEEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEE09", scope = AEEType.class)
    public JAXBElement<jdo.sta.bean.String> createAEETypeAEE09(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AEETypeAEE09_QNAME, jdo.sta.bean.String.class, AEEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAC03", scope = AACType.class)
    public JAXBElement<jdo.sta.bean.String> createAACTypeAAC03(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AACTypeAAC03_QNAME, jdo.sta.bean.String.class, AACType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ABA01C", scope = ABAType.class)
    public JAXBElement<jdo.sta.bean.String> createABATypeABA01C(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_ABATypeABA01C_QNAME, jdo.sta.bean.String.class, ABAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ABA01N", scope = ABAType.class)
    public JAXBElement<jdo.sta.bean.String> createABATypeABA01N(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_ABATypeABA01N_QNAME, jdo.sta.bean.String.class, ABAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ABG01C", scope = ABGType.class)
    public JAXBElement<jdo.sta.bean.String> createABGTypeABG01C(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_ABGTypeABG01C_QNAME, jdo.sta.bean.String.class, ABGType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ABG01N", scope = ABGType.class)
    public JAXBElement<jdo.sta.bean.String> createABGTypeABG01N(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_ABGTypeABG01N_QNAME, jdo.sta.bean.String.class, ABGType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AED02", scope = AEDType.class)
    public JAXBElement<jdo.sta.bean.String> createAEDTypeAED02(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AEDTypeAED02_QNAME, jdo.sta.bean.String.class, AEDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AED03", scope = AEDType.class)
    public JAXBElement<jdo.sta.bean.String> createAEDTypeAED03(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AEDTypeAED03_QNAME, jdo.sta.bean.String.class, AEDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Date }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AED04", scope = AEDType.class)
    public JAXBElement<Date> createAEDTypeAED04(Date value) {
        return new JAXBElement<Date>(_AEDTypeAED04_QNAME, Date.class, AEDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AED01CType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AED01C", scope = AEDType.class)
    public JAXBElement<AED01CType> createAEDTypeAED01C(AED01CType value) {
        return new JAXBElement<AED01CType>(_AEDTypeAED01C_QNAME, AED01CType.class, AEDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ACA09SType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACA09S", scope = ACAType.class)
    public JAXBElement<ACA09SType> createACATypeACA09S(ACA09SType value) {
        return new JAXBElement<ACA09SType>(_ACATypeACA09S_QNAME, ACA09SType.class, ACAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACA08", scope = ACAType.class)
    public JAXBElement<jdo.sta.bean.String> createACATypeACA08(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_ACATypeACA08_QNAME, jdo.sta.bean.String.class, ACAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ACA07CType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACA07C", scope = ACAType.class)
    public JAXBElement<ACA07CType> createACATypeACA07C(ACA07CType value) {
        return new JAXBElement<ACA07CType>(_ACATypeACA07C_QNAME, ACA07CType.class, ACAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACA10C", scope = ACAType.class)
    public JAXBElement<java.lang.String> createACATypeACA10C(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_ACATypeACA10C_QNAME, java.lang.String.class, ACAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ACA06CType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACA06C", scope = ACAType.class)
    public JAXBElement<ACA06CType> createACATypeACA06C(ACA06CType value) {
        return new JAXBElement<ACA06CType>(_ACATypeACA06C_QNAME, ACA06CType.class, ACAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACA03", scope = ACAType.class)
    public JAXBElement<jdo.sta.bean.String> createACATypeACA03(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_ACATypeACA03_QNAME, jdo.sta.bean.String.class, ACAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACA04", scope = ACAType.class)
    public JAXBElement<jdo.sta.bean.String> createACATypeACA04(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_ACATypeACA04_QNAME, jdo.sta.bean.String.class, ACAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEG06", scope = AEGType.class)
    public JAXBElement<Integer> createAEGTypeAEG06(Integer value) {
        return new JAXBElement<Integer>(_AEGTypeAEG06_QNAME, Integer.class, AEGType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEG05", scope = AEGType.class)
    public JAXBElement<Integer> createAEGTypeAEG05(Integer value) {
        return new JAXBElement<Integer>(_AEGTypeAEG05_QNAME, Integer.class, AEGType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEG08", scope = AEGType.class)
    public JAXBElement<Integer> createAEGTypeAEG08(Integer value) {
        return new JAXBElement<Integer>(_AEGTypeAEG08_QNAME, Integer.class, AEGType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEG07", scope = AEGType.class)
    public JAXBElement<Integer> createAEGTypeAEG07(Integer value) {
        return new JAXBElement<Integer>(_AEGTypeAEG07_QNAME, Integer.class, AEGType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AEG01CType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEG01C", scope = AEGType.class)
    public JAXBElement<AEG01CType> createAEGTypeAEG01C(AEG01CType value) {
        return new JAXBElement<AEG01CType>(_AEGTypeAEG01C_QNAME, AEG01CType.class, AEGType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AEG02CType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEG02C", scope = AEGType.class)
    public JAXBElement<AEG02CType> createAEGTypeAEG02C(AEG02CType value) {
        return new JAXBElement<AEG02CType>(_AEGTypeAEG02C_QNAME, AEG02CType.class, AEGType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEG04", scope = AEGType.class)
    public JAXBElement<Integer> createAEGTypeAEG04(Integer value) {
        return new JAXBElement<Integer>(_AEGTypeAEG04_QNAME, Integer.class, AEGType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEM02", scope = AEMType.class)
    public JAXBElement<jdo.sta.bean.String> createAEMTypeAEM02(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AEMTypeAEM02_QNAME, jdo.sta.bean.String.class, AEMType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEM04", scope = AEMType.class)
    public JAXBElement<jdo.sta.bean.String> createAEMTypeAEM04(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AEMTypeAEM04_QNAME, jdo.sta.bean.String.class, AEMType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAB03", scope = AABType.class)
    public JAXBElement<jdo.sta.bean.String> createAABTypeAAB03(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AABTypeAAB03_QNAME, jdo.sta.bean.String.class, AABType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ABF02CType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ABF02C", scope = ABFType.class)
    public JAXBElement<ABF02CType> createABFTypeABF02C(ABF02CType value) {
        return new JAXBElement<ABF02CType>(_ABFTypeABF02C_QNAME, ABF02CType.class, ABFType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ABF01C", scope = ABFType.class)
    public JAXBElement<jdo.sta.bean.String> createABFTypeABF01C(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_ABFTypeABF01C_QNAME, jdo.sta.bean.String.class, ABFType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ABF03CType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ABF03C", scope = ABFType.class)
    public JAXBElement<ABF03CType> createABFTypeABF03C(ABF03CType value) {
        return new JAXBElement<ABF03CType>(_ABFTypeABF03C_QNAME, ABF03CType.class, ABFType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ABF01N", scope = ABFType.class)
    public JAXBElement<jdo.sta.bean.String> createABFTypeABF01N(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_ABFTypeABF01N_QNAME, jdo.sta.bean.String.class, ABFType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ABF04", scope = ABFType.class)
    public JAXBElement<jdo.sta.bean.String> createABFTypeABF04(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_ABFTypeABF04_QNAME, jdo.sta.bean.String.class, ABFType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEB01", scope = AEBType.class)
    public JAXBElement<jdo.sta.bean.String> createAEBTypeAEB01(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AEBTypeAEB01_QNAME, jdo.sta.bean.String.class, AEBType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ACASType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACAS", scope = ACType.class)
    public JAXBElement<ACASType> createACTypeACAS(ACASType value) {
        return new JAXBElement<ACASType>(_ACTypeACAS_QNAME, ACASType.class, ACType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AAA13CType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA13C", scope = AAAType.class)
    public JAXBElement<AAA13CType> createAAATypeAAA13C(AAA13CType value) {
        return new JAXBElement<AAA13CType>(_AAATypeAAA13C_QNAME, AAA13CType.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZipCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA21C", scope = AAAType.class)
    public JAXBElement<ZipCode> createAAATypeAAA21C(ZipCode value) {
        return new JAXBElement<ZipCode>(_AAATypeAAA21C_QNAME, ZipCode.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA15", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA15(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA15_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA36C", scope = AAAType.class)
    public JAXBElement<java.lang.String> createAAATypeAAA36C(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_AAATypeAAA36C_QNAME, java.lang.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AAA23CType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA23C", scope = AAAType.class)
    public JAXBElement<AAA23CType> createAAATypeAAA23C(AAA23CType value) {
        return new JAXBElement<AAA23CType>(_AAATypeAAA23C_QNAME, AAA23CType.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA12", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA12(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA12_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA11", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA11(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA11_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA10", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA10(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA10_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA19", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA19(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA19_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA09", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA09(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA09_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IDCard }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA07", scope = AAAType.class)
    public JAXBElement<IDCard> createAAATypeAAA07(IDCard value) {
        return new JAXBElement<IDCard>(_AAATypeAAA07_QNAME, IDCard.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA20", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA20(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA20_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AAA05CType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA05C", scope = AAAType.class)
    public JAXBElement<AAA05CType> createAAATypeAAA05C(AAA05CType value) {
        return new JAXBElement<AAA05CType>(_AAATypeAAA05C_QNAME, AAA05CType.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Age }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA04", scope = AAAType.class)
    public JAXBElement<Age> createAAATypeAAA04(Age value) {
        return new JAXBElement<Age>(_AAATypeAAA04_QNAME, Age.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA33C", scope = AAAType.class)
    public JAXBElement<java.lang.String> createAAATypeAAA33C(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_AAATypeAAA33C_QNAME, java.lang.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA42", scope = AAAType.class)
    public JAXBElement<Integer> createAAATypeAAA42(Integer value) {
        return new JAXBElement<Integer>(_AAATypeAAA42_QNAME, Integer.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZipCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA14C", scope = AAAType.class)
    public JAXBElement<ZipCode> createAAATypeAAA14C(ZipCode value) {
        return new JAXBElement<ZipCode>(_AAATypeAAA14C_QNAME, ZipCode.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BirthedDays }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA40", scope = AAAType.class)
    public JAXBElement<BirthedDays> createAAATypeAAA40(BirthedDays value) {
        return new JAXBElement<BirthedDays>(_AAATypeAAA40_QNAME, BirthedDays.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA44", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA44(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA44_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA25", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA25(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA25_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA43", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA43(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA43_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA46", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA46(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA46_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA27", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA27(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA27_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA45", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA45(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA45_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA22", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA22(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA22_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA48", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA48(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA48_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZipCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA17C", scope = AAAType.class)
    public JAXBElement<ZipCode> createAAATypeAAA17C(ZipCode value) {
        return new JAXBElement<ZipCode>(_AAATypeAAA17C_QNAME, ZipCode.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA47", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA47(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA47_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA24", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA24(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA24_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA49", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA49(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA49_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AAA06CType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA06C", scope = AAAType.class)
    public JAXBElement<AAA06CType> createAAATypeAAA06C(AAA06CType value) {
        return new JAXBElement<AAA06CType>(_AAATypeAAA06C_QNAME, AAA06CType.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA50", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA50(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA50_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAA51", scope = AAAType.class)
    public JAXBElement<jdo.sta.bean.String> createAAATypeAAA51(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AAATypeAAA51_QNAME, jdo.sta.bean.String.class, AAAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Minute }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEJ06", scope = AEJType.class)
    public JAXBElement<Minute> createAEJTypeAEJ06(Minute value) {
        return new JAXBElement<Minute>(_AEJTypeAEJ06_QNAME, Minute.class, AEJType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Minute }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEJ03", scope = AEJType.class)
    public JAXBElement<Minute> createAEJTypeAEJ03(Minute value) {
        return new JAXBElement<Minute>(_AEJTypeAEJ03_QNAME, Minute.class, AEJType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEJ02", scope = AEJType.class)
    public JAXBElement<Integer> createAEJTypeAEJ02(Integer value) {
        return new JAXBElement<Integer>(_AEJTypeAEJ02_QNAME, Integer.class, AEJType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEJ05", scope = AEJType.class)
    public JAXBElement<Integer> createAEJTypeAEJ05(Integer value) {
        return new JAXBElement<Integer>(_AEJTypeAEJ05_QNAME, Integer.class, AEJType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEJ04", scope = AEJType.class)
    public JAXBElement<Integer> createAEJTypeAEJ04(Integer value) {
        return new JAXBElement<Integer>(_AEJTypeAEJ04_QNAME, Integer.class, AEJType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEJ01", scope = AEJType.class)
    public JAXBElement<Integer> createAEJTypeAEJ01(Integer value) {
        return new JAXBElement<Integer>(_AEJTypeAEJ01_QNAME, Integer.class, AEJType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AEKSType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEKS", scope = AEType.class)
    public JAXBElement<AEKSType> createAETypeAEKS(AEKSType value) {
        return new JAXBElement<AEKSType>(_AETypeAEKS_QNAME, AEKSType.class, AEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AEBType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEB", scope = AEType.class)
    public JAXBElement<AEBType> createAETypeAEB(AEBType value) {
        return new JAXBElement<AEBType>(_AETypeAEB_QNAME, AEBType.class, AEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AENSType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AENS", scope = AEType.class)
    public JAXBElement<AENSType> createAETypeAENS(AENSType value) {
        return new JAXBElement<AENSType>(_AETypeAENS_QNAME, AENSType.class, AEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AEMType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEM", scope = AEType.class)
    public JAXBElement<AEMType> createAETypeAEM(AEMType value) {
        return new JAXBElement<AEMType>(_AETypeAEM_QNAME, AEMType.class, AEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AEIType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEI", scope = AEType.class)
    public JAXBElement<AEIType> createAETypeAEI(AEIType value) {
        return new JAXBElement<AEIType>(_AETypeAEI_QNAME, AEIType.class, AEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AEJType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEJ", scope = AEType.class)
    public JAXBElement<AEJType> createAETypeAEJ(AEJType value) {
        return new JAXBElement<AEJType>(_AETypeAEJ_QNAME, AEJType.class, AEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AEDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AED", scope = AEType.class)
    public JAXBElement<AEDType> createAETypeAED(AEDType value) {
        return new JAXBElement<AEDType>(_AETypeAED_QNAME, AEDType.class, AEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEL01", scope = AEType.class)
    public JAXBElement<Integer> createAETypeAEL01(Integer value) {
        return new JAXBElement<Integer>(_AETypeAEL01_QNAME, Integer.class, AEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AEGType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEG", scope = AEType.class)
    public JAXBElement<AEGType> createAETypeAEG(AEGType value) {
        return new JAXBElement<AEGType>(_AETypeAEG_QNAME, AEGType.class, AEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEI10", scope = AEIType.class)
    public JAXBElement<Integer> createAEITypeAEI10(Integer value) {
        return new JAXBElement<Integer>(_AEITypeAEI10_QNAME, Integer.class, AEIType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AEI01CType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEI01C", scope = AEIType.class)
    public JAXBElement<AEI01CType> createAEITypeAEI01C(AEI01CType value) {
        return new JAXBElement<AEI01CType>(_AEITypeAEI01C_QNAME, AEI01CType.class, AEIType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link jdo.sta.bean.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEI08", scope = AEIType.class)
    public JAXBElement<jdo.sta.bean.String> createAEITypeAEI08(jdo.sta.bean.String value) {
        return new JAXBElement<jdo.sta.bean.String>(_AEITypeAEI08_QNAME, jdo.sta.bean.String.class, AEIType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AEI09", scope = AEIType.class)
    public JAXBElement<Integer> createAEITypeAEI09(Integer value) {
        return new JAXBElement<Integer>(_AEITypeAEI09_QNAME, Integer.class, AEIType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AAD01C", scope = AAType.class)
    public JAXBElement<java.lang.String> createAATypeAAD01C(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_AATypeAAD01C_QNAME, java.lang.String.class, AAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ABAType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ABA", scope = ABType.class)
    public JAXBElement<ABAType> createABTypeABA(ABAType value) {
        return new JAXBElement<ABAType>(_ABTypeABA_QNAME, ABAType.class, ABType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ABHType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ABH", scope = ABType.class)
    public JAXBElement<ABHType> createABTypeABH(ABHType value) {
        return new JAXBElement<ABHType>(_ABTypeABH_QNAME, ABHType.class, ABType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ABGType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ABG", scope = ABType.class)
    public JAXBElement<ABGType> createABTypeABG(ABGType value) {
        return new JAXBElement<ABGType>(_ABTypeABG_QNAME, ABGType.class, ABType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ABFType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ABF", scope = ABType.class)
    public JAXBElement<ABFType> createABTypeABF(ABFType value) {
        return new JAXBElement<ABFType>(_ABTypeABF_QNAME, ABFType.class, ABType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ABDSType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ABDS", scope = ABType.class)
    public JAXBElement<ABDSType> createABTypeABDS(ABDSType value) {
        return new JAXBElement<ABDSType>(_ABTypeABDS_QNAME, ABDSType.class, ABType.class, value);
    }

}
