//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 10:28:02 ÉÏÎç CST 
//


package jdo.sta.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZBType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZBType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ZB01C" type="{}ZB01CType"/>
 *         &lt;element name="ZB02" type="{}ZB02Type"/>
 *         &lt;element name="ZB03" type="{}ZB03Type"/>
 *         &lt;element name="ZB04" type="{}String"/>
 *         &lt;element name="ZB05" type="{}String"/>
 *         &lt;element name="ZB06" type="{}TimeStamp"/>
 *         &lt;element name="ZB07" type="{}min1Integer"/>
 *         &lt;element name="ZB08" type="{}Email" minOccurs="0"/>
 *         &lt;element name="ZB09" type="{}MobilePhone" minOccurs="0"/>
 *         &lt;element name="ZB10" type="{}String" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZBType", propOrder = {
    "zb01C",
    "zb02",
    "zb03",
    "zb04",
    "zb05",
    "zb06",
    "zb07",
    "zb08",
    "zb09",
    "zb10"
})
public class ZBType {

    @XmlElement(name = "ZB01C", required = true)
    protected ZB01CType zb01C;
    @XmlElement(name = "ZB02", required = true)
    protected ZB02Type zb02;
    @XmlElement(name = "ZB03", required = true)
    protected ZB03Type zb03;
    @XmlElement(name = "ZB04", required = true)
    protected String zb04;
    @XmlElement(name = "ZB05", required = true)
    protected String zb05;
    @XmlElement(name = "ZB06", required = true)
    protected TimeStamp zb06;
    @XmlElement(name = "ZB07", required = true)
    protected Min1Integer zb07;
    @XmlElementRef(name = "ZB08", type = JAXBElement.class)
    protected JAXBElement<Email> zb08;
    @XmlElementRef(name = "ZB09", type = JAXBElement.class)
    protected JAXBElement<MobilePhone> zb09;
    @XmlElementRef(name = "ZB10", type = JAXBElement.class)
    protected JAXBElement<String> zb10;

    /**
     * Gets the value of the zb01C property.
     * 
     * @return
     *     possible object is
     *     {@link ZB01CType }
     *     
     */
    public ZB01CType getZB01C() {
        return zb01C;
    }

    /**
     * Sets the value of the zb01C property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZB01CType }
     *     
     */
    public void setZB01C(ZB01CType value) {
        this.zb01C = value;
    }

    /**
     * Gets the value of the zb02 property.
     * 
     * @return
     *     possible object is
     *     {@link ZB02Type }
     *     
     */
    public ZB02Type getZB02() {
        return zb02;
    }

    /**
     * Sets the value of the zb02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZB02Type }
     *     
     */
    public void setZB02(ZB02Type value) {
        this.zb02 = value;
    }

    /**
     * Gets the value of the zb03 property.
     * 
     * @return
     *     possible object is
     *     {@link ZB03Type }
     *     
     */
    public ZB03Type getZB03() {
        return zb03;
    }

    /**
     * Sets the value of the zb03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZB03Type }
     *     
     */
    public void setZB03(ZB03Type value) {
        this.zb03 = value;
    }

    /**
     * Gets the value of the zb04 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZB04() {
        return zb04;
    }

    /**
     * Sets the value of the zb04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZB04(String value) {
        this.zb04 = value;
    }

    /**
     * Gets the value of the zb05 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZB05() {
        return zb05;
    }

    /**
     * Sets the value of the zb05 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZB05(String value) {
        this.zb05 = value;
    }

    /**
     * Gets the value of the zb06 property.
     * 
     * @return
     *     possible object is
     *     {@link TimeStamp }
     *     
     */
    public TimeStamp getZB06() {
        return zb06;
    }

    /**
     * Sets the value of the zb06 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeStamp }
     *     
     */
    public void setZB06(TimeStamp value) {
        this.zb06 = value;
    }

    /**
     * Gets the value of the zb07 property.
     * 
     * @return
     *     possible object is
     *     {@link Min1Integer }
     *     
     */
    public Min1Integer getZB07() {
        return zb07;
    }

    /**
     * Sets the value of the zb07 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Min1Integer }
     *     
     */
    public void setZB07(Min1Integer value) {
        this.zb07 = value;
    }

    /**
     * Gets the value of the zb08 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Email }{@code >}
     *     
     */
    public JAXBElement<Email> getZB08() {
        return zb08;
    }

    /**
     * Sets the value of the zb08 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Email }{@code >}
     *     
     */
    public void setZB08(JAXBElement<Email> value) {
        this.zb08 = ((JAXBElement<Email> ) value);
    }

    /**
     * Gets the value of the zb09 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MobilePhone }{@code >}
     *     
     */
    public JAXBElement<MobilePhone> getZB09() {
        return zb09;
    }

    /**
     * Sets the value of the zb09 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MobilePhone }{@code >}
     *     
     */
    public void setZB09(JAXBElement<MobilePhone> value) {
        this.zb09 = ((JAXBElement<MobilePhone> ) value);
    }

    /**
     * Gets the value of the zb10 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getZB10() {
        return zb10;
    }

    /**
     * Sets the value of the zb10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setZB10(JAXBElement<String> value) {
        this.zb10 = ((JAXBElement<String> ) value);
    }

}
