//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 10:28:02 ÉÏÎç CST 
//


package jdo.sta.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ZA" type="{}ZAType"/>
 *         &lt;element name="ZB" type="{}ZBType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZType", propOrder = {
    "za",
    "zb"
})
public class ZType {

    @XmlElement(name = "ZA", required = true)
    protected ZAType za;
    @XmlElement(name = "ZB", required = true)
    protected ZBType zb;

    /**
     * Gets the value of the za property.
     * 
     * @return
     *     possible object is
     *     {@link ZAType }
     *     
     */
    public ZAType getZA() {
        return za;
    }

    /**
     * Sets the value of the za property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZAType }
     *     
     */
    public void setZA(ZAType value) {
        this.za = value;
    }

    /**
     * Gets the value of the zb property.
     * 
     * @return
     *     possible object is
     *     {@link ZBType }
     *     
     */
    public ZBType getZB() {
        return zb;
    }

    /**
     * Sets the value of the zb property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZBType }
     *     
     */
    public void setZB(ZBType value) {
        this.zb = value;
    }

}
