
package action.ind.stockclient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-04-02T11:37:56.575+08:00
 * Generated source version: 2.5.2
 * 
 */
public final class SpcStockService_SpcStockServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://stockinf.spc.jdo/", "SpcStockServiceImplService");

    private SpcStockService_SpcStockServiceImplPort_Client() {
    	
    }
    
    public static List<action.ind.stockclient.IndStock> onSearchIndStock() {
    	 URL wsdlURL = SpcStockServiceImplService.WSDL_LOCATION;
    	 SpcStockServiceImplService ss = new SpcStockServiceImplService(wsdlURL, SERVICE_NAME);
    	 SpcStockService port = ss.getSpcStockServiceImplPort();
         List<action.ind.stockclient.IndStock> list = port.onSearchIndStock();
         return list;
    }
    

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SpcStockServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SpcStockServiceImplService ss = new SpcStockServiceImplService(wsdlURL, SERVICE_NAME);
        SpcStockService port = ss.getSpcStockServiceImplPort();  
        
        {
        System.out.println("Invoking onSearchIndStock...");
        List<action.ind.stockclient.IndStock> _onSearchIndStock__return = port.onSearchIndStock();
        System.out.println("onSearchIndStock.result=" + _onSearchIndStock__return.size());


        }

        System.exit(0);
    }

}
