package action.ind.stockclient;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-04-02T11:37:56.871+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://stockinf.spc.jdo/", name = "SpcStockService")
@XmlSeeAlso({ObjectFactory.class})
public interface SpcStockService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "onSearchIndStock", targetNamespace = "http://stockinf.spc.jdo/", className = "action.ind.stockclient.OnSearchIndStock")
    @WebMethod
    @ResponseWrapper(localName = "onSearchIndStockResponse", targetNamespace = "http://stockinf.spc.jdo/", className = "action.ind.stockclient.OnSearchIndStockResponse")
    public java.util.List<action.ind.stockclient.IndStock> onSearchIndStock();		
}
