package action.spc.accountclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-05-21T10:36:52.172+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "IndAccountServiceImplService", 
                  wsdlLocation = "http://192.168.5.100:8080/webgy/services/indAccountService?wsdl",
                  targetNamespace = "http://inf.ind.jdo/") 
public class IndAccountServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://inf.ind.jdo/", "IndAccountServiceImplService");
    public final static QName IndAccountServiceImplPort = new QName("http://inf.ind.jdo/", "IndAccountServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.5.100:8080/webgy/services/indAccountService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IndAccountServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.5.100:8080/webgy/services/indAccountService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IndAccountServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IndAccountServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IndAccountServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IndAccountServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IndAccountServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IndAccountServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns IndAccountService
     */
    @WebEndpoint(name = "IndAccountServiceImplPort")
    public IndAccountService getIndAccountServiceImplPort() {
        return super.getPort(IndAccountServiceImplPort, IndAccountService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IndAccountService
     */
    @WebEndpoint(name = "IndAccountServiceImplPort")
    public IndAccountService getIndAccountServiceImplPort(WebServiceFeature... features) {
        return super.getPort(IndAccountServiceImplPort, IndAccountService.class, features);
    }

}
