package action.spc.phaSyncClient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.5.2 2013-08-14T17:51:31.770+08:00
 * Generated source version: 2.5.2
 * 
 */
public final class SPCPhaBaseSynchWsTool_SPCPhaBaseSynchWsToolImplPort_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://phaBaseSyncClient.spc.jdo/",
			"SPCPhaBaseSynchWsToolImplService");

	private SPCPhaBaseSynchWsTool_SPCPhaBaseSynchWsToolImplPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = SPCPhaBaseSynchWsToolImplService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		SPCPhaBaseSynchWsToolImplService ss = new SPCPhaBaseSynchWsToolImplService(
				wsdlURL, SERVICE_NAME);
		SPCPhaBaseSynchWsTool port = ss.getSPCPhaBaseSynchWsToolImplPort();

		{
			System.out.println("Invoking updatePhaTransUnit...");
			java.lang.String _updatePhaTransUnit_arg0 = "";
			java.lang.String _updatePhaTransUnit_arg1 = "";
			java.lang.String _updatePhaTransUnit_arg2 = "";
			java.lang.String _updatePhaTransUnit_arg3 = "";
			java.lang.String _updatePhaTransUnit_arg4 = "";
			java.lang.String _updatePhaTransUnit_arg5 = "";
			double _updatePhaTransUnit_arg6 = 0.0;
			double _updatePhaTransUnit_arg7 = 0.0;
			double _updatePhaTransUnit_arg8 = 0.0;
			double _updatePhaTransUnit_arg9 = 0.0;
			java.lang.String _updatePhaTransUnit_arg10 = "";
			java.lang.Object _updatePhaTransUnit_arg11 = new java.lang.Object();
			java.lang.String _updatePhaTransUnit_arg12 = "";
			java.lang.String _updatePhaTransUnit_arg13 = "";
			boolean _updatePhaTransUnit__return = port.updatePhaTransUnit(
					_updatePhaTransUnit_arg0, _updatePhaTransUnit_arg1,
					_updatePhaTransUnit_arg2, _updatePhaTransUnit_arg3,
					_updatePhaTransUnit_arg4, _updatePhaTransUnit_arg5,
					_updatePhaTransUnit_arg6, _updatePhaTransUnit_arg7,
					_updatePhaTransUnit_arg8, _updatePhaTransUnit_arg9,
					_updatePhaTransUnit_arg10, _updatePhaTransUnit_arg11,
					_updatePhaTransUnit_arg12, _updatePhaTransUnit_arg13);
			System.out.println("updatePhaTransUnit.result="
					+ _updatePhaTransUnit__return);

		}
		{
			System.out.println("Invoking updatePhaBase...");
			java.lang.String _updatePhaBase_arg0 = "";
			java.lang.String _updatePhaBase_arg1 = "";
			java.lang.String _updatePhaBase_arg2 = "";
			java.lang.String _updatePhaBase_arg3 = "";
			java.lang.String _updatePhaBase_arg4 = "";
			boolean _updatePhaBase__return = port.updatePhaBase(
					_updatePhaBase_arg0, _updatePhaBase_arg1,
					_updatePhaBase_arg2, _updatePhaBase_arg3,
					_updatePhaBase_arg4);
			System.out
					.println("updatePhaBase.result=" + _updatePhaBase__return);

		}

		System.exit(0);
	}

}
