
package jdo.pha.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */


import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;

import com.dongyang.config.TConfig;



/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-12-22T12:12:24.665+08:00
 * Generated source version: 2.5.2
 * 
 */
public final class PHADosageWsImplService_Client {

 //   private static final QName SERVICE_NAME = new QName("http://inf.spc.jdo/", "SpcServiceImplService");

    public PHADosageWsImplService_Client() {
    }
    
    private static  TConfig getProp() {
        TConfig config = TConfig.getConfig("WEB-INF\\config\\system\\TConfig.x");
        return config;
	}
 
	 public  static String getWebServicesIp(){
		 TConfig config = getProp() ;
		 String url = config.getString("", "WEB_SERVICES_IP");
		 return url;
	 }
	 
    
    public static SpcOpdOrderReturnDto getPhaStateReturn(String caseNo,String rxNo,String seqNo){
//    	 URL wsdlURL = SpcServiceImplService.WSDL_LOCATION;
//    	 SpcServiceImplService ss = new SpcServiceImplService(wsdlURL, SERVICE_NAME);
//    	 SpcService port = ss.getSpcServiceImplPort(); 
//    	 SpcOpdOrderReturnDto result = port.getPhaStateReturn(rxNo,caseNo,seqNo);
    	 
    	 
    	 String ip = getWebServicesIp();
     	String url = "http://"+ip+"/services/spcService" ;
     	JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean(); 
         factory.setAddress(url); 
         factory.setServiceClass(SpcService.class); 
         //factory.getInInterceptors().add(new LoggingInInterceptor()); 
         SpcService service = (SpcService) factory.create();
         SpcOpdOrderReturnDto result = service.getPhaStateReturn(rxNo,caseNo,seqNo);
         return result;
    }

    public static void main(String args[]) throws java.lang.Exception {
//        URL wsdlURL = SpcServiceImplService.WSDL_LOCATION;
//        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
//            File wsdlFile = new File(args[0]);
//            try {
//                if (wsdlFile.exists()) {
//                    wsdlURL = wsdlFile.toURI().toURL();
//                } else {
//                    wsdlURL = new URL(args[0]);
//                }
//            } catch (MalformedURLException e) {
//                e.printStackTrace();
//            }
//        }
//      
//        SpcServiceImplService ss = new SpcServiceImplService(wsdlURL, SERVICE_NAME);
//        SpcService port = ss.getSpcServiceImplPort();   
////        2c051007
//        
//        {
//        System.out.println("Invoking onSaveSpcRequest...");
////        SpcOpdOrderDtos _onSaveSpcRequest__return =  port.getOpdOrder( "1208010134","2012-04-11 00:00:00.0", "2012-12-11 10:00:00.0");
//        SpcOpdOrderReturnDto _onSaveSpcRequest__return = getPhaStateReturn("130208000950","1302080726", "4");//port.getOpdOrder("1204010137", "2011-01-01 00:00:00.0", "2012-12-21 01:00:00.0");//port.getOpdOrder( "1204010137","2011-04-11 00:00:00.0", "2012-12-11 10:00:00.0");
//        System.out.println("size:=" + _onSaveSpcRequest__return.getPhaCheckCode());
////        System.out.println("getRxNo:=" + _onSaveSpcRequest__return.getSpcOpdOrderDtos().get(0).getRxNo());
////         System.out.println("tSpcOpdOrderDtos:=" + _onSaveSpcRequest__return.getSpcOpdOrderDtos().get(0).getPatName());
////         System.out.println("st__retur:=" + _onSaveSpcRequest__return.getSpcOpdOrderDtos().get(0).getSeqNo());        
////         System.out.println("onSaveSpcRequest.result=" + _onSaveSpcRequest__return);
////        SpcDaoImpl.getInstance().onSavePhaOrder(_onSaveSpcRequest__return);
//
//        }
//       
//
//        System.exit(0);
    }

}
