Module.item=getNsCheckEXEFlg

//护士审核执行注记
getNsCheckEXEFlg.Type=TSQL
getNsCheckEXEFlg.SQL=SELECT NS_CHECK_FLG,DSPN_TIME,IVA_EXPANDTIME,ODI_DEFA_FREG,ODI_STAT_CODE,START_TIME,UDD_STAT_CODE FROM ODI_SYSPARM
getNsCheckEXEFlg.Debug=N



