Module.item=insertdata;selectdata;updatedata;deletedata;existsDrugAllergy;initAllergySourceCombo

// 查询全字段
selectdata.Type=TSQL
selectdata.SQL=SELECT MR_NO,ADM_DATE,DRUG_TYPE,DRUGORINGRD_CODE,ADM_TYPE,CASE_NO,DEPT_CODE,DR_CODE,ALLERGY_NOTE,OPT_USER,OPT_DATE,OPT_TERM FROM OPD_DRUGALLERGY ORDER BY ADM_DATE,DRUG_TYPE,DRUGORINGRD_CODE
selectdata.item= MR_NO;ADM_DATE;DRUG_TYPE;DRUGORINGRD_CODE
selectdata.MR_NO=MR_NO=<MR_NO>
selectdata.ADM_DATE=ADM_DATE=<ADM_DATE>
selectdata.DRUG_TYPE=DRUG_TYPE=<DRUG_TYPE>
selectdata.DRUGORINGRD_CODE=DRUGORINGRD_CODE=<DRUGORINGRD_CODE> 
selectdata.Debug=N

//插入数据（测试用）
insertdata.Type=TSQL
insertdata.SQL=INSERT INTO OPD_DRUGALLERGY VALUES (<MR_NO>,<ADM_DATE>,<DRUG_TYPE>,<DRUGORINGRD_CODE>,<ADM_TYPE>,<CASE_NO>,<DEPT_CODE>,<DR_CODE>,<ALLERGY_NOTE>,<OPT_USER>,<OPT_DATE>,<OPT_TERM>)
insertdata.Debug=N

//修改数据（测试用）
updatedata.Type=TSQL
updatedata.SQL=UPDATE OPD_DRUGALLERGY SET DRUGORINGRD_CODE=<DRUGORINGRD_CODE>,ADM_TYPE=<ADM_TYPE>,CASE_NO=<CASE_NO>,DEPT_CODE=<DEPT_CODE>,DR_CODE=<DR_CODE>,ALLERGY_NOTE=<ALLERGY_NOTE>,OPT_USER=<OPT_USER>,OPT_DATE=<OPT_DATE>,OPT_TERM=<OPT_TERM>
updatedata.item= MR_NO;ADM_DATE;DRUG_TYPE;DRUGORINGRD_CODE
updatedata.MR_NO=MR_NO=<MR_NO>
updatedata.ADM_DATE=ADM_DATE=<ADM_DATE>
updatedata.DRUG_TYPE=DRUG_TYPE=<DRUG_TYPE>
updatedata.DRUGORINGRD_CODE=DRUGORINGRD_CODE=<DRUGORINGRD_CODE>
updatedata.Debug=N

//删除数据（测试用）
deletedata.Type=TSQL
deletedata.SQL=DELETE OPD_DRUGALLERGY
deletedata.item= MR_NO;ADM_DATE;DRUG_TYPE;DRUGORINGRD_CODE
deletedata.MR_NO=MR_NO=<MR_NO>
deletedata.ADM_DATE=ADM_DATE=<ADM_DATE>
deletedata.DRUG_TYPE=DRUG_TYPE=<DRUG_TYPE>
deletedata.DRUGORINGRD_CODE=DRUGORINGRD_CODE=<DRUGORINGRD_CODE>
deletedata.Debug=N

//判断数据是否存在（测试用）
existsDrugAllergy.Type=TSQL
existsDrugAllergy.SQL=SELECT COUNT(CASE_NO) AS COUNT FROM OPD_DRUGALLERGY
existsDrugAllergy.item= MR_NO;ADM_DATE;DRUG_TYPE;DRUGORINGRD_CODE
existsDrugAllergy.MR_NO=MR_NO=<MR_NO>
existsDrugAllergy.ADM_DATE=ADM_DATE=<ADM_DATE>
existsDrugAllergy.DRUG_TYPE=DRUG_TYPE=<DRUG_TYPE>
existsDrugAllergy.DRUGORINGRD_CODE=DRUGORINGRD_CODE=<DRUGORINGRD_CODE>
existsDrugAllergy.Debug=N

//初始化过敏源combo
existsDrugAllergy.Type=TSQL
existsDrugAllergy.SQL=SELECT COUNT(CASE_NO) AS COUNT FROM OPD_DRUGALLERGY